#!/bin/bash

fasta_file=$1 #$(readlink - f $1)
work_dir=$2 #$(readlink -f $2)

#echo "$(readlink -f $fasta_file)"
fasta_file=$(readlink -f $fasta_file)
work_dir=$(readlink -f $work_dir)
############## The following are the hard paths to the different tools. Change them accordingly. ####################

hhsuite3_dir=/data/farhan/SoftwareTools/DeepComplexToolBox/tools/hhsuite-3.0-beta.3-Linux #/home/multicom4s_tool/ZComplexMSA/bin/hhsuite-3.0-beta.3-Linux #/data/farhan/SoftwareTools/DeepComplexToolBox/tools/hhsuite-3.2.0-SSE2-Linux
nr_db=/home/multicom4s_tool/alphafold_databases/data/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt  #### switch to BFD ###
nr_iteration_num=4

#######
### SET #### Currently settling these ...
hhblits_dir=/data/farhan/multicom4s/tool/multicom4s_TMB/tools_/hhblits/   #/home/fqg7h/multicom4s_TMB/tools/hhblits/   #### Change ####
multicom_tool_dir=/data/farhan/multicom4s/tool/multicom4s_TMB/tools_/ ## Local ##### Change #####
multicom_database_dir=/data/farhan/multicom4s/tool/multicom4s_TMB/databases ## Local ##### Change ####/data/farhan/multicom4s/tool

#### This is hhsuite 2.0 version 
hhsuite_dir=/data/farhan/multicom4s/tool/multicom4s_TMB/tools_/hhsuite-2.0.8-linux-x86_64/ #/data/farhan/SoftwareTools/DeepComplexToolBox/tools/hhsuite-2.0.16-linux-x86_64 #/data/farhan/SoftwareTools/DeepComplexToolBox/tools/hhsuite-3.0-beta.3-Linux  #/exports/store2/casp14/tools/hhsuite-2.0.8-linux-x86_64

#### Change the hhsuite DB ######
#### Currently settling these ...
hhsuitedb=/data/farhan/multicom4s/tool/multicom4s_TMB/tools_/update_db_hhsuite/hhsuitedb3 #/exports/store2/casp14/databases/update_db_hhsuite/hhsuitedb3 #####

##### Change this to one common directory
meta_dir=/data/farhan/multicom4s/tool/multicom4s_TMB/tools_/hhsuite
meta_common_dir=/exports/store2/casp14/tools/meta/

##### This is the .atom files of the heteromers
atom_dir=/exports/store2/casp14/databases/RCSB_PDB/atom/
align_option=$meta_dir/align_option  # Change the info at the align option file 
option_file=$same #Same stuff as here
prosys_dir=/exports/store2/casp14/tools/prosys/
script_dir=$prosys/scriptsacct

####################### End of Hard paths ##################################

fn=$(basename $fasta_file)
name=${fn%.*}

echo "FASTA $fasta_file"
echo "WORK_DIR $work_dir"
echo "NAME $name"

#exit 10

if [ ! -e $fasta_file ]; then
    echo "$fasta_file not found! Quitting!"
    exit 1
fi

if [ ! -d $work_dir ]; then
    mkdir -p $work_dir
    chmod +775 $work_dir
fi

#work_dir=$(readlink -f $2)

#cp $fasta_file $work_dir/

cd $work_dir

scp $fasta_file $work_dir


############## Generate msa using hhblits ###########################
#echo "Generate alignments from the bdf database using hhblits..."
#$hhsuite3_dir/bin/hhblits -i $work_dir/$name.fasta -d $nr_db -oa3m $work_dir/$name.a3m -n $nr_iteration_num
#if [ $? != 0 ]; then
#    echo "Alignment generation using hhblits problem. Quitting !!!"
#    exit 2
#fi

#echo "Alignments for $fasta_file successfully generated"

################ Add secondary structure into alignments #################
##### Modify the paths and add the tools in $hhblits_dir/scripts/addss_v2020.pl ###
echo "Adding Secondary structure information to a3m..."
perl $hhblits_dir/scripts/addss_v2020.pl $multicom_tool_dir $multicom_database_dir $work_dir/$name.a3m $work_dir/$name.ss.a3m -a3m

if [ $? != 0 ]; then
    echo "Unable to add Secondary structure information. Quitting !!!"
    exit 3
fi

echo "Secondary structure information successfully added to $workd_dir/$name.ss.a3m"


#### This is hhsuite 2.0 version 
#export HHLIB="$hhsuite_dir/lib/hh"


export HHLIB="$hhsuite3_dir"
##### Create the hidden markov model #############
echo "Creating Hidden Markov Models..." 
$hhsuite3_dir/bin/hhmake -i $name.ss.a3m -o $name.hmm
if [ $? != 0 ]; then
    echo "Unable to create HMM. Quitting !!!"
    #exit 4
fi

echo "HMM successfully created $workd_dir/$name.hmm"

#search shhm against the database
echo "Searching $name.hmm against $hhsuitedb...\n";

#### Remove any previous search results ##########
if [ -f $work_dir/$name.hhr ]; then
    echo "Removing existing $work_dir/$name.hhr ..."
    #rm $work_dir/$name.hhr
fi
echo "[Running] $hhsuite3_dir/bin/hhsearch -i $work_dir/$name.hmm -d $hhsuitedb -realign -mact 0"

#$hhsuite3_dir/bin/hhsearch -i $work_dir/$name.hmm -d $hhsuitedb -realign -mact 0

if [ ! -f $work_dir/$name.hhr ]; then
    echo "$work_dir/$name.hhr is not generated by hhsuite search. Try one more time using $name.ss.a3m ...\n"
    $hhsuite3_dir/bin/hhsearch -i $name.ss.a3m -d $hhsuitedb -realign -mact 0
    if [ -f $work_dir/$name.ss.hhr ]; then
        mv $name.ss.hhr $name.hhr
    fi
fi

if [ ! -f $work_dir/$name.hhr ]; then
    echo "$work_dir/$name.hhr is not generated by hhsuite search. Try one more time using $name.a3m ...\n"
    $hhsuite3_dir/bin/hhsearch -i $name.a3m -d $hhsuitedb -realign -mact 0
    
fi

if [ $? != 0 ]; then
    echo "Unable to perform hhsearch. Quitting !!!"
    exit 5
fi

echo "hhsearch successfully done"
##### End of Search #####

###### Now the rest #############
### 1. Rank the templates
echo "Generate ranking list..."
echo "[Running] $meta_dir/script/rank_templates.pl $name.hhr $work_dir/$name.rank"
$meta_dir/script/rank_templates.pl $name.hhr $work_dir/$name.rank

if [ $? != 0 ]; then
    echo "Unable to rank the templates. Quitting !!!"
    exit 5
fi

echo "Ranking successfully done"
