>P1;1A7NH_1A7NL
sequence:1A7NH_1A7NL::::::::
SFTIN------------------SVDM-KSLPDWTVQNGKQLTLQCFADVSTTSKPQHQMLFYKDDVLFY-------------------QISSMKSTESYFIPEVRIYDSGTYKCTVIVNNKEKTTAEYQLLVE----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*


>P1;5GNIA_5GNIB
 : : : : : : : : : 
SFTIN------------------SVDM-KSLPDWTVQNGKQLTLQCFADVSTTSKPQHQMLFYKDDVLFY-------------------QISSMKSTESYFIPEVRIYDSGTYKCTVIVNNKEKTTAEYQLLVEGVPSPRVTLDKKEAIQGGIVRVQCSVPEEKAPIHFTIEKLELNEKMVKLKREKNSRDQNFVILEFPVEEQDRVLSFRCQARIISGIHMQTSESTKSELVTSFTINSVDMKSLPDWTVQNGKQLTLQCFADVSTTSVKPQHQMLFYKDDVLFYQISSMKSTESYFIPEVRIYDSGTYKCTVIVNNKEKTTAEYQLLVEGVPSPRVTLDKKEAIQGGIVRVQCSVPEEKAPIHFTIEKLELNEKMVKLKREKNSRDQNFVILEFPVEEQDRVLSFRCQARIISGIHMQTSESTKSELVTV*

