>P1;1A7OH_1A7OL
sequence:1A7OH_1A7OL::::::::
-------------------------------------------------------------------------------------------QLLVEGVPSPRVTLDKKEAIQGGIVRVQCSVPEEK-APIHFTIEKLELNEK----------------MVKLKREKNSR--DQNFVILEFPVEEQDRVLSFRCQARIISGIHMQTSESTKSELVTSFTI-NSVDMK-SLPDWTVQNGKQLTLQCFADVSTTSVKPQHQMLFYKDDVLFYQISSMKSTESYFIPEVRIYDSGTYKCTVIVNNKEKTTAEYQLLVEGVPSPRVTLDKKEAIQGGIVRVQCSVPEEKAPIHFTIEKLELNEKMVKLKREKNSRDQNFVILEFP-----------------------------------*


>P1;5GNIA_5GNIB
 : : : : : : : : : 
SFTINSVDMKSLPDWTVQNGKQLTLQCFADVSTTSKPQHQMLFYKDDVLFYQISSMKSTESYFIPEVRIYDSGTYKCTVIVNNKEKTTAEYQLLVEGVPSPRVTLDKKEAIQGGIVRVQCSVPEEK-APIHFTIEKLELNEK----------------MVKLKREKNSR--DQNFVILEFPVEEQDRVLSFRCQARIISGIHMQTSESTKSELVTSFTI-NSVDMK-SLPDWTVQNGKQLTLQCFADVSTTSVKPQHQMLFYKDDVLFYQISSMKSTESYFIPEVRIYDSGTYKCTVIVNNKEKTTAEYQLLVEGVPSPRVTLDKKEAIQGGIVRVQCSVPEEKAPIHFTIEKLELNEKMVKLKREKNSRDQNFVILEFPVEEQDRVLSFRCQARIISGIHMQTSESTKSELVTV*

