>P1;1A7RH_1A7RL
sequence:1A7RH_1A7RL::::::::
-------------------------------------------------------------------------------------------QLLVEGVPSPRVTLDKKEAIQGGIVRVQCSVPEEK-APIHFTIEKLELNEK----------------MVKLKREKNSR--DQNFVILEFPVEEQDRVLSFRCQARIISGIHMQTSESTKSELVTSFTI-NSVDMK-SLPDWTVQNGKQLTLQCFADVSTTSVKPQHQMLFYKDDVLFYQISSMKSTESYFIPEVRIYDSGTYKCTVIVNNKEKTTAEYQLLVEGVPSPRVTLDKKEAIQGGIVRVQCSVPEEKAPIHFTIEKLELNEKMVKLKREKNSRDQNFVILEFP-----------------------------------*


>P1;5GNIA_5GNIB
 : : : : : : : : : 
SFTINSVDMKSLPDWTVQNGKQLTLQCFADVSTTSKPQHQMLFYKDDVLFYQISSMKSTESYFIPEVRIYDSGTYKCTVIVNNKEKTTAEYQLLVEGVPSPRVTLDKKEAIQGGIVRVQCSVPEEK-APIHFTIEKLELNEK----------------MVKLKREKNSR--DQNFVILEFPVEEQDRVLSFRCQARIISGIHMQTSESTKSELVTSFTI-NSVDMK-SLPDWTVQNGKQLTLQCFADVSTTSVKPQHQMLFYKDDVLFYQISSMKSTESYFIPEVRIYDSGTYKCTVIVNNKEKTTAEYQLLVEGVPSPRVTLDKKEAIQGGIVRVQCSVPEEKAPIHFTIEKLELNEKMVKLKREKNSRDQNFVILEFPVEEQDRVLSFRCQARIISGIHMQTSESTKSELVTV*

