>P1;1A6UL_1A6UH
sequence:1A6UL_1A6UH::::::::
S--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------PRVTLDKKEAIQGGIVRVQCSVPEE--KAPIHFTIEKLELNE------------KMVKLKREKNSRDQNFVILEFPVEEQDRVLSFRCQARIISG----I--------------HMQTSESTKSELVTV*


>P1;5GNIA_5GNIB
 : : : : : : : : : 
SFTINSVDMKSLPDWTVQNGKQLTLQCFADVSTTSKPQHQMLFYKDDVLFYQISSMKSTESYFIPEVRIYDSGTYKCTVIVNNKEKTTAEYQLLVEGVPSPRVTLDKKEAIQGGIVRVQCSVPEEKAPIHFTIEKLELNEKMVKLKREKNSRDQNFVILEFPVEEQDRVLSFRCQARIISGIHMQTSESTKSELVTSFTINSVDMKSLPDWTVQNGKQLTLQCFADVSTTSVKPQHQMLFYKDDVLFYQISSMKSTESYFIPEVRIYDSGTYKCTVIVNNKEKTTAEYQLLVEGVPSPRVTLDKKEAIQGGIVRVQCSVPEE--KAPIHFTIEKLELNE------------KMVKLKREKNSRDQNFVILEFPVEEQDRVLSFRCQARIISG----I--------------HMQTSESTKSELVTV*

