>P1;1A7QL_1A7QH
sequence:1A7QL_1A7QH::::::::
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------QLLVEGVPSPRVTLDKKEAIQGGIVRVQCSVPEEK-------------APIHFTIEKLELNEKMVKLKREKNSRDQNFVILEFPVEEQDRVLSFRCQARIIS----GI-------------HMQTSESTKSELVTV*

>P1;5GNIA_5GNIB
 : : : : : : : : : 
SFTINSVDMKSLPDWTVQNGKQLTLQCFADVSTTSKPQHQMLFYKDDVLFYQISSMKSTESYFIPEVRIYDSGTYKCTVIVNNKEKTTAEYQLLVEGVPSPRVTLDKKEAIQGGIVRVQCSVPEEKAPIHFTIEKLELNEKMVKLKREKNSRDQNFVILEFPVEEQDRVLSFRCQARIISGIHMQTSESTKSELVTSFTINSVDMKSLPDWTVQNGKQLTLQCFADVSTTSVKPQHQMLFYKDDVLFYQISSMKSTESYFIPEVRIYDSGTYKCTVIVNNKEKTTAEYQLLVEGVPSPRVTLDKKEAIQGGIVRVQCSVPEEK-------------APIHFTIEKLELNEKMVKLKREKNSRDQNFVILEFPVEEQDRVLSFRCQARIIS----GI-------------HMQTSESTKSELVTV*
