
>P1;5GNIB
sequence:5GNIB:    0: :    0: :::-1.00:-1.00
SFTINSVDMKSLPDWTVQNGKQLTLQCFADVSTTSVKPQHQMLFYKDDVLFYQISSMKSTESYFIPEVRIYDSGT
YKCTVIVNNKEKTTAEYQLLVEGVPSPRVTLDKKEAIQGGIVRVQCSVPEEKAPIHFTIEKLELNEKMVKLKREK
NSRDQNFVILEFPVEEQDRVLSFRCQARIISGIHMQTSESTKSELVTV*

>P1;5gniA
structure:5gniA:    1: :  196: :::-1.00:-1.00
SFTINSVDMKSLPDWTVQNGKQLTLQCFADVSTTS-KPQHQMLFYKDDVLFYQISSMKSTESYFIPEVRIYDSGT
YKCTVIVNNKEKTTAEYQLLVEGVPSPRVTLDKKEAIQGGIVRVQCSVPEEKAPIHFTIEKLELNEKMVKLKREK
NSRDQNFVILEFPVEEQDRVLSFRCQARIISGIHMQTSESTKSELVT-*

>P1;5gniB
structure:5gniB:    1: :  198: :::-1.00:-1.00
SFTINSVDMKSLPDWTVQNGKQLTLQCFADVSTTSVKPQHQMLFYKDDVLFYQISSMKSTESYFIPEVRIYDSGT
YKCTVIVNNKEKTTAEYQLLVEGVPSPRVTLDKKEAIQGGIVRVQCSVPEEKAPIHFTIEKLELNEKMVKLKREK
NSRDQNFVILEFPVEEQDRVLSFRCQARIISGIHMQTSESTKSELVTV*

>P1;5c14A
structure:5c14A:    1: :  199: :::-1.00:-1.00
SFTINSVDMKSLPDWTVQNGKNLTLQCFADVSTTSVKPQHQMLFYKDDVLFYNISSMKSTESYFIPEVRIYDSGT
YKCTVIVNNKEKTTAEYQLLVEGVPSPRVTLDKKEAIQGGIVRVNCSVPEEKAPIHFTIEKLELNEKMVKLKREK
NSRDQNFVILEFPVEEQDRVLSFRCQARIISGIHMQTSESTKSELVTV*

>P1;5c14B
structure:5c14B:    1: :  199: :::-1.00:-1.00
SFTINSVDMKSLPDWTVQNGKNLTLQCFADVSTTSVKPQHQMLFYKDDVLFYNISSMKSTESYFIPEVRIYDSGT
YKCTVIVNNKEKTTAEYQLLVEGVPSPRVTLDKKEAIQGGIVRVNCSVPEEKAPIHFTIEKLELNEKMVKLKREK
NSRDQNFVILEFPVEEQDRVLSFRCQARIISGIHMQTSESTKSELVTV*
