
>P1;1A1MA
sequence:1A1MA:    0: :    0: :::-1.00:-1.00
GSHSMRYFYTAMSRPGRGEPRFIAVGYVDDTQFVRFDSDAASPRTEPRPPWIEQEGPEYWDRNTQIFKTNTQTYR
ENLRIALRYYNQSEAGSHIIQRMYGCDLGPDGRLLRGHDQSAYDGKDYIALNEDLSSWTAADTAAQITQRKWEAA
RVAEQLRAYLEGLCVEWLRRYLENGKETLQRADPPKTHVTHHPVSDHEATLRCWALGFYPAEITLTWQRDGEDQT
QDTELVETRPAGDRTFQKWAAVVVPSGEEQRYTCHVQHEGLPKPLTLRWEPHH*

>P1;5gjyA
structure:5gjyA:    3: :  266: :::-1.00:-1.00
--HSLRYFYTAVSDPSPGVPQFVTVGSVDGEVFVRYDSE--TRKMEPRVDWIANVDQQYWDRETETSRGNEQIFR
VNLDTARERYNQSR-GSHTWQCMHGCDL-EDGS-IRGFQQCGYDGKDFIALDKDTLTYTAADAAAQITKRKWEEG
TVAEQWKNYLENTCIEWLRKYVSYGKDVLERRERPKVR-----VSGMELTLSCRAHGFYPPPISISWLKDGVVQE
QETKRGSTVPNSDGTYHAWATIDVLPGNRDKYQCRVEHASLPQPGLFSW----*

>P1;6wzyA
structure:6wzyA:    2: :  275: :::-1.00:-1.00
GPHSMRYFETAVSRPGLEEPRYISVGYVDNKEFVRFDSDAENPRYEPRAPWMEQEGPEYWERETQKAKGQEQWFR
VSLRNLLGYYNQSAGGSHTLQQMSGCDLGSDWRLLRGYLQFAYEGRDYIALNEDLKTWTAADMAAQITRRKWEQS
GAAEHYKAYLEGECVEWLHRYLKNGNATLLRTDSPKAHVTHHPRSKGEVTLRCWALGFYPADITLTWQLNGEELT
M--ELVETRPAGDGTFQKWASVVVPLGKEQNYTCRVYHEGLPEPLTLRWEP--*

>P1;1iebB
structure:1iebB:   58: :  214: :::-1.00:-1.00
---------------------------------------------------------------------------
------------------------------------------YNLEENLRFDSDVGEFRAVTELGRPDAENWNSP
EFLEQKRAEVDTVC----RHNYEIFDNFLRRVEPTVTYPTKTQPLEHHNLLVCSVSDFYPGNIEVRWFRNGKE--
EKTGIVSTGLVGDWTFQTLVMLETVPQSGEVYTCQVEHPSLTDPVTVEW----*

>P1;1b3jA
structure:1b3jA:    3: :  255: :::-1.00:-1.00
--HSLRYNLTVLSWDGSVQSGFLTEVHLDGQPFLRCDRQKC--RAKPQGQWAEDVGNKTWDRETRDLTGN----G
KDLRMTLAHIKDQKEGLHSLQEIRVCEIHEDNS-TRSSQHFYYDGELFLSQNLETKEW----TMPQSSRAQTLAM
NVRNFLKEDAMADCLQELRRYLKSG-VVLRRTVPPMVNVTRSEASEGNITVTCRASGFYPWNITLSWRQDGVSLS
HDTQWGDVLPDGNGTYQTWVATRICQGEEQRFTCYMEHSG-------------*

>P1;1ktdB
structure:1ktdB:   59: :  215: :::-1.00:-1.00
---------------------------------------------------------------------------
------------------------------------------YNLEENLRFDSDVGEFRAVTELGRPDAENWNSP
EFLEQKRAEVDTVC----RHNYEIFDNFLRRVEPTVTYPTKTQPLEHHNLLVCSVSDFYPGNIEVRWFRNGKE--
EKTGIVSTGLVGDWTFQTLVMLETVPQSGEVYTCQVEHPSLTDPVTVEW----*

>P1;5f1nA
structure:5f1nA:    1: :  275: :::-1.00:-1.00
GSHSLRYFYTSVSRPGRGDPRFIAVGYVDDTQFVRFDSDAATGRTEPRAPWVEQEGPEYWDGETRKVKETAQVYR
VDLDTLRGYYNQSEAGSHTIQTMYGCDLGPGGRLLRGYRQDAYDGADYIALNEDLRSWTAADTAAQITRRKWEAA
GVAEQWRNYLETTCVEWLQRYLEMGKETLLRAEPPSTRVTRHPISDHEVTLRCWALGFYPAEITLTWQRDGEDQT
QDTEVVDTRPAGDGTFQKWAAVVVPSGQEQRYTCHVQHEGLVEPVTRRW----*

>P1;5f1nB
structure:5f1nB:    5: :   96: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------PPKIQVSRHPAENGKPNLNCYVSGFHPPEIEIDLLKNGKEKA
EQTDLSFSK---DWTFYLLVHTEFTPNEQDEFSCRVKHVTLSEPQIVKWD---*

>P1;4nt6A
structure:4nt6A:    2: :  274: :::-1.00:-1.00
-SHSMRYFYTAVSRPGRGEPRFIAVGYVDDTQFVQFDSDAASPRGEPRAPWVEQEGPEYWDRETQKYKRQAQTDR
VSLRNLRGYYNQSEAGSHTLQRMYGCDLGPDGRLLRGYNQFAYDGKDYIALNEDLRSWTAADTAAQITQRKWEAA
RTAEQLRAYLEGTCVEWLRRYLENGKKTLQRAEHPKTHVTHHPVSDHEATLRCWALGFYPAEITLTWQRDGEDQT
QDTELVETRPAGDGTFQKWAAVVVPSGEEQRYTCHVQHEGLPEPLTLRW----*

>P1;1d5mB
structure:1d5mB:   27: :  179: :::-1.00:-1.00
---------------------------------------------------------------------------
--------------------------------------DRYFYHQEEYVRFDSDVGEYRAVTELGRPDAEYWNSQ
KLLEQKRAAVDTYC---RHNYGVGESFTVQRRVYPE--VTVYPAN----LLVCSVNGFYPGSIEVRWFRNGQEEK
TGVVSTGLIQNGDWTFQTLVMLETVPRSGEVYTCQVEHPSVTSPLTVEW----*

>P1;1tmcA
structure:1tmcA:    1: :  175: :::-1.00:-1.00
GSHSMRYFYTSVSRPGRGEPRFIAVGYVDDTQFVRFDSDAASQRMEPRAPWIEQEGPEYWDRNTRNVKAQSQTDR
VDLGTLRGYYNQSEAGSHTIQMMYGCDVGSDGRFLRGYRQDAYDGKDYIALKEDLRSWTAADMAAQTTKHKWEAA
HVAEQWRAYLEGTCVEWLRRYLENG--------------------------------------------------
-----------------------------------------------------*

>P1;5d1zC
structure:5d1zC:  119: :  201: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
------------------------------------------PPSDEQASVVCLLNNFYPREAKVQWKVDNALQS
GNSESVTEQDSKDSTYSLSSTLTLSKADYEKYACEVTHQGLSSPVT-------*

>P1;4nhuE
structure:4nhuE:    1: :  175: :::-1.00:-1.00
GPHSMRYFETAVSRPGLGEPRYISVGYVDDKEFVRFDSDAENPRYEPQVPWMEQEGPEYWERITQVAKGQEQWFR
VNLRTLLGYYNQSAGGTHTLQRMYGCDVGSDGRLLRGYEQFAYDGCDYIALNEDLRTWTAADMAAQITRRKWEQA
GAAEYYRAYLEGECVEALHRYLKNG--------------------------------------------------
-----------------------------------------------------*

>P1;6nhaA
structure:6nhaA:    3: :  252: :::-1.00:-1.00
---SLLYHLTAVSSPAPGTPAFWVSGWLGPQQYLSYNS--LRGEAEPCGAWV-WENSWYWEKETTDLRIKEKLFL
EAFK-AL-----GGKGPYTLQGLLGCELGPDATSV-PTAKFALNGEEFMNFDLKQGTWGGDPEALAISQRWQQQD
KAANKELTFLLFSCPHRLREHLEEWKE------PPSMRLKARPSSPGFSVLTCSAFSFYPPELQLRFLRNG--LA
AGTGQGDFGPNSDGSFHASSSLTVKSGDEHHYCCIVQHAGLAQPL--------*

>P1;1je6A
structure:1je6A:    4: :  266: :::-1.00:-1.00
--HSLRYNLMVLSQDGSVQSGFLAEGHLDGQPFLRYDRQ--KRRAKPQGQWAEDVGAETWDTETEDLTENGQ---
-DLRRTLTHIKDQKGGLHSLQEIRVCEIHEDSS-TRGSRHFYYNGELFLSQNLETQESTVAQTLAMNVTNFWDAM
KTKTHYRA-MQADCLQKLQRYLKSG-VAIRRTVPPMVNVTCSEVSEGNITVTCRASSFYPRNITLTWRQDGVSLS
HNTQWGDVLPDGNGTYQTWVATRIRQGEEQRFTCYMEHSG-------------*

>P1;1kjmA
structure:1kjmA:    1: :  276: :::-1.00:-1.00
GSHSLRYFYTAVSRPGLGEPRFIAVGYVDDTEFVRFDSDAENPRMEPRARWMEREGPEYWEQQTRIAKEWEQIYR
VDLRTLRGYYNQSEGGSHTIQEMYGCDVGSDGSLLRGYRQDAYDGRDYIALNEDLKTWTAADFAAQITRNKWERA
RYAERLRAYLEGTCVEWLSRYLELGKETLLRSDPPEAHVTLHPRPEGDVTLRCWALGFYPADITLTWQLNGEDLT
QDMELVETRPAGDGTFQKWASVVVPLGKEQNYTCRVEHEGLPKPLSQRWEP--*

>P1;1kjvA
structure:1kjvA:    1: :  276: :::-1.00:-1.00
GSHSLRYFDIAVSRPGLGEPRYISVGYVDDTEFARYDSDAENRRYQPRARWMEREGPEYWERNTPIYKGKEQTFR
VNLRTLRGYYNQSEGGSHTIQEMYGCDVGSDGSLLRGYEQFAYDGRDYIALNEDLKTWTAADFAARISRNKLERD
GFADLHRAYLEGECVESLRRYLELGKETLLRSDPPKAHVTLHPRPEGDVTLRCWALGFYPADITLTWQLNGEDLT
QDMELVETRPAGDGTFQKWASVVVPLGKEQNYTCRVEHEGLPKPLSQRWEP--*

>P1;6gh1A
structure:6gh1A:    1: :  274: :::-1.00:-1.00
GSHSLKYFHTSVSRPGRGEPRFISVGYVDDTQFVRFDNDAASPRMVPRAPWMEQEGSEYWDRETRSARDTAQIFR
VNLRTLRGYYNQSEAGSHTLQWMHGCELGPDGRFLRGYEQFAYDGKDYLTLNEDLRSWTAVDTAAQISEQKSNDA
SEAEHQRAYLEDTCVEWLHKYLEKGKETLLHLEPPKTHVTHHPISDHEATLRCWALGFYPAEITLTWQQDGEGHT
QDTELVETRPAGDGTFQKWAAVVVPSGEEQRYTCHVQHEGLPEPVTLRW----*

>P1;4cw1A
structure:4cw1A:    3: :  271: :::-1.00:-1.00
--HTLRYIQTAMTDPGPGQPWFVTVGYVDGELFVHYNSTAR--RVVPRTEWMANTDQQYWNGQTQIVQGNEQIDR
DDLGTLQRRYNQT-GGSHTVQLMYGCDILEDG-TIRGYSQDAYDGRDFIAFDKGTMTFTAAVPEAVPTKRKWEEG
DYAEGLKQYLEETCVEWLRRYVEYGKAELGRRERPEVRVWGKE-ADGILTLSCRAHGFYPRPIVVSWLKDGAVRG
QDAQSGGIVPNGDGTYHTWVTIDAQPGDGDKYQCRVEHASLPQPGLYSWE---*

>P1;4zuuA
structure:4zuuA:    1: :  274: :::-1.00:-1.00
GSHSMRYFYTAVSRPGRGEPRFIAVGYVDDTQFVRFDSDAASPRMEPRAPWVEQEGPEYWERETRNMKEATQNFR
VGLNTLHGYYNQSEAGSHTLQRMYGCDVGPDGRLLRGYRQDAYDGADYIALNEDLRSWTAADAAAQITRRKREEA
GEAEQCRNYLEGTCVEWLLRYLENGNETLQRADAPKTHVTHHPISDHEVTLRCWALGFYPEEISLSWQRDGEDVT
QDTEFVETRPAGDRTFQKWAAVVVPSGEEQRYTCHVQHEGLAEPVTLRW----*

>P1;2fseA
structure:2fseA:   84: :  176: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------PEVTVLSRSPVNLGEPNLICFIDKFSPPVVNVTWLRNGRPVT
EGVSETVFLPRDDHLFRKFHYLTFLPSTDDFYDCEVDHWGLEEPLRKHWE---*

>P1;2fseB
structure:2fseB:   24: :  185: :::-1.00:-1.00
---------------------------------------------------------------------------
--------------------------------------ERCIYNQEESVRFDSDVGEYRAVTELGRPDAEYWNSQ
KLLEQRRAAVDTYC---RHNYGVGESFTVQRRVEPT--VTVYPTKQHHNLLVCSVSDFYPGNIEVRWFRNGKE--
EETGIVSTGLVGDWTFQTLVMLETVPQSGEVYTCQVEHPSLTDPVTVEWK---*

>P1;3vj6A
structure:3vj6A:    3: :  276: :::-1.00:-1.00
--HSLRYFTTAVSRPGLGEPRFIIVGYVDDTQFVRFDSDAENPRMEPRARWIEQEGPEYWERETWKARDMGRNFR
VNLRTLLGYYNQSNDESHTLQWMYGCDVGPDGRLLRGYCQEAYDGQDYISLNEDLRSWTANDIASQISKHKSEAV
DEAHQQRAYLQGPCVEWLHRYLRLGNETLQRSDPPKAHVTHHPRSEDEVTLRCWALGFYPADITLTWQLNGEELT
QDMELVETRPAGDGTFQKWAAVVVPLGKEQYYTCHVYHEGLPEPLTLRWEP--*

>P1;2vuoA
structure:2vuoA:  117: :  203: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
----------------------------------PKVYTMGPPLSSRSVSLTCMINGFYPSDISVEWEKNGKAE-
---DNYKTTPASDGSYFLYSKLSVPTSEWQRFTCSVMHEAL------------*

>P1;5ni9A
structure:5ni9A:   86: :  178: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------PEVTVLTNSPVELREPVLICFIDKFTPPVVNVTWLRNGKPVT
TGVSETVFLPREDHLFRKFHYLPFLPSTEDVYDCRVEHWGLDEPLLKHWE---*

>P1;5ni9B
structure:5ni9B:   27: :  187: :::-1.00:-1.00
---------------------------------------------------------------------------
--------------------------------------DRYFYHQEEYVRFDSDVGEYRAVTELGRPDAEYWNSQ
KLLEQKRAAVDTYC---RHNYGVGESFTVQRRVYPE--VTVYPAKQHHNLLVCSVNGFYPGSIEVRWFRNGQEEK
TGVVSTGLIQNGDWTFQTLVMLETVPRSGEVYTCQVEHPSLTSPLTVEW----*

>P1;2zokA
structure:2zokA:    2: :  251: :::-1.00:-1.00
--HSMRYFETAVSRPGLEEPRYISVGYVDNKEFVRFDSDAENPRYEPRAPWMEQEGPEYWERETQKAKGQEQWFR
VSLRNLLGYYNQSAGGSHTLQQMSGCDLGSDWRLLRGYLQFAYEGRDYIALNEDLKTWTAADMAAQITRRKWEQS
GAAEHYKAYLEGECVEWLHRYLKNGNATLLRTDSPKAHVTHH-------TLRCWALGFYPADITLTWM-------
---ELVETRPAGDGTFQKWASVVV-----QNY-CRVYHEGLPEPLTLRWE---*

>P1;6rpbK
structure:6rpbK:    1: :  259: :::-1.00:-1.00
GSHSMRYFFTSVSRPGRGEPRFIAVGYVDDTQFVRFDSDAASQRMEPRAPWIEQEGPEYWDGETRKVKAHSQTHR
VDLGTLRGYYNQSEAGSHTVQRMYGCDVGSDWRFLRGYHQYAYDGKDYIALKEDLRSWTAADMAAQTTKHKWEAA
HVAEQLRAYLEGTCVEWLRRYLENGKETLQRTDAPKTHMTHHAV----ATLRCWALSFYPAEITLTWQR------
-DTELVETRPAGDGTFQKWAAVVV----EQRYTCHVQHEGLPKPLTLRW----*

>P1;6bgaB
structure:6bgaB:   56: :  206: :::-1.00:-1.00
---------------------------------------------------------------------------
------------------------------------------YNLEENLRFDSDVGEFRAVTELGRPDAENWNSP
EFLEQKRAEVDTVC----RHNYEIFDNFLRRVEPT---VTVYPTKN---LLVCSVSDFYPGNIEVRWFRNGKE--
EKTGIVSTGLVGDWTFQTLVMLETVPQSGEVYTCQVEHPSLTDPVTVEWK---*

>P1;5m3vB
structure:5m3vB:   42: :  163: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---EEVVSVLTVLHQDWL-----NGKETISKAQPREPEVATFPLTKNQVTLVCLVTGFYPSDIAVEWESNGQPEN
NDPPLLES----DGSFALSSRLRVDKSRWQQFSCSVMHEAL------------*

>P1;4l4vC
structure:4l4vC:    3: :  250: :::-1.00:-1.00
-THSLRYFRLGVSDPIHGVPEFISVGYVDSHPITTYDS--VTRQKEPRAPWMENLAPDHWERYTQLLRGWQQMFK
VELKRLQRHYNHS--GSHTYQRMIGCELLEDGS-TTGFLQYAYDGQDFLIFNKDTLSWLAVDNVAHTIKQAWEAN
Q-HELLKNWLEEECIAWLKRFLEYGKDTLQRTEPPLVRV------NRKTALFCKAHGFYPPEIYMTWMKNGE---
-EIDYGDILPSGDGTYQAWASIEL----SNLYSCHVEHSGV------------*

>P1;1zagD
structure:1zagD:    1: :  263: :::-1.00:-1.00
GRYSLTYIYTGLSKHVEDVPAFQALGSLNDLQFFRYNS--KDRKSQPMGLWRQVEGMEDWKQDSQLQKAREDIFM
ETLKDIVEYYNDSN-GSHVLQGRFGCEI-ENNRSSGAFWKYYYDGKDYIEFNKEIPAWVPFDPAAQITKQKWEAE
PVVQRAKAYLEEECPATLRKYLKYSKNILDRQDPPSVVVTSHQAPGEKKKLKCLAYDFYPGKIDVHWTRAGE--V
QEPELGDVLHNGNGTYQSWVVVA--------YSCHVQHSSLAQPLVVPWE---*

>P1;6e1iA
structure:6e1iA:  111: :  385: :::-1.00:-1.00
GSHSMRYFFTSVSRPGRGEPRFIAVGYVDDTQFVRFDSDAASQRMEPRAPWIEQEGPEYWDGETRKVKAHSQTHR
VDLGTLRGAYNQSEAGSHTVQRMYGCDVGSDWRFLRGYHQYAYDGKDYIALKEDLRSWTAADMAAQTTKHKWEAA
HVAEQLRAYLEGTCVEWLRRYLENGKETLQRTDSPKAHVTYHPRSQVDVTLRCWALGFYPADITLTWQLNGEDLT
QDMELVETRPAGDGTFQKWAAVVVPLGKEQNYTCHVHHEGLPEPLTLRWE---*

>P1;1k5nA
structure:1k5nA:    1: :  276: :::-1.00:-1.00
GSHSMRYFHTSVSRPGRGEPRFITVGYVDDTLFVRFDSDAASPREEPRAPWIEQEGPEYWDRETQICKAKAQTDR
EDLRTLLRYYNQSEAGSHTLQNMYGCDVGPDGRLLRGYHQHAYDGKDYIALNEDLSSWTAADTAAQITQRKWEAA
RVAEQLRAYLEGECVEWLRRYLENGKETLQRADPPKTHVTHHPISDHEATLRCWALGFYPAEITLTWQRDGEDQT
QDTELVETRPAGDRTFQKWAAVVVPSGEEQRYTCHVQHEGLPKPLTLRWEP--*

>P1;4en3C
structure:4en3C:   45: :  257: :::-1.00:-1.00
-------------------------------------------------PWSQGTSDQQWETLQHIFRVYRSSFT
RDVKEFAKMLRLSYPLE--LQVSAGCEVHPAS---NNFFHVAFQGKDILSFQG--TSWEPTQEAQVLNQDKW---
-TRETVQWLLNGTCPQFVSGLLESGKSELKKQVKPKAWLSRGP---SPLLLVCHVSGFYPKPVWVKWMRQ-----
QGTQPGDILPNADETWYLRATLVVAAG----LSCRVKHSSLEQDIVLYW----*

>P1;1kcgC
structure:1kcgC:    2: :  170: :::-1.00:-1.00
-AHSLWYNFTIIHLPRHGQQWCEVQSQVDQKNFLSY--DCGSDKVLSMGHLEEQYATDAWGKQLEMLREVGQ---
-RLRLEL-----ADTEPLTLQVRMSCECEADG-YIRGSWQFSFDGRKFLLFDSNNRKWTVVHAGARRMKEKWEKS
GLTTFFKMVSMRDCKSWLRDFLMHRKKRLE---------------------------------------------
-----------------------------------------------------*

>P1;3wexB
structure:3wexB:   36: :  193: :::-1.00:-1.00
---------------------------------------------------------------------------
------------------------------------------YNREELVRFDSDVGEFRAVTELGRPEAEYWNSQ
KILEEKRAVPDRMC---RHNYELDEAVTLQRRVQPKVNVSPSKKGQHHNLLVCHVTDFYPGSIQVRWFLNGQEET
AGVVSTNLIRNGDWTFQILVMLEMTPQQGDVYICQVEHTSLDSPVTVEWK---*

>P1;5weuA
structure:5weuA:    1: :  273: :::-1.00:-1.00
-SHSLRYFVTAVSRPGFGEPRYMEVGYVDNTEFVRFDSDAENPRYEPRARWIEQEGPEYWERETRRAKGNEQCFR
VDLRTALRYYNQSAGGSHTLQWMAGCDVESDGRLLRGYWQFAYDGCDYIALNEDLKTWTAADMAAQITRRKWEQA
GAAERDRAYLEGECVEWLRRYLKNGNATLLRTDPPKAHVTHHRRPEGDVTLRCWALGFYPADITLTWQLNGEELT
QEMELVETRPAGDGTFQKWASVVVPLGKEQKYTCHVEHEGLPEPLTLRW----*

>P1;3ln4A
structure:3ln4A:    1: :  274: :::-1.00:-1.00
GSHSMRYFHTAMSRPGRGEPRFITVGYVDDTLFVRFDSDATSPRKEPRAPWIEQEGPEYWDRETQISKTNTQTYR
ESLRNLRGYYNQSEAGSHTLQRMYGCDVGPDGRLLRGHNQYAYDGKDYIALNEDLRSWTAADTAAQITQRKWEAA
RVAEQDRAYLEGTCVEWLRRYLENGKDTLERADPPKTHVTHHPISDHEATLRCWALGFYPAEITLTWQRDGEDQT
QDTELVETRPAGDRTFQKWAAVVVPSGEEQRYTCHVQHEGLPKPLTLRW----*

>P1;1lnuB
structure:1lnuB:   32: :  216: :::-1.00:-1.00
---------------------------------------------------------------------------
-----------------HFVYQFMGCYFTNGTQRIRYVTRYIYNREEYVRYDSDVGEHRAVTELGRPDAEYWNSP
EILERTRAELDTVC-----RHNYEGPETLRRLEQPNVSLSRTEALNHHNTLVCSVTDFYPAKIKVRWFRNGQEET
VGVSSTQLIRNGDWTFQVLVMLEMTPRRGEVYTCHVEHPSLKSPITVEWK---*

>P1;5swzP
structure:5swzP:    1: :  238: :::-1.00:-1.00
GPHSMRYFETAVSRPGLEEPRYISVGYVDNKEFVRFDSDAENPRYEPRAPWMEQEGPEYWERETQKAKGQEQWFR
VSLRNLLGYYNQSAGGSHTLQQMSGCDLGSDWRLLRGYLQFAYEGRDYIALNEDLKTWTAADMAAQITRRKWEQS
GAAEHYKAYLEGECVEWLHRYLKNGNATLLRTDSPKAHV----------TLRCWALGFYPADITLT---------
--MELVETRPAGDGTFQKWA------------SCRVYHEGLPEPLT-------*

>P1;2zpkL
structure:2zpkL:   89: :  201: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-------------CALWYNHWVFGGGTKLTVLGQPKSSVTLFPPSSEEATLVCTITDFYPGVVTVDWKVDGTPVT
QGMETTQPSKQSNNKYMASSYLTLTARAWERYSCQVTHEG-------------*

>P1;2zpkM
structure:2zpkM:   89: :  201: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-------------CALWYNHWVFGGGTKLTVLGQPKSSVTLFPPSSEEATLVCTITDFYPGVVTVDWKVDGTPVT
QGMETTQPSKQSNNKYMASSYLTLTARAWERYSCQVTHEG-------------*

>P1;6kwlA
structure:6kwlA:    1: :  275: :::-1.00:-1.00
GPHSLSYFYTAVSRPDRGDSRFIAVGYVDDTQFVRFDNYAPNPRMEPRVPWIQQEGQEYWDRETRNVKETAQTYG
VGLNTLRGYYNQSEAGSHTLQSMYGCYLGPDGLLLHGYRQDAYDGADYIALNEDLRSWTAADMAAQITKRKWEAA
DEAERARSYLQGLCVESLRRYLEMGKDTLQRAEPPKTHVTRHPSSDLGVTLRCWALGFYPKEISLTWQREGQDQS
QDMELVETRPSGDGTFQKWAALVVPPGEEQSYTCHVQHEGLQEPLTLRWD---*

>P1;3fruA
structure:3fruA:    7: :  267: :::-1.00:-1.00
----LMYHLAAVSDLSTGLPSFWATGWLGAQQYLTYNN--LRQEADPCGAWIENQVSWYWEKETTDLKSKEQLFL
EAIRTLENQIN----GTFTLQGLLGCELAPDNSSL-PTAVFALNGEEFMRFNPRTGNWSGTDIVGNLWMKQPEAA
RKESE---FLLTSCPERLLGHLERGRQNLEWKEPPSMRLKARPGNSGSSVLTCAAFSFYPPELKFRFLRNG--LA
SGSGNCSTGPNGDGSFHAWSLLEVKRGDEHHYQCQVEHEGLAQPLTV------*

>P1;1pqzA
structure:1pqzA:    1: :  237: :::-1.00:-1.00
GSESLRYAYTLVVDGTANTARCFGTGHVDGEAFVGYSNN-------------KTHGIGRWVNASHVEEENKEFVR
QCKELQAELDKMQNNSAVIGVKTVQLDVGCTSKIEKHY---AYDGNE-----------TEDDTATSASER----A
RDCQ--------------KKLTEYRKLVLASAVSPQLEVERRS-SGREGRLRCFARDYYPADLEIRWWKDGALPQ
TSKQHHDPLPSGQGLYQKHIDVYVDGGLEHVYSCRV--KGIATGLELRWK---*

>P1;1zs8A
structure:1zs8A:    1: :  260: :::-1.00:-1.00
-SHWLKTFRIVIMEPGILEPRFIQVSYVDSIQYQGFDSRSG---MQPRAAWMKQEPPEYWKNETEHAMGASLLAR
RTLIYMVTENNNKKNDYHTLQEVFGCNVAHDGSFLGGHYGLTYYGYDYIILNEDLNSWTTEGKVG----GKFNS-
-VTEGWRTYLKGECTERFLRCLDLGKETLLRSDAPRTHVTHKVT----VTLRCWALGFYPADITLTWKRDGKNHT
QDMELPDTRPAGDGTFQKWAAVVVPFGEELRYTCHVHHEGLPGPLTLKW----*

>P1;6jozA
structure:6jozA:    1: :  274: :::-1.00:-1.00
GSHSMRYFYTSVSRPGRGEPRFIAVGYVDDTQFVRFDSDAASQRMEPRAPWIEQEGPEYWDQETRNVKAQSQTDR
VDLGTLRGYYNQSEDGSHTIQIMYGCDVGPDGRFLRGYRQDAYDGKDYIALNEDLRSWTAADMAAQITKRKWEAA
HAAEQQRAYLEGRCVEWLRRYLENGKETLQRTDPPKTHMTHHPISDHEATLRCWALGFYPAEITLTWQRDGEDQT
QDTELVETRPAGDGTFQKWAAVVVPSGEEQRYTCHVQHEGLPKPLTLRW----*

>P1;1zvsA
structure:1zvsA:    1: :  278: :::-1.00:-1.00
GSHSMKYFYTSMSRPGRGQPRFIAVGYVDDTQFVRFDSDAASQRMEPRAPWVEQEGPEYWDRETRNMKTETQNAP
VNLRTLLRYYNQSEAGSHTLQRMVGCDLGPDGRLLRGYEQYAYDGKDYIALNEDLRSWTAADVAAQNTQRKWEAA
DVAESMRAYLEGQCVEWLPRYLEKGKETLQRTDPPKTHVTHHPVSDHEATLRCWALGFYPAEITLTWQRDGEDQT
QDTELVETRPAGDGTFQKWAAVVVPSGEEQRYTCHVQHEGLPKPHTLKWEPHH*

>P1;3dbxA
structure:3dbxA:   49: :  279: :::-1.00:-1.00
-------------------------------------------------PWVQEITAE-----TEVKKILSFS-M
VGIRNTIRFMHEAKAGPRVFQIHTGCKLYTNGTRW-SFVNIGEGGRDLVTYELSRERW--------VPQRSTLLA
KVMSDLRAFLEHIFSSSFPNYIEEGRTDLERRVPPMAVVFARTAGQVQLLLVCRVTSFYPRPIAVTWLRDGREVP
PSPALSTVLPNADLTYQLRSTLLVSPQDGHGYACRVQHCSLDRSLLVPW--HH*

>P1;3gmoA
structure:3gmoA:   15: :  266: :::-1.00:-1.00
----------------RSWSRTDSVVWLGDLQTHRWSNDSAT--ISFTKPWSQGKSNQQWEKLQHMFQVYRVSFT
RDIQELVKMMSPKEDYPIEIQLSAGCEMYP-GNASESFLHVAFQGKYVVRFWG--TSWQTVDLPIKVLNADQGTS
ATVQML---LNDTCPLFVRGLLEAGKSDLEKQEKPVAWLSSH------RQLVCHVSGFYPKPVWVMWMR-GDQEQ
QGTHRGDFLPNADETWYLQATLDVEAGEEAGLACRVKHSSLGQDIILYW----*

>P1;3g08A
structure:3g08A:   15: :  262: :::-1.00:-1.00
----------------RSWSRTDSVVWLGDLQTHRWSNDSAT--ISFTKPWSQGKSNQQWEKLQHMFQVYRVSFT
RDIQELVK---MMEDYPIEIQLSAGCEMYASESFL----HVAFQGKYVVRFWG--TSWQTVDLPIKVLNADQGTS
ATVQML---LNDTCPLFVRGLLEAGKSDLEKQEKPVAWLSSVP----HRQLVCHVSGFYPKPVWVMWMR-GDQEQ
QGTHRGDFLPNADETWYLQATLDVEAGEEAGLACRVKHSSLGQDIILYW----*

>P1;5kaqG
structure:5kaqG:   94: :  205: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
----------------WLRTFGQGTKLEIKTVAAPSVFI--FPPSDEQASVVCLLNNFYPREAKVQWKVDNALQS
GNSESVTEQDSKDSTYSLSSTLTLSKADYEKYACEVTHQGLSSPVT-------*

>P1;6ddmC
structure:6ddmC:    3: :   79: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------PPMVNVT------RSITVTCRASSFYPRNIILTWRQDGVSLS
HDTQWGDVLPDGNGTYQTWVATRICRGEEQRFTCYMEHSG-------------*

>P1;6t3yB
structure:6t3yB:   46: :  196: :::-1.00:-1.00
---------------------------------------------------------------------------
------------------------------------------YNRQQLVHFDSDVGKFVADTPLGEPQAEYWNSA
ELLENIMNIADGSC---RHNYGILESFTVQRSVEPKVRVSALQETDR---LACYVTGFYPPEIEVKWFLNGREET
ERVVSTDVMQNGDWTYQ--VLVVLETVPGDSYVCRVEHASLRQPISQAWE---*

>P1;6m2jA
structure:6m2jA:    1: :  274: :::-1.00:-1.00
GSHSMRYFYTSVSRPGLGEPRFIIVGYVDDTQFVRFDSDAASPRMEQRAPWMGQVEPEYWDQQTQIAKDTAQTFR
VNLNTALRYYNQSAAGSHTFQTMFGCEVWADGRFFHGYRQYAYDGADYIALNEDLRSWTAADTAAQNTQRKWEAA
GEAERHRAYLERECVEWLRRYLEMGKETLQRADPPKAHVTHHPASDREATLRCWALGFYPAEISLTWQRDGEDQT
QDTELVETRPGGDGTFQKWAAVVVPSGEEQRYTCRVQHEGLPEPLTLTW----*

>P1;1a6zA
structure:1a6zA:    2: :  272: :::-1.00:-1.00
-SHSLHYLFMGASEQDLGLSLFEALGYVDDQLFVFYDHE--SRRVEPRTPWVSSRSSQMWLQLSQSLKGWDHMFT
VDFWTIMENHNHSKE-SHTLQVILGCEMQEDNS-TEGYWKYGYDGQDHLEFCPDTLDWRAAEPRAWPTKLEWERH
KIARQNRAYLERDCPAQLQQLLELGRGVLDQQVPPLVKVTHH-VTSSVTTLRCRALNYYPQNITMKWLKDKQPDA
KEFEPKDVLPNGDGTYQGWITLAVPPGEEQRYTCQVEHPGLDQPLIVIW----*

>P1;6a6hA
structure:6a6hA:    1: :  275: :::-1.00:-1.00
GPHSLRYFDTAVSRPDRGEPRFIEVGYVDDTQFVRFDSDAPNPRMEPRAPWIQQEGQEYWDRNTRNAMGNAQIYR
GNLRTALGYYNQSEAGSHTLQIMYGCDVGPDGLLLRGYSQDAYDGADYIALNEDLRSWTAADTAAQITKRKWEAA
NVAEQWRSYLQGTCVEWLQKYLQMGKDTLQRAEPPKTHVTRHPSSDLGVTLRCWALGFYPKEISLTWQREGQDQS
QDMELVETRPSGDGTFQKWAALVVPPGEEQSYTCHVQHEGLQEPLTLRWD---*

>P1;1a6aB
structure:1a6aB:   24: :  184: :::-1.00:-1.00
---------------------------------------------------------------------------
--------------------------------------DRYFHNQEENVRFDSDVGEFRAVTELGRPDAEYWNSQ
KLLEQKRGRVDNYC---RHNYGVVESFTVQRRVHPK--VTVYPSKQHHNLLVCSVSGFYPGSIEVRWFRNGQEEK
TGVVSTGLIHNGDWTFQTLVMLETVPRSGEVYTCQVEHPSVTSPLTVEW----*

>P1;4e41G
structure:4e41G:   25: :  175: :::-1.00:-1.00
---------------------------------------------------------------------------
--------------------------------------ERCIYNQEESVRFDSDVGEYRAVTELGRPDAEYWNSQ
KLLEQRRAAVDTYC---RHNYGVGESFTVQRRVEPK--VTVYPSN----LLVCSVSGFYPGSIEVRWFRNGQEEK
AGVVSTGLIQNGDWTFQTLVMLETVSGEV--YTCQVEHPSVTSPLTVEW----*

>P1;3rugA
structure:3rugA:   14: :  273: :::-1.00:-1.00
----------------RSWSRTDSVVWLGDLQTHRWSNDSAT--ISFTKPWSQGKSNQQWEKLQHMFQVYRVSFT
RDIQELVKMMSPKEDYPIEIQLSAGCEMYP-GNASESFLHVAFQGKYVVRFWG--TSWQTVDLPIKVLNADQGTS
ATVQML---LNDTCPLFVRGLLEAGKSDLEKQEKPVAWLSSVP-SGHR-QLVCHVSGFYPKPVWVMWMR-GDQEQ
QGTHRGDFLPNADETWYLQATLDVEAGEEAGLACRVKHSSLGQDIILYWGSLH*

>P1;6bmhA
structure:6bmhA:   28: :  273: :::-1.00:-1.00
-----------------------------DLQTHRWSNDSAI--ISFTKPWSQGKSNQQWEKLQHMFQVYRVSFT
RDIQELVKMMSPKEDYPIEIQLSTGCEMYP-GNASESFFHVAFQGK--YAVRFRGTSWLGAPSWLDLPIKVLNAD
QTSATVQTLLNDTWPQFARGLLEAGKSDLEKQEKPVAWLSSVPSSAHHLQLVCHVSGFYPKPVWVMWMR-GDQEQ
QGTHRGDFLPNADETWYLQATLDVEAGEEAGLACRVKHSSLGQDIILYW----*

>P1;6u3mC
structure:6u3mC:  105: :  180: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
--------------------------------------------------LICLVDNIFPPVVNITWLSNGHSVT
EGVSETSFLSKSDHSFFKISYLTLLPSAEESYDCKVEHWGLDKPLLKHWEP--*

>P1;6u3mD
structure:6u3mD:   27: :  179: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------RSIYNREEIVRFDSDVGEFRAVTLLGLPAAEYWNSQ
KILERKRAAVDRVC---RHNYQLELRTTLQRRVEPTV-----TISPSHNLLVCSVTDFYPAQIKVRWFRNDQEET
AGVVSTPLIRNGDWTFQILVMLEMTPQRGDVYTCHVEHPSLQSPITVEW----*

>P1;5hhmA
structure:5hhmA:    1: :  212: :::-1.00:-1.00
GSHSMRYFFTSVSRPGRGEPRFIAVGYVDDTQFVRFDSDAASQRMEPRAPWIEQEGPEYWDGETRKVKAHSQTHR
VDLGTLRGYYNQSEAGSHTVQRMYGCDVGSDWRFLRGYHQYAYDGKDYIALKEDLRSWTAADMAAQTTKHKWEAA
HVAEQLRAYLEGTCVEWLRRYLENGKETLQRTDAPKT-----------------ALSFYPAEIT-----------
-----VETRPAGDGTFQKWA---------------------------------*

>P1;4p5kB
structure:4p5kB:   43: :  196: :::-1.00:-1.00
---------------------------------------------------------------------------
------------------------------------------YNREEFVRFDSDVGEFRAVTELGRPDEEYWNSQ
KILEEERAVPDRMC---RHNYELGGPMTLQRRVQPRVNVS--PSKKGHNLLVCHVTDFYPGSIQVRWFLNGQEET
AGVVSTNLIRNGDWTFQILVMLEMTPQQGDVYTCQVEHTSLDSPVTVEWK---*

>P1;4p57B
structure:4p57B:   44: :  195: :::-1.00:-1.00
---------------------------------------------------------------------------
------------------------------------------YNREEFVRFDSDVGEFRAVTELGRPDEEYWNSQ
KILEEKRAVPDRMC---RHNYELGGPMTLQRRVQPRVNVS---PSKHN-LLVCHVTDFYPGSIQVRWFLNGQEET
AGVVSTNLIRNGDWTFQILVMLEMTPQQGDVYTCQVEHTSLDSPVTVEWK---*

>P1;4p5mA
structure:4p5mA:   70: :  179: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-----------------LNTLIQRSNHTQATNDPPEVTVPKEPVEGQPNTLICHIDKFFPPVLNVTWLCNGELVT
EGVAESLFLPRTDYSFHKFHYLTFVPSAEDFYDCRVEHWGLDQPLLKHWE---*

>P1;4p5mB
structure:4p5mB:   13: :  197: :::-1.00:-1.00
---------------------------------------------------------------------------
----------------------------GPENYLFQGRERYIYNREEFVRFDSDVGEFRAVTELGRPDEEYWNSQ
KILEEERAVPDRMC---RHNYELGGPMTLQRRVQPRVNVSPSKKGQHHNLLVCHVTDFYPGSIQVRWFLNGQEET
AGVVSTNLIRNGDWTFQILVMLEMTPQQGDVYTCQVEHTSLDSPVTVEWK---*

>P1;5wkiA
structure:5wkiA:   91: :  267: :::-1.00:-1.00
---------------------------------------------------------------------------
-------------------IQGIAGCELSAIVSFLRG----ALGGLDFLSVKNAVPSPEGGSRAQKFCALIIQYQ
GIMETVRILLYETCPRYLLGVLNAGKADLQRQVKPEAWLSSGP--SGRLQLVCHVSGFYPKPVWVMWMR-GEQEQ
QGTQLGDILPNANWTWYLRATLDVADGEAAGLSCRVKHSSLEQDIILYW----*

>P1;6c09A
structure:6c09A:   90: :  268: :::-1.00:-1.00
---------------------------------------------------------------------------
-------------------VQVKAGCEL-HSGKSPEGFFQVAFNGLDLLSFQN--TTWSLAQSVCHLLNHQYEG-
-VTETVYNLIRSTCPRFLLGLLDAGKMYVHRQVRPEAWLSSRP-SLGQLLLVCHASGFYPKPVWVTWMRNEQEQL
-GTKHGDILPNADGTW--YLQVILEVASEAGLSCRVRHSSLGQDIILYW----*

>P1;6v2oA
structure:6v2oA:    1: :  276: :::-1.00:-1.00
GSHSMRYFYTAMSRPGRGEPRFIAVGYVDDTQFVRFDSDAASPRMAPRAPWIEQEGPEYWDGETRNMKASAQTYR
ENLRIALRYYNQSEAGSHIIQVMYGCDVGPDGRLLRGHDQSAYDGKDYIALNEDLSSWTAADTAAQITQRKWEAA
RVAEQLRAYLEGLCVEWLRRYLENGKETLQRADPPKTHVTHHPISDHEATLRCWALGFYPAEITLTWQRDGEDQT
QDTELVETRPAGDRTFQKWAAVVVPSGEEQRYTCHVQHEGLPKPLTLRWEP--*

>P1;6mngD
structure:6mngD:   15: :  191: :::-1.00:-1.00
---------------------------------------------------------------------------
-----------------HFVYQFMGCYFTNGTQRIRYVTRYIYNREEYVRYDSDVGEHRAVTELGRPDAEYWNSP
EILERTRAELDTVC-----RHNYEGPETLRRLEQPNV-----VISLSRNTLVCSVTDFYPAKIKVRWFRNGQEET
VGVSSTQLIRNGDWTFQVLVMLEMTPRRGEVYTCHVEHPSLKSPITVEW----*

>P1;1zt1A
structure:1zt1A:    2: :  273: :::-1.00:-1.00
GPHSLRYFHTAVSRPGLGKPRFISVGYVDDTQFVRFDSDAENPRYEPRVRWMEQVEPEYWERNTQIAKGNEQIFR
VNLRTALRYYNQSAGGSHTFQRMYGCEVGSDWRLLRGYEQYAYDGCDYIALNEDLKTWTAADMAALITKHKWEQA
GDAERDRAYLEGTCVEWLRRYLQLG----NRTDSPKAHVTRHSRPEDKVTLRCWALGFYPADITLTWQLNGEELT
QDMELVETRPAGDGTFQKWASVVVPLGKEQYYTCHVYHQGLPEPLTLRWEP--*

>P1;1jn6A
structure:1jn6A:   89: :  198: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
------------ICALWFSNIFGSGTKVTVKSSP---SVTLFPPSSEEATLVCTITDFYPGVVTVDWKVDGTPVT
QGMETTQPSKQSNNKYMASSYLTLTARAWERYSCQVTHEG-------------*

>P1;2pxyD
structure:2pxyD:   31: :  186: :::-1.00:-1.00
---------------------------------------------------------------------------
------------------------------------------YNREEYLRFDSDVGEYRAV-TELGRPDAEYYNK
QYLERTRAELDTVC-----RY--NYEETLRRLEQPNVSLSRTEALNHHNTLVCSVTDFYPAKIKVRWFRNGQEET
VGVSSTQLIRNGDWTFQVLVMLEMTPRRGEVYTCHVEHPSLKSPITVEW----*

>P1;4ms8A
structure:4ms8A:    2: :  162: :::-1.00:-1.00
GPHSMRYYETATS------PRYTSVGYVDDKEFVRFDSDAENPRYEPQVPWMEQEGPEYWERITQIAKGQEQWFR
VNLRTLLGY--------HTLQWMYGCDVGSDGRLLRGYEQFAYDGCDYIALNEDLRTWTAADMAAQITRRKWEQA
GAAEYYRAYLEGECVEWLHRYLKNG--------------------------------------------------
-----------------------------------------------------*

>P1;5wnbM
structure:5wnbM:  118: :  195: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
------------------------------------------PPSDEQASVVCLLNNFYPREAKVQWKLQGNSQE
SVTE----QDSKDSTYSLSSTLTLSKADYKVYACEVTHQGLSSPVT-------*

>P1;2wngA
structure:2wngA:  219: :  298: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------PPTLEVTQQPVAENQVNVTCQVRKFYPQRLQLTWLENGNSRT
ETASTVTENKDGTYNWMSWLLVDV------KLTCQVEHDGQP-----------*

>P1;3qulA
structure:3qulA:    1: :  264: :::-1.00:-1.00
GPHSMRYFETAVSRPGLEEPRYISVGYVDNKEFVRFDSDAENPRYEPRAPWMEQEGPEYWERETQKAKGQEQWFR
VSLRNLLGYYNQSAGGSHTLQQMSGCDLGSDWRLLRGYLQFAYEGRDYIALNEDLKTWTAADMAAQITRRKWEQS
GAAEHYKAYLEGECVEWLHRYLKNGN---LRTDSPKAHVTHHPRS--EVTLRCWALGFYPADITLTWQ--GEEM-
---ELVETRPAGDGTFQKWASVVVPLGKEQNYTCRVYHEGLPEPLTLRWE---*

>P1;4mq7A
structure:4mq7A:  107: :  267: :::-1.00:-1.00
---------------------------------------------------------------------------
-----------------------------------------AFQGKDILSFQG--TSWEPTQEAQVLNQDKW---
-TRETVQWLLNGTCPQFVSGLLESGKSELKKQEKPVAWLSSVPSSAHHRQLVCHVSGFYPKPVWVMWMR-GDQEQ
QGTHRGDFLPNADETWYLQATLDVEAGEEAGLACRVKHSSLGQDIILYW----*

>P1;3he7A
structure:3he7A:   14: :  266: :::-1.00:-1.00
----------------RSWSRTDSVVWLGDLQTHRWSNDSAT--ISFTKPWSQGKSNQQWEKLQHMFQVYRVSFT
RDIQELVKMPIE-------IQLSAGCEMYASESFL----HVAFQGKYVVRFWG--TSWQTVDLPIKVLNADQGTS
ATVQML---LNDTCPLFVRGLLEAGKSDLEKQEKPVAWLSSVPSSAHHRQLVCHVSGFYPKPVWVMWMR-GDQEQ
QGTHRGDFLPNADETWYLQATLDVEAGEEAGLACRVKHSSLGQDIILYWGLHH*

>P1;1p1zA
structure:1p1zA:    1: :  255: :::-1.00:-1.00
--HSLRYFVTAVSRPGLGEPRYMEVGYVDDTEFV----------YEPRARWMEQEGPEYWERETQKAKGNEQSFR
VDLRTLLGYYNQSKGGSHTIQVISGCE-------VRGYQQYAYDGCDYIALNEDLKTWTAADMAALITKHKWEQA
GEAERLRAYLEGTCVEWLRRYLKNGNATLLRTDSPKAHVTHHSRPEDKVTLRCWALGFYPADITLTWQLNGEELI
QDMELVETRPAGDGTFQKWASVVVPLGKEQYYTCHVYHQGLPEPLTLRW----*

>P1;3spvA
structure:3spvA:    1: :  276: :::-1.00:-1.00
GSHSMRYFDTAMSRPGRGEPRFISVGYVDDTQFVRFDSDAASPREEPRAPWIEQEGPEYWDRNTQIFKTNTQTDR
ESLRNLRGYYNQSEAGSHTLQSMYGCDVGPDGRLLRGHNQYAYDGKDYIALNEDLRSWTAADTAAQITQRKWEAA
RVAEQDRAYLEGTCVEWLRRYLENGKDTLERADPPKTHVTHHPISDHEATLRCWALGFYPAEITLTWQRDGEDQT
QDTELVETRPAGDRTFQKWAAVVVPSGEEQRYTCHVQHEGLPKPLTLRWEP--*

>P1;4y2dA
structure:4y2dA:   16: :  244: :::-1.00:-1.00
----------------RSWSRTDSVVWLGDLQTHRWSNDSAT--ISFTKPWSQGKSNQQWEKLQHMFQVYRVSFT
RDIQELVKMMSPKEDYPIEIQLSAGCEMYP-GNASESFLHVAFQGKYVVRFWG--TSWQTVDLPIKVLNADQGTS
ATVQML---LNDTCPLFVRGLLEAGKSDLEKQEKPVAWLSSVP------QLVCHVSGFYPKPVWVTHRGD-----
-------FLPNADET---WYLQATLDGEEAGLACRVKHSSL------------*

>P1;6qn8L
structure:6qn8L:  101: :  201: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
------------------------GGTTLTVLGQPKSSVTLFPPSTEEATLVCLISDFYPGSVTVVWKADGSTIT
RN---VETTRASKQSNSKYAALSLTSSDKGSYSCEVTHEG-------------*

>P1;6qn9L
structure:6qn9L:  119: :  199: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------PPST----EELNGNKATLVCLISDFYPGSVTVVWKADGSTIT
RN---VETTRASKQSNSKYAALSLTSSDKGSYSCEVTHEG-------------*

>P1;5h94A
structure:5h94A:    1: :  275: :::-1.00:-1.00
GPHSLSYFYTAVSRPDRGDSRFIAVGYVDDTQFVRFDSDAPNPREEPRAPWIQQEGQEYWDRETQISKDNAQTYR
VNLNNLRGYYNQSEAGSHTFQNMYGCYLGPDGLLLHGYHQYAYDGADYIALNEDLRSWTAADTAAQITKRKWEAS
GWAEQERSYLQGLCVESLREYLEMGKDTLQRAEPPKTHVTRHPSSDLGVTLRCWALGFYPKEISLTWQREGQDQS
QDMELVETRPSGDGTFQKWAALVVPPGEEQSYTCHVQHEGLQEPLTLRWD---*

>P1;5vclA
structure:5vclA:    2: :  276: :::-1.00:-1.00
-SHSLRYFHTAMSRPGLGEPRFIVVGYVDDTQFVSFDSDSENPKMEPRARWMEQEGPEYWERETWKARDMGRNFR
VNLRTLLGYYNQSKDESHTLQWMYGCDVGPDGRLLRGYCQEAYDGQDYISLNEDLRSWTATDFASQISKHKSEMV
DEAHQQRAYLQGPCVEWLHTYLRLGNKTLKRSDPPKAHVTHHPRSEDYVTLRCWALGFYPADITLTWQLNGEELT
QDMEFVETRPAGDGNFQKWASVVVPLGKEQNYTCHVEHEGLPEPLTLRWEP--*

>P1;6mp0A
structure:6mp0A:  112: :  387: :::-1.00:-1.00
GPHSMRYFETAVSRPGLEEPRYISVGYVDNKEFVRFDSDAENPRYEPRAPWMEQEGPEYWERETQKAKGQEQWFR
VSLRNLLGAYNQSAGGSHTLQQMSGCDLGSDWRLLRGYLQFAYEGRDYIALNEDLKTWTAADMAAQITRRKWEQS
GAAEHYKAYLEGECVEWLHRYLKNGNATLLRTDSPKAHVTHHPRSKGEVTLRCWALGFYPADITLTWQLNGEELT
QDMELVETRPAGDGTFQKWASVVVPLGKEQNYTCRVYHEGLPEPLTLRWEP--*

>P1;1k8dA
structure:1k8dA:    1: :  274: :::-1.00:-1.00
GQHSLQYFHTAVSRPGLGEPWFISVGYVDDTQFVRFDSDAENPRMEPRARWMEQEGPEYWERETQIAKGHEQSFR
GSLRTAQSYYNQSKGGSHTLQWMYGCDMGSDGRLLRGYLQFAYEGRDYIALNEDLKTWTAVDMAAQITRRKWEQA
GIAEKDQAYLEGTCMQSLRRYLELGKETLLRTDPPKAHVTHHPRSYGAVTLRCWALGFYPADITLTWQLNGEELT
QDMELVETRPAGDGTFQKWASVVVPLGKEQNYTCHVNHEGLPEPLTLRW----*

>P1;1k8iB
structure:1k8iB:   25: :  190: :::-1.00:-1.00
---------------------------------------------------------------------------
------------------------------------------------VSFNKDLLACWDPDVGKIVPCEFGVLS
RLAEIISNILNE--QESLIHRLQNGLQDCATHTQPLTHRTRAPSTREPVMLACYVWGFYPADVTITWMKNGQLVP
SHSNKEKTQPNGDWTYQTVSYLALTPSYGDVYTCVVQHSGTSEPIRGDWTP--*

>P1;7k81A
structure:7k81A:    1: :  276: :::-1.00:-1.00
GSHSMRYFSTSVSRPGRGEPRFIAVGYVDDTQFVRFDSDAASQRMEPRAPWIEQEGPEYWDEETGKVKAHSQTDR
ENLRIALRYYNQSEAGSHTLQMMFGCDVGSDGRFLRGYHQYAYDGKDYIALKEDLRSWTAADMAAQITKRKWEAA
HVAEQQRAYLEGTCVDGLRRYLENGKETLQRTDPPKTHMTHHPISDHEATLRCWALGFYPAEITLTWQRDGEDQT
QDTELVETRPAGDGTFQKWAAVVVPSGEEQRYTCHVQHEGLPKPLTLRWEP--*

>P1;4u1mA
structure:4u1mA:    1: :  276: :::-1.00:-1.00
GSHSMRYFYTSVSRPGRGEPRFISVGYVDDTQFVRFDSDAASPREEPRAPWIEQEGPEYWDRNTQIYKAQAQTDR
ESLRNLRGYYNQSEAGSHTLQSMYGCDVGPDGRLLRGHNQYAYDGKDYIALNEDLRSWTAADTAAQITQRKWEAA
RVAEQDRAYLEGTCVEWLRRYLENGKDTLERADPPKTHVTHHPISDHEATLRCWALGFYPAEITLTWQRDGEDQT
QDTELVETRPAGDRTFQKWAAVVVPSGEEQRYTCHVQHEGLPKPLTLRWEP--*

>P1;1mhcA
structure:1mhcA:    1: :  274: :::-1.00:-1.00
GSHSLRYFHTAVSRPGRGEPQYISVGYVDDVQFQRCDSIEEIPRMEPRAPWMEKERPEYWKELKLKVKNIAQSAR
ANLRTLLRYYNQSEGGSHILQWMVSCEVGPDMRLLGAHYQAAYDGSDYITLNEDLSSWTAVDMVSQITKSRLESA
GTAEYFRAYVEGECLELLHRFLRNGKEILQRADPPKAHVAHHPRPKGDVTLRCWALGFYPADITLTWQKDEEDLT
QDMELVETRPSGDGTFQKWAAVVVPSGEEQRYTCYVHHEGLTEPLALKW----*

>P1;1r3hA
structure:1r3hA:    1: :  248: :::-1.00:-1.00
GSHSLRYFYTAVSRPGLGEPWFIIVGYVDDMQVLRFSSKEETPR---MAPWLEQEEADDWEQQTHIVTIQGQLSE
RNLMTLVHFYNKSMDDSHTLQWLQDCDVEPDRHLCLWYNQLAYDSEDLPTLSENPSSCT----------------
-------QHLEGHCSDVLQKYLEKGKERLLRSDPPKAHVTRHPRPEGDVTLRCWALGFYPADITLTWQKDGEELT
--VEFVETRPAGDGTFQKWAAVVVPLGKVQSYTCHVDHEGLPEPLTLRWEP--*

>P1;2h3nB
structure:2h3nB:    7: :  107: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-----------------------SGTQLTVLSQPKATSVTLFPPSSEEATLVCLMNDFYPGILTVTWKADGTPIT
QGVEM--TTPS-KQSNNKYAASLTPEQWRSRYSCQVMHEG-------------*

>P1;6h3hB
structure:6h3hB:   90: :  202: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-------------CALWYNHWVFGGGTKLTVLGQPKSSVTLFPPSSEEATLVCTITDFYPGVVTVDWKVDGTPVT
QGMETTQPSKQSNNKYMASSYLTLTARAWERYSCQVTHEG-------------*

>P1;4xxcA
structure:4xxcA:    1: :  276: :::-1.00:-1.00
GSHSMRYFHTSVSRPGRGEPRFISVGYVDGTQFVRFDSDAASPRTEPRAPWIEQEGPEYWDRNTQISKTNTQTYR
ESLRNLRGYYNQSEAGSHTLQRMYGCDVGPDGRLLRGHDQSAYDGKDYIALNEDLSSWTAADTAAQITQRKWEAA
RVAEQLRAYLEGTCVEWLRRHLENGKETLQRADPPKTHVTHHPISDHEATLRCWALGFYPAEITLTWQRDGEDQT
QDTELVETRPAGDRTFQKWAAVVVPSGEEQRYTCHVQHEGLPKPLTLRWEP--*

>P1;3eryB
structure:3eryB:    1: :  149: :::-1.00:-1.00
GPHSMRYYETATSRRGLGEPRYTSVGYVDDKEFVRFDSDA---------------------RITQVAKGQEQWFR
VNLRTLLGYYNQSAGGTHTLQRMYGCDVGSDGRLLRGYEQFAYDGCDYIALNEDLRTWTAADMAAQITRRKWEQA
GAAEYYRAYLEGECVEWLHR-------------------------------------------------------
-----------------------------------------------------*

>P1;3mreA
structure:3mreA:    1: :  274: :::-1.00:-1.00
GSHSMRYFFTSVSRPGRGEPRFIAVGYVDDTQFVRFDSDAASQRMEPRAPWIEQEGPEYWDGETRKVKAHSQTHR
VDLGTLRGYYNQSEAGSHTVQRMYGCDVGSDWRFLRGYHQYAYDGKDYIALKEDLRSWTAADMAAQTTKHKWEAA
HVAEQLRAYLEGTCVEWLRRYLENGKETLQRTDAPKTHMTHHAVSDHEATLRCWALSFYPAEITLTWQRDGEDQT
QDTELVETRPAGDGTFQKWVAVVVPSGQEQRYTCHVQHEGLPKPLTLRW----*

>P1;3s6cA
structure:3s6cA:  190: :  365: :::-1.00:-1.00
---------------------------------------------------------------------------
-------------------IQILAGCRMNAPQIFL----NMAYQGSDFLSFSWEPSAGIRAQNICKVLNRYLD--
-IKEILQSLLGHTCPRFLAGLMEAGESELKRKVKPEAWLSCGPPGPGRLQLVCHVSGFYPKPVWVMWMR-GEQEQ
RGTQRGDVLPNADETWYLRATLDVAAGEAAGLSCRVKHSSLGHDLIIHW----*

>P1;3fonA
structure:3fonA:    1: :  274: :::-1.00:-1.00
GSHSLRYFVTAVSRPGHGKPRYMEVGYVDDTEFVRFDSDAENPRYEPRTPWMEQVEPEYWEGQTQIAKGNEQSSR
VDLRTALRYYNQSAGGSHTIQRMRGCEVGSDGRLLRGYQQVAYDGRDYIALNEDLKTWTAADMAALITKHKWEQA
GAAERDRAYLEGACVEWLRRYLELGNATLLRTDSPKAHVTHHSRPKDKVTLRCWALGFYPADITLTWQLNGEELT
QDMELVETRPAGDGTFQKWASVVVPLGKEQNYTCHVYHEGLPEPLTLRW----*

>P1;3cupB
structure:3cupB:   44: :  176: :::-1.00:-1.00
---------------------------------------------------------------------------
------------------------------------------YNREEYLRFDSDVGEYRAVTELGRHSAEYYN-K
QYLERTRAELDTAC---RHNYEETEVPTLRRLEQPNVAIS-------LSTLVCSVTDFYPAKIKVRWETVGVSST
Q---LIRN---GDWTFQ----VLV-----MLYTCHVEHPSLKSPITVEW----*

>P1;2q6wB
structure:2q6wB:   26: :  186: :::-1.00:-1.00
---------------------------------------------------------------------------
--------------------------------------DRYFHNQEEFLRFDSDVGEYRAVTELGRPVAESWNSQ
KLLEQKRGRVDNYC---RHNYGVGESFTVQRRVHPQ--VTVYPAKQHHNLLVCSVSGFYPGSIEVRWFRNGQEEK
AGVVSTGLIQNGDWTFQTLVMLETVPRSGEVYTCQVEHPSVTSALTVEW----*

>P1;6k7tA
structure:6k7tA:    1: :  253: :::-1.00:-1.00
GFHSLRYFYTAWSRPGSGEPRFVAVGYVDDTQFVRFDSDNASPRAEPRAPWVEQQDPQYWDRNTRNARDAAQTYR
VGLDNVRGYYNQSEAGSHTIQRMYGCDVGPHGRLLRGYDQLAYDGADYIALNEDLRSWTAADLAAQNTRRKWEEA
GYAERDRAYLEGECVEWLLKHLENGRETLLRADPPKTHITHHPI----VTLRCWALGFYPEEITLTWM-------
---ELVETRPDGNGAFQKWAA----------YTCHVQHEGLPQPLTLRW----*

>P1;2xfxA
structure:2xfxA:    1: :  276: :::-1.00:-1.00
GSHSLRYFHTAVSRPGLREPLFITVGYVDDTQFVRFDSDARDPRTEPRQPWMEKEGPEYWDRETQISKENALWYR
EALNNLRGYYNQSEAGSHTLQEMYGCDVGSDGRLRRGYEQYGYDGRDYLALNEDLRSWTAADTAAQISKRKMEAA
GAAERFRNYLEGTCVEWLRRYLENGKDTLLRADPPKAHVTRHPSSEHEVTLRCWALGFYPEEISLTWQRNGEDQT
QDMELVETRPSGDGNFQKWAALVVPSGEEQRYTCRVQHEGLQEPLTLRWEP--*

>P1;2xfxB
structure:2xfxB:    5: :   96: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------PPKIQVSRHPPEDGKPNLNCYVYGFHPPQIEIDLLKNGEKKS
EQSDLSFSK---DWSFYLLSHAEFTPNSKDQYSCRVKHVTLEQPRIVKWD---*

>P1;6vmxF
structure:6vmxF:    1: :  267: :::-1.00:-1.00
GSHSMRYFYTSVSRPGRGEPRFISVGYVDDTQFVRFDSDAASPREEPRAPWIEQEGPEYWDRNTQIYKAQAQTDR
ESLRNLRGYYNQSEAGSHTLQSMYGCDVGPDGRLLRGHDQYAYDGKDYIALNEDLRSWTAADTAAQITQRKWEAA
REAEQRRAYLEGECVEWLRRYLENGKDKLERADPPKTHVTHHPISDHEATLRCWALGFYPAEITLTWQRDGEDQT
QDTELVETRPAGDRTFQKWAAVVVP--EEQRYTCHVQHEGLPKP---------*

>P1;1t7vA
structure:1t7vA:    2: :  272: :::-1.00:-1.00
GRYSLTYIYTGLSKHVEDVPAFQALGSLNDLQFFRYNS--KDRKSQPMGLWRQVEGMEDWKQDSQLQKAREDIFM
ETLKDIVEYYKDS-TGSHVLQGRFGCEI-ENNRSSGAFWKYYYDGKDYIEFNKEIPAWVPFDPAAQITKQKWEAE
PVVQRAKAYLEEECPATLRKYLKYSKNILDRQDPPSVVVTSHQAPGEKKKLKCLAYDFYPGKIDVHWTRAGE--V
QEPELGDVLHNGNGTYQSWVVVAVPPQDTAPYSCHVQHSSLAQPLVVPWE---*

>P1;5v4mF
structure:5v4mF:   38: :  198: :::-1.00:-1.00
---------------------------------------------------------------------------
--------------------------------------DRYFYNQEESVRFDSDVGEFRAVTELGRPDAEYWNSQ
KILEQARAAVDTYC---RHNYGVVESFTVQRRVQPK--VTVYPSKQHHNLLVCSVSGFYPGSIEVRWFLNGQEEK
ASTGLIQN---GDWTFQTLVMLETVPRSGEVYTCQVEHPSVTSPLTVEW----*

>P1;4gg6B
structure:4gg6B:   30: :  163: :::-1.00:-1.00
---------------------------------------------------------------------------
------------------------------------------YNREEYARFDSDVGVYRAVTPLGPPAAEYWNSQ
KVLERTRAELDTVC---RHNYQLELRTTLQRRVEPT--VTISP-----SLLVCSVTDFYPAQIKVRWETTG---V
VSTPLIRN---GDWTFQ----ILV-----MLETCHVEHPSLQNPIIVEW----*

>P1;1mujB
structure:1mujB:    4: :  180: :::-1.00:-1.00
---------------------------------------------------------------------------
-----------------HFVYQFMGCYFTNGTQRIRYVTRYIYNREEYVRYDSDVGEHRAVTELGRPDAEYWNSP
EILERTRAELDTVC-----RHNYEGPETLRRLEQPNV-----VISLSHNTLVCSVTDFYPAKIKVRWFRNGQEET
VGVSSTQLIRNGDWTFQVLVMLEMTPRRGEVYTCHVEHPSLKSPITVEW----*

>P1;6xqpA
structure:6xqpA:    2: :  237: :::-1.00:-1.00
-THSLRYFRLGVSDPIHGVPEFISVGYVDSHPITTYDS--VTRQKEPRAPWMENLAPDHWERYTQLLRGWQQMFK
VELKRLQRHYNHS--GSHTYQRMIGCELLEDGS-TTGFLQYAYDGQDFLIFNKDTLSWLAVDNVAHTIKQAWEAN
Q-HELLKNWLEEECIAWLKRFLEYGKDTLQRTEPPLVRV------NRKETLFCKAHGFYPPEIYMTWEIDYGD--
-------ILPSGDGTYQAWASI-----------CHVEHSGV------------*

>P1;6kvmB
structure:6kvmB:   31: :  179: :::-1.00:-1.00
---------------------------------------------------------------------------
------------------------------------------YNRQQYAHFDSDVGKFVADSPLGEPQAEYWNSA
ELLENRMNEVDRFC-----RHNYGGVETVQRSVEPKVRVS--------ARLACYVTGFYPPEIEVKWFLNGREET
ERVVSTDVMQNGDWTYQVLVVLETVPRRGDSYVCRVEHASLRQPISQAWEP--*

>P1;1es0B
structure:1es0B:   42: :  189: :::-1.00:-1.00
---------------------------------------------------------------------------
------------------------------------------YNREEYLRFDSDVGEYRAVTELGRHSAEYYN-K
QYLERTRAELDTAC---RHNYEETEVPTLRRLEQPNVAIS---LSN---TLVCSVTDFYPAKIKVRWFRNGQEET
VGVSSTQLIRNGDWTFQVLVMLEMTPHQGEVYTCHVEHPSLKSPITVEW----*

>P1;6v1aB
structure:6v1aB:   27: :  173: :::-1.00:-1.00
---------------------------------------------------------------------------
--------------------------------------DRYFYHQEEYVRFDSDVGEYRAVTELGRPDAEYWNSQ
KLLEQKRAAVDTYC---RHNYGVGESFTVQRRVYPE--VTVYP-----AKTVCSVNGFYPGSIEVRWFRNGQEEK
TGVVSTGLIQNGDWTFQTLVML-----ETEVYTCQVEHPSLTSPLTVEW----*

>P1;3pwuA
structure:3pwuA:    1: :  274: :::-1.00:-1.00
-SHSLRYFYTAVSRPGLGEPRFIAVGYVDDTQFTRFDSDAPNPRDEPRVPWMEQEGPEYWDRNTRIYKDTAQIFR
ANLNTALGYYNQSEAGSHTFQEMYGCYVGPDGRLLLGFMQFAYDGRDYIALNEDLRSWTAADTAAQITKRKWEAA
GEAERQRNYLEGRCVEGLRRYLENGKDTLLRADPPKAHVTHHPISDREVTLRCWALGFYPEEISLTWQHEGEDQT
QDMELVETRPSGDGTFQKWAALVVPSGEEQRYTCRVQHEGLQEPLTLRWE---*

>P1;1fneA
structure:1fneA:   87: :  179: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------PEVTVLSRSPVNLGEPNLICFIDKFSPPVVNVTWLRNGRPVT
EGVSETVFLPRDDHLFRKFHYLTFLPSTDDFYDCEVDHWGLEEPLRKHWE---*

>P1;1fneB
structure:1fneB:   57: :  213: :::-1.00:-1.00
---------------------------------------------------------------------------
------------------------------------------YNLEENLRFDSDVGEFRAVTELGRPDAENWNSP
EFLEQKRAEVDTVC----RHNYEIFDNFLRRVEPTVTYPTKTQPLEHHNLLVCSVSDFYPGNIEVRWFRNGKE--
EKTGIVSTGLVGDWTFQTLVMLETVPQSGEVYTCQVEHPSLTDPVTVEW----*

>P1;4x5wB
structure:4x5wB:   27: :  178: :::-1.00:-1.00
---------------------------------------------------------------------------
--------------------------------------ERCIYNQEESVRFDSDVGEYRAVTELGRPDAEYWNSQ
KLLEQRRAAVDTYC---RHNYGVGESFTVQRRVEPK--VTVYP-----SLLVCSVSGFYPGSIEVRWFRNGQEEK
AGVVSTGLIQNGDWTFQTLVMLETVPRSGEVYTCQVEHPSVTSPLTVEW----*

>P1;3bevA
structure:3bevA:    3: :  270: :::-1.00:-1.00
--HTLRYIRTAMTDPGPGLPWFVDVGYVDGELFMHYNSTAR--RAVPRTEWIANTDQQYWDRETQIVQGSEQINR
ENLDILRRRYNQT-GGSHTVQWMSGCDILEDG-TIRGYHQAAYDGRDFVAFDKGTMTLTAAVPEAVPTKRKWEEG
GYAEGLKQYLEETCVEWLRRYVEYGKAELGRRERPEVRVWGKE-ADGILTLSCRAHGFYPRPIVVSWLKDGAVRG
QDAQSGGIVPNGDGTYHTWVTIDAQPGDGDKYQCRVEHASLPQPGLYSW----*

>P1;6qbcL
structure:6qbcL:   87: :  201: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-------------CAAWLNAWVFGGGTKLTVLGQPKSSVTLFPPSSEEATLVCTITDFYPGVVTVDWKVDGTPVT
QGMETTQPSKQSNNKYMASSYLTLTARAWERYSCQVTHEG-------------*

>P1;6birB
structure:6birB:   27: :  184: :::-1.00:-1.00
---------------------------------------------------------------------------
--------------------------------------DRYFYHQEEYVRFDSDVGEYRAVTELGRPSAEYWNSQ
KLLEQRRAAVDTYC---RHNYGVGESFTVQRRVYPEVTVYPAKTQPHN-LLVCSVNGFYPGSIEVRWFRNGQEEK
TGVVSTGLIQNGDWTFQTLVMLETVPRSGEVYTCQVEHPSLTSPLTVEW----*

>P1;3jvgA
structure:3jvgA:   23: :  263: :::-1.00:-1.00
------------------------LGLLGDVKMGSLDSRTGNIRY--YRPWLRPSLPKDWD----VIESSIKSYV
RDFSRLVQMY--TVPYPFVFQSSIGCELQSNG-TIRTFFDIAYEGQNFLRFNLDAGTWDQMQLSAKAEHLMANAS
TLNEVIQVLLNDTCVDILRLFIQAGKADLERQVPPMAVVFARTA---QLLLVCRVTSFYPRPIAVTWLRDGREVP
PSPALSTVLPNADLTYQLRSTLLVPHG----YACRVQHCSLGRSLLVPW----*

>P1;5j1aA
structure:5j1aA:   23: :  264: :::-1.00:-1.00
-------------------------GWLSDLQTHTWDSNSST--IVFLWPWSRGNSNEEWKELETLFRIRTIRSF
EGIR---RY-------AHELQFEYPFEIQVTGGCEGSFLQLAYQGSDFVSFQN--NSWLPYPVAGNMAKHFCKVL
NQNQHTHNLLSDTCPRFILGLLDAGKAHLQRQVKPEAWLSHGPPGPGHLQLVCHVSGFYPKPVWVMWMR-GEQEQ
QGTQRGDILPSADGTWYLRATLEVAAGEAADLSCRVKHSSLEQDIVLYWE---*

>P1;3bwaA
structure:3bwaA:    1: :  276: :::-1.00:-1.00
GSHSMRYFYTAMSRPGRGEPRFIAVGYVDDTQFVRFDSDAASPRTEPRAPWIEQEGPEYWDRNTQIFKTNTQTYR
ESLRNLRGYYNQSEAGSHIIQRMYGCDLGPDGRLLRGHDQSAYDGKDYIALNEDLSSWTAADTAAQITQRKWEAA
RVAEQRRAYLEGLCVEWLRRYLENGKETLQRADPPKTHVTHHPVSDHEATLRCWALGFYPAEITLTWQRDGEDQT
QDTELVETRPAGDRTFQKWAAVVVPSGEEQRYTCHVQHEGLPKPLTLRWEP--*

>P1;6k60A
structure:6k60A:    1: :  257: :::-1.00:-1.00
-SHSMRYFSAAVSRPGRGEPRFIAMGYVDDTQFVRFDSDSASPRMEPRAPWVEQEGPEYWEEETRNTKAHAQTDR
MNLQTLRGYYNQSEASSHTLQWMIGCDL-----LLRGYEQYAYDGKDYLALNEDLRSWTAADTAAQISKRKCEAA
NVAEQRRAYLEGTCVEWLHRYLENGKEMLQRADPPKTHVTHHPV---EATLRCWALGFYPAEIILTW--------
QDVELVETRPAGDGTFQKWAAVVVPSGEEQRYTCHVQHEGLPEPLMLRW----*

>P1;2qrtA
structure:2qrtA:  123: :  398: :::-1.00:-1.00
GPHSLRYFVTAVSRPGLGEPRYMEVGYVDDTEFVRFDSDAENPRYEPRARWMEQEGPEYWERETQKAKGNEQSFR
VDLRTLLGCYNQSKGGSHTIQVISGCEVGSDGRLLRGYQQYAYDGCDYIALNEDLKTWTAADMAALITKHKWEQA
GEAERLRAYLEGTCVEWLRRYLKNGNATLLRTDSPKAHVTHHSRPEDKVTLRCWALGFYPADITLTWQLNGEELI
QDMELVETRPAGDGTFQKWASVVVPLGKEQYYTCHVYHQGLPEPLTLRWEP--*

>P1;4l8sC
structure:4l8sC:  105: :  362: :::-1.00:-1.00
-THSLRYFRLGISEPGYGIPEFISAGYVDSHPITMYNSVS---QLEPRALWMEENAPDHWERYTQLLRGWQQAFK
VELKQLQHHYNHS--GFHTYQRMIGCELLEDGS-ITGFLQYAYDGQDFLIFNKDTLSWMAMDNVADIIRRVWEAN
RHELQYKNWLEEECIAWLKRFLEYGKDALQRTEPPKVRVNH---KETITTLYCRAYGFYPPEISINWMKNGEEIF
QDTDYGGILPSGDGTYQTWVSVELDPQNGDIYSCHVEHGGV------------*

>P1;6a97A
structure:6a97A:    1: :  258: :::-1.00:-1.00
-THTLRYNVRAHSLEGSEKTQLLVLIYVDEELFLKYNGD--SRETEPLGCWIKHGGNETCARET----NNLLKVE
EKLRMMAEVINQQEEGLHTLQATLGCELLSNGS-TRGFWHLGYDGQNFLTFDQKTLTWTVDGPSTQQNKMFWKTA
PRADLVKTFLDDICPAHLQRYLASLR---NGTGPPMVTVTNYPVG--RVTLTCRAFNLYTREATLVWLQDGKPVQ
QKTFRSETLPSGDGTYQARVSIRVLPGQEPQFSCNLRH---------------*

>P1;6a97C
structure:6a97C:    1: :  216: :::-1.00:-1.00
-THTLRYNVRAHSLEGSEKTQLLVLIYVDEELFLKYNGD--SRETEPLGCWI-------CARET----NNLLKVE
EKLR------GMMAEVINTLQATLGCE--------RGFWHLGYD-----FLTFDTLTWTVQN------KMFWKTA
PRADLVKTFLDDICPAHLQRYL----------GPPMVTVTNYPVG--RVTLTCRAFNLYTREATLVWLQDGKPVQ
QKTFRSETLPSGDGTYQARVSIRVLPGQEPQFSCNLRH---------------*

>P1;4g43A
structure:4g43A:    3: :  271: :::-1.00:-1.00
--HTLRYIRTAMTDPGPGQPWFVTVGYVDGELFVHYNSTAR--RYVPRTEWIANTDQQYWDGQTQIGQLNEQINR
ENLGIRQRRYNQT-GGSHTVQWMFGCDILEDG-TIRGYRQSAYDGRDFIALDKDMKTFTAAVPEAVPTKRKWEEE
SEPERWKNYLEETCVEWLRRYVEYGKAELGRRERPEVRVWGKE-ADGILTLSCRAHGFYPRPIVVSWLKDGAVRG
QDAHSGGIVPNGDGTYHTWVTIEAQPGDGDKYQCRVEHASLPQPGLYSWK---*

>P1;1sm3L
structure:1sm3L:   89: :  201: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-------------CALWYSNHWVFGKLTVLGSEKSSPSVTLFPPSSEEATLVCTITDFYPGVVTVDWKVDGTPVT
QGMETTQPSKQSNNKYMASSYLTLTARAWERYSCQVTHEG-------------*

>P1;6cpoB
structure:6cpoB:   27: :  187: :::-1.00:-1.00
---------------------------------------------------------------------------
--------------------------------------DRYFYNQEESVRFDSDVGEFRAVTELGRPDAEYWNSQ
KILEQARAAVDTYC---RHNYGVGESFTVQRRVQPK--VTVYPSKQHHNLLVCSVSGFYPGSIEVRWFLNGQEEK
ASTGLIQN---GDWTFQTLVMLETVPRSGEVYTCQVEHPSVTSPLTVEW----*

>P1;7cpoA
structure:7cpoA:    2: :  270: :::-1.00:-1.00
-SHSMRYFVTSVSEPGQ---PFSYVGYVDDQEFVSY--NASTRRYLPKVPWIEKNDPDYWERNTLYAQGHERSFR
DHLATLAEYYNQS-GGLHTFQWMYGCELRNDWS-KGGYYQYAYDGRDYISLDKDTLTWMAADVPAQNTKRKWDAF
RDNEYKKTYLEETCIEWLQRYLNYGKETLLRTEVPEVKVTRKEDYGME-TLICRVGGFYPKDIDIDWTRDGEVWL
QDVFHGLVSPNSDGTYYTWRSVKVDPKERERYKCHVEHDGLPNPVDVAW----*

>P1;7cpoB
structure:7cpoB:    2: :   90: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-----------------------------QKAPSVQVYFRHPAEKGKENTFHCYAESFHPPKINITLLKNGMENV
QQSDLSFKK---DWTFERLVAKVIPDGAE--FACKVEHITLPQPM--------*

>P1;6v7yA
structure:6v7yA:   49: :  270: :::-1.00:-1.00
-------------------------------------------------PWSQGTSDQQWETLQHIFRVYRSSFT
RDVKEFAKMLRLSYPLE--LQVSAGCEVHP-GNASNNFFHVAFQGKDILSFQG--TSWEPTQEAQVLNQDKW---
-TRETVQWLLNGTCPQFVSGLLESGKSELKKQVKPKAWLSRGP-SPGRLLLVCHVSGFYPKPVWVKWMR--EQEQ
QGTQPGDILPNADETWYLRATLDVVAG-AAGLSCRVKHSSLEQDIVLYW----*

>P1;5ylxA
structure:5ylxA:    1: :  275: :::-1.00:-1.00
GPHSLSYFSTAVSRPDRGDSRFIAVGYVDDTQFVRFDSDAPNPRMEPRVPWIQQEGQEYWAEETRKVKDNAQTYR
VNLKALRGYYNQSVAGSHTLQSMFGCYLGPDGLLLHGYRQDAYDGADYIALNEDLRSWTAADMAAQITKRKWEAA
DAAEQMRSYLQGLCVESLRKYLEMGKDTLQRAEPPKTHVTRHPSSDLGATLRCWALGFYPKEISLTWQREGQDQS
QDMELVETRPSGDGTFQKWAALVVPPGEEQSYTCHVQHEGLQEPLTLRWD---*

>P1;3kyoA
structure:3kyoA:    1: :  273: :::-1.00:-1.00
-SHSMRYFSAAVSRPGRGEPRFIAMGYVDDTQFVRFDSDSASPRMEPRAPWVEQEGPEYWEEETRNTKAHAQTDR
MNLQTLRGYYNQSEASSHTLQWMIGCDLGSDGRLIRGYERYAYDGKDYLALNEDLRSWTAADTAAQISKRKCEAA
NVAEQRRAYLEGTCVEWLHRYLENGKEMLQRADPPKTHVTHHPVFDYEATLRCWALGFYPAEIILTWQRDGEDQT
QDVELVETRPAGDGTFQKWAAVVVPSGEEQRYTCHVQHEGLPEPLMLRW----*

>P1;6kyuA
structure:6kyuA:    3: :  271: :::-1.00:-1.00
--HSLRYFDTGVSDPSPGVPRFVSVGYVDGHLIDHYDSE--TQRTEPRADWFANTDQQYWDRQTEISRGAEQIFR
LDLETLRERYNQSR-GSHTWQLMYGCDLLEDGS-TRGFRQYGYEGRDFVAFDKDTLTFTAADAGAQITKRKWEQE
GTAERWKFYLENTCIEGLRKYVSYGKDVLERRERPEVQVSGME-ADKILTLSCRAHGFYPRPISISWLKDGMVQE
QETKRGSTVPNSDGTYHIWATIDVLPGERDKYQCRVEHASLPQPGLFSW----*

>P1;6kyuB
structure:6kyuB:    7: :   99: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
----------------------------------PKVQVSRHPTAGTENILNCYVEGFHPPKIDIALLKNGEPM-
KDVKYNDMSFGDDWTFQRLVYAPFTPTKSDVYTCRVDHEAFTEPQSFRWEP--*

>P1;4prhA
structure:4prhA:    1: :  240: :::-1.00:-1.00
-SHSMRYFYTAMSRPGRGEPRFIAVGYVDDTQFVRFDSDAASPRTEPRAPWIEQEGPEYWDRNTQIFKTNTQTYR
ESLRNLRGYYNQSEAGSHIIQRMYGCDLGPDGRLLRGHDQSAYDGKDYIALNEDLSSWTAADTAAQITQRKWEAA
RVAEQRRAYLEGLCVEWLRRYLENGKETLQRADPPKTHV-----------LRCWALGFYPAEITL---------T
QDTELVETRPAGDRTFQKW--------------CHVQHEGLPKPLTLRWE---*

>P1;6iwgA
structure:6iwgA:    1: :  276: :::-1.00:-1.00
GSHSLRYFGTAVSRPGRGEPRFIYVGYVDDTQFVRFDSDAASPRTEPRAPWVEQEGPEYWEEETRRAKARAQTDR
ADLRTLRGYYNQSEAGSHTLQWMAGCDLGPNGRLLRGYHQSAYDGKDYIALNEDLRSWIAADMAAQNTQRKWEAT
RYAERFRAYLEGPCLEWLRRYLENGKETLQHADPPKTHVTHHPVSDHEATLRCWALGFYPAEITLTWQRDGEEQT
QDIEFVETRPAGDGTFQKWGAVVVPSGEEQRYTCHVQHEGLPEPLTLRWEP--*

>P1;4f7eA
structure:4f7eA:   89: :  270: :::-1.00:-1.00
---------------------------------------------------------------------------
-------------------IQIATGCELLP-RNISESFLRAAFQGRDVLSFQG--MSWVSAPDAPPFIQ---EVI
KVLNQNQGTKE--TVHWLRGVLQTGKSELEKQVKPEAWLSSGPPGPGRLLLVCHVSGFYPKPVRVMWMR-GEQEE
PGTRQGDVMPNADSTWYLRVTLDVAAGEVAGLSCQVKHSSLDQDIILYW----*

>P1;4lccC
structure:4lccC:   86: :  333: :::-1.00:-1.00
-THSLRYFRLGISE----IPEFISAGYVDSHPITMYNS--VSQLKEPRALWMEENAPDHWERYTQLLRGWQQMFK
VELKQLQHHYNHS--GFHTYQRMIGCELLEDGS-ITGFLQYAYDGQDFLIFNKDTLSWMAMDNVADIIRRVWEAN
Q-HELLKNWLEEECIAWLKRFLEYGKDALQRTEPPKVRV------NHKTTLYCRAYGFYPPEISINWMKNGEEIF
QDTDYGGILPSGDGTYQTWVSVEL----GDIYSCHVEHGGV------------*

>P1;1hyrC
structure:1hyrC:    4: :  266: :::-1.00:-1.00
--HSLRYNLTVLSWDGSVQSGFLTEVHLDGQPFLRCDRQKC--RAKPQGQWAEDVGNKTWDRETRDLTGN----G
KDLRMTLAHIKDQKEGLHSLQEIRVCEIHEDNS-TRSSQHFYYDGELFLSQNLETKEWTRAQTLAMNVRNKEDAM
KTKTHYHA-MHADCLQELRRYLKSG-VVLRRTVPPMVNVTRSEASEGNITVTCRASGFYPWNITLSWRQDGVSLS
HDTQWGDVLPDGNGTYQTWVATRICQGEEQRFTCYMEHSG-------------*

>P1;3wl9A
structure:3wl9A:    1: :  274: :::-1.00:-1.00
GSHSMRYFSTSVSRPGRGEPRFIAVGYVDDTQFVRFDSDAASQRMEPRAPWIEQEGPEYWDEETGKVKAHSQTDR
ENLRIALRYYNQSEAGSHTLQMMFGCDVGSDGRFLRGYHQYAYDGKDYIALKEDLRSWTAADMAAQITKRKWEAA
HVAEQQRAYLEGTCVDGLRRYLENGKETLQRTDPPKTHMTHHPISDHEATLRCWALGFYPAEITLTWQRDGEDQT
QDTELVETRPAGDGTFQKWAAVVVPSGEEQRYTCHVQHEGLPKPLTLRW----*

>P1;5wl1A
structure:5wl1A:   93: :  274: :::-1.00:-1.00
---------------------------------------------------------------------------
-------------------IQGIAGCELHSGGAILRG----ALGGLDFLSVKNAVPSPEGGSRAQKFCALIIQYQ
GIMETVRILLYETCPRYLLGVLNAGKADLQRQVKPEAWLSSGPPGPGRLQLVCHVSGFYPKPVWVMWMR-GEQEQ
QGTQLGDILPNANWTWYLRATLDVADGEAAGLSCRVKHSSLEQDIILYW----*

>P1;6wl2A
structure:6wl2A:    1: :  178: :::-1.00:-1.00
GPHSLRYFVTAVSRPGLGEPRYMEVGYVDDTEFVRFDSDAENPRYEPRARWMEQECPEYWERETQKAKGNEQSFR
VDLRTLLGYYNQSKGGSHTIQVISGCEVGSDGRLLRGYQQYAYDGQDYIALNEDLKTWTAADMAALITKHKWEQA
GEAERLRAYLEGTCVEWLRRYLKNGNAT-----------------------------------------------
-----------------------------------------------------*

>P1;4k3dL
structure:4k3dL:  122: :  202: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------PPST----EELNGNKATLVCLISDFYPGSVTVVWKADGSTIT
RN---VETTRASKQSNSKYAALSLTSSDKGSYSCEVTHEG-------------*

>P1;1fv1B
structure:1fv1B:   10: :  188: :::-1.00:-1.00
---------------------------------------------------------------------------
--------------------QDKYECHFFNGTERVRFLHRDIYNQEEDLRFDSDVGEYRAVTELGRPDAEYWNSQ
KFLEDRRAAVDTYC---RHNYGVGESFTVQRRVEPK--VTVYPARQHHNLLVCSVNGFYPGSIEVRWFRNSQEEK
AGVVSTGLIQNGDWTFQTLVMLETVPRSGEVYTCQVEHPSVTSPLTVEW----*

>P1;5dmkB
structure:5dmkB:   41: :  189: :::-1.00:-1.00
---------------------------------------------------------------------------
------------------------------------------YNREEYLRFDSDVGEYRAVTELGRHSAEYYN-K
QYLERTRAELDTAC---RHNYEETEVPTLRRLEQPNV-----AISLSHNTLVCSVTDFYPAKIKVRWFRNGQEET
VGVSSTQLIRNGDWTFQVLVMLEMTPHQGEVYTCHVEHPSLKSPITVEW----*

>P1;3p73A
structure:3p73A:    3: :  274: :::-1.00:-1.00
GSHSLRYFLTGMTDPGPGMPRFVIVGYVDDKIFGTYNS--KSRTAQPIVEMLPQEDQEHWDTQTQKAQGGERDFD
WNLNRLPERYNKSK-GSHTMQMMFGCDILEDGS-IRGYDQYAFDGRDFLAFDMDTMTFTAADPVAEITKRRWETG
TYAERWKHELGTVCVQNLRRYLEHGKAALKRRVQPEVRVWGKE-ADGILTLSCHAHGFYPRPITISWMKDGMVRD
QETRWGGIVPNSDGTYHASAAIDVLPEDGDKYWCRVEHASLPQPGLFSWEP--*

>P1;3p73B
structure:3p73B:    5: :   97: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
----------------------------------PKVQVSRFPASGTKNVLNCFAAGFHPPKISITLMKDGVPM-
EGAQYSDMSFNDDWTFQRLVHADFTPSSGSTYACKVEHETLKEPQVYKWDP--*

>P1;1uvqA
structure:1uvqA:   89: :  182: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------PEVTVFSKSPVTGQPNTLICLVDNIFPPVVNITWLSNGQSVT
EGVSETSFLSKSDHSFFKISYLTFLPSADEIYDCKVEHWGLDQPLLKHWEP--*

>P1;1uvqB
structure:1uvqB:   30: :  178: :::-1.00:-1.00
---------------------------------------------------------------------------
------------------------------------------YNREEYARFDSDVGVYRAVTPQGRPDAEYWNSQ
KVLEGTRAELDTVC---RHNYEVAFRGILQRRVEPT--VTISPSN----LLVCSVTDFYPGQIKVRWFRNDQEET
AGVVSTPLIRNGDWTFQILVMLEMTPQRGDVYTCHVEHPSLQSPITVEW----*

>P1;6atfB
structure:6atfB:   31: :  187: :::-1.00:-1.00
---------------------------------------------------------------------------
------------------------------------------HNQEENVRFDSDVGEYRAVTELGRPDAEYWNSQ
KLLEQRRAAVDTYC---RHNYGVGESFTVQRRVHPK--VTVYPSKQHHNLLVCSVSGFYPGSIEVRWFRNGQEEK
TGVVSTGLIHNGDWTFQTLVMLETVPRSGEVYTCQVEHPSVTSPLTVEW----*

>P1;3l9rA
structure:3l9rA:   28: :  274: :::-1.00:-1.00
-------------------------GWLDDLQIHGWESDSGTAKPWSKGNFSDDEVTELVDLFRAYFIGFTREVQ
DRVEFQLEY-------PFVIQVTAGCELGAIESSLRG----ALGGLDFVSI-QNHSCVPAPDSGSRLTTQYQGIS
DIIERL---LSETCPRYLLGVLDAGKAELQRQVKPEAWLSSGPTGPGRLLLVCHVSGFYPKPVRVMWMR-GEQEQ
PGTQQGDLMPNADWTWYLRVTLNVAAGEAAGLNCRVKHSSLDQDIILYW----*

>P1;4l9lC
structure:4l9lC:   69: :  319: :::-1.00:-1.00
-THSLRYFRLGISEPGYGIPEFISAGYVDSHPITMYNS-----QLEPRALWMEENAPDHWERYTQLLRGWQQAFK
VELKQLQHHYNHS--GFHTYQRMIGCELLEDGS-ITGFLQYAYDGQDFLIFNKDTLSWMAMDNVADIIRRVWEAN
RHELQYKNWLEEECIAWLKRFLEYGKDALQRTEPPKVRV------NHKTTLYCRAYGFYPPEISINWMKNGEEIF
QDTDYGGILPSGDGTYQTWVSVELQNGD--IYSCHVEHGGV------------*

>P1;6l9kA
structure:6l9kA:    1: :  175: :::-1.00:-1.00
GPHSMRYYETATSRRGLGEPRYTSVGYVDDKEFVRFDSDAENPRYEPQVPWMEQEGPEYWERITQIAKGQEQWFR
VNLRTLLGYYNQSAGGTHTLQRMYGCDVGSDGRLLRGYEQFAYDGCDYIALNEDLRTWTAADMAAQITRRKWEQA
GAAEYYRAYLEGECVEWLHRYLKNG--------------------------------------------------
-----------------------------------------------------*

>P1;5v5lA
structure:5v5lA:    1: :  278: :::-1.00:-1.00
GSHSMRYFYTAMSRPGRGEPRFIAVGYVDDTQFVRFDSDAASPRTEPRAPWIEQEGPEYWDGETRNMKASAQTYR
ENLRIALRYYNQSEAGSHIIQRMYGCDLGPDGRLLRGHDQSAYDGKDYIALNEDLSSWTAADTAAQITQRKWEAA
RVAEQLRAYLEGLCVEWLRRYLENGKETLQRADPPKTHVTHHPVSDHEATLRCWALGFYPAEITLTWQRDGEDQT
QDTELVETRPAGDRTFQKWAAVVVPSGEEQRYTCHVQHEGLPKPLTLRWEPHH*

>P1;1ld9A
structure:1ld9A:    1: :  268: :::-1.00:-1.00
GPHSMRYFETAVSRPGLGEPRYISVGYVDNKEFVRFDSDAENPRYEPQAPWMEQEGPEYWERITQIAKGQEQWFR
VNLRTLLGYYNQSAGGTHTLQWMYGCDVGSDGRLLRGYEQFAYDGCDYIALNEDLKTWTAADMAAQITRRKWEQA
GAAEYYRAYLEGECVEWLHRYLKNGNATLLRTDSPKAHVTHHPRSKGEVTLRCWALGFYPADITLTWQLNGEELT
QDMELVETRPAGDGTFQKWASVVVPLGKEQNYTCRVYHEGLPE----------*

>P1;5j6hA
structure:5j6hA:    1: :  275: :::-1.00:-1.00
GSHSMRYFETSVSRPGLGEPRFIIVGYVDDTQFVRFDSDAETPRMEPRAPWMEQEGPEYWERETQRAKGNEQSFH
VSLRTLLGYYNQSESGSHTIQWMYGCKVGSDGRFLRGYLQYAYDGRDYIALNEDLKTWTAADVAAIITRRKWEQA
GAAEYYRAYLEAECVEWLLRYLELGKETLLRTDPPKTHVTHHP-GEGDVTLRCWALGFYPADITLTWQLNGEELT
QDMELVETRPAGDGTFQKWASVVVPLGKEQNYTCHVYHEGLPEPLTLRWEP--*

>P1;4x6cC
structure:4x6cC:   24: :  249: :::-1.00:-1.00
-------------------------GWLSDLQTHTWDSNSST--IVFLWPWSRGNSNEEWKELETLFRIRTIRSF
EGIR---RYAHELQFEYPFIQVTGGCEL-HSGKVSGSFLQLAYQGSDFVSFQN--NSWLPYPVAGNMAKHFCKVL
NQNQHTHNLLSDTCPRFILGLLDAGKAHLQRQVKPEAWLSHQ--------LVCHVSGFYPKPVWVMWMR-GEQRG
------DILPSADGTWYLRATL-------EDLSCRVKHSSLEQDIVLYW----*

>P1;4x6fA
structure:4x6fA:   18: :  259: :::-1.00:-1.00
-------------------------GWLSDLQTHTWDSNSST--IVFLWPWSRGNSNEEWKELETLFRIRTIRSF
EGIR---RY-------AHELQFEYPFEIQVTGGCEGSFLQLAYQGSDFVSFQN--NSWLPYPVAGNMAKHFCKVL
NQNQHTHNLLSDTCPRFILGLLDAGKAHLQRQVKPEAWLSHGPPGPGHLQLVCHVSGFYPKPVWVMWMR-GEQEQ
QGTQRGDILPSADGTWYLRATLEVAAGEAADLSCRVKHSSLEQDIVLYWE---*

>P1;5c9jA
structure:5c9jA:   91: :  275: :::-1.00:-1.00
---------------------------------------------------------------------------
-------------------VQVKAGCEL-HSGKSPEGFFQVAFNGLDLLSFQN--TTWSLAQSVCHLLNHQYEG-
-VTETVYNLIRSTCPRFLLGLLDAGKMYVHRQVKPEAWLSSGPPGPGRLQLVCHVSGFYPKPVWVMWMR-GEQEQ
QGTQLGDILPNANWTWYLRATLDVADGEAAGLSCRVKHSSLEQDIILYWGP--*

>P1;6c98A
structure:6c98A:    3: :  258: :::-1.00:-1.00
---SLLYHLTAVSSPAPGTPAFWVSGWLGPQQYLSYNS--LRGEAEPCGAWVENQVSWYWEKETTDLRIKEKLFL
EAFK--------ALGGPYTLQGLLGCELGPDNTSV-PTAKFALNGEEFMNFDLKQGTWGGDPEALAISQRWQQQD
KAANKELTFLLFSCPHRLREHLERGRGNLEWKEPPSMRLKARPSSPGFSVLTCSAFSFYPPELQLRFLRNG--LA
AGTGQGDFGPNSDGSFHASSSLTVKSGDEHHYCCIVQHAGLAQPL--------*

>P1;1hdmB
structure:1hdmB:   85: :  182: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
------------------------------RTRPPSVQVAKTPFNTREVMLACYVWGFYPAEVTITWRKNGKLVM
HSSAHKTAQPNGDWTYQTLSHLALTPSYGDTYTCVVEHIGAPEPILRDWTP--*

>P1;1mfeL
structure:1mfeL:   89: :  201: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-------------CALWCNHWIFGGGTKLTVLGQPKSSVTLFPPSSEEATLVCTITDFYPGVVTVDWKVDGTPVT
QGMETTQPSKQSNNKYMASSYLTLTARAWERYSCQVTHEG-------------*

>P1;6mfgE
structure:6mfgE:   38: :  189: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------RSIYNREEIVRFDSDVGEFRAVTLLGLPAAEYWNSQ
KILERKRAAVDRVC---RHNYQLELRTTLQRRVEPT--VTISPSN----LLVCSVTDFYPAQIKVRWFRNDQEET
AGVVSTPLIRNGDWTFQILVMLEMTPQRGDVYTCHVEHPSLQSPITVEW----*

>P1;1zglB
structure:1zglB:   10: :  174: :::-1.00:-1.00
---------------------------------------------------------------------------
--------------------QDKYECHFFNGTERVRFLHRDIYNQEEDLRFDSDVGEYRAVTELGRPDAEYWNSQ
KFLEDRRAAVDTYC---RHNYGVGESFTVQRRVEPK--VTVYPRTN---LLVCSVNGFYPGSIEVRW----FNSV
VSTGLIQN---GDWTFQTLVMLETVPRSGEVYTCQVEHPSVTSPLTVEW----*

>P1;6dfxB
structure:6dfxB:   50: :  198: :::-1.00:-1.00
---------------------------------------------------------------------------
------------------------------------------YNREEYARFDSDVGVYRAVTPLGPPAAEYWNSQ
KVLERTRAELDTVC---RHNYQLELRTTLQRRVEPT--VTISP----SRLLVCSVTDFYPAQIKVRWFRNDQEET
TGVVSTPLIRNGDWTFQILVMLEMTPQRGDVYTCHVEHPSLQNPIIVEW----*

>P1;3ov6A
structure:3ov6A:  192: :  376: :::-1.00:-1.00
---------------------------------------------------------------------------
-------------------VQVKAGCELHSGGS-PEGFFQVAFNGLDLLSFQQ--TTWSLAQSVCHLLNHQYEG-
-VTETVYNLIRSTCPRFLLGLLDAGKMYVHRQVKPEAWLSSGPPGPGRLQLVCHVSGFYPKPVWVMWMR-GEQEQ
QGTQLGDILPNAQGTWYLRATLDVADGEAAGLSCRVKHSSLEQDIILYW--HH*

>P1;3mbeB
structure:3mbeB:   28: :  177: :::-1.00:-1.00
---------------------------------------------------------------------------
------------------------------------------YNREEYLRFDSDVGEYRAVTELGRHSAEYYN-K
QYLERTRAELDTAC---RHNYEETEVPTLRRLEQPNVAIS---LSRHN-TLVCSVTDFYPAKIKVRWFRNGQEET
VGVSSTQLIRNGDWTFQVLVMLEMTPHQGEVYTCHVEHPSLKSPITVEW----*

>P1;6pudA
structure:6pudA:    3: :  258: :::-1.00:-1.00
-THSLRYFRLGVSDPIHGVPEFISVGYVDSHPITTYDS--VTRQKEPRAPWMENLAPDHWERYTQLLRGWQQMFK
VELKRLQRHYNHS--GSHTYQRMIGCELLEDGS-TTGFLQYAYDGQDFLIFNKDTLSWLAVDNVAHTIKQAWEAN
Q-HELLKNWLEEECIAWLKRFLEYGKDTLQRTEPPLVRV------NRKTALFCKAHGFYPPEIYMTWMKNGEEIV
QEIDYGDILPSGDGTYQAWASIELDPQSSNLYSCHVEHSGV------------*

>P1;5iueA
structure:5iueA:    1: :  274: :::-1.00:-1.00
-SHSLRYFSTAVSRPGRGEPRYIAVEYVDDTQFLRFDSDAAIPRMEPREPWVEQEGPQYWEWTTGYAKANAQTDR
VALRNLLRRYNQSEAGSHTLQGMNGCDMGPDGRLLRGYHQHAYDGKDYISLNEDLRSWTAADTVAQITQRFYEAE
EYAEEFRTYLEGECLELLRRYLENGKETLQRADPPKAHVAHHPISDHEATLRCWALGFYPAEITLTWQRDGEEQT
QDTELVETRPAGDGTFQKWAAVVVPSGEEQRYTCHVQHEGLPQPLILRWE---*

>P1;5nq2A
structure:5nq2A:    2: :  277: :::-1.00:-1.00
GPHSLSYFYTAVSRPDRGEPRFIAVGYVDDTQFVRFDSDAPNPRMEPRAPWIQQEGQDYWDRETQIQRDNAQTFR
VNLRTALGYYNQSEAGSHTFQSMYGCYLGPDGLLLRGYSQYGYDSADYIALNEDLRSWTAADTAAQITKRKWEAA
DEAEQWRSYLQGLCVEGLRRYLEMGKDTLQRAEPPKTHVTRHPSSDLGVTLRCWALGFYPKEISLTWQREGQDQS
QDMELVETRPSGDGTFQKWAALVVPPGEEQSYTCHVQHEGLQEPLTLRWDP--*

>P1;5nq0A
structure:5nq0A:    1: :  275: :::-1.00:-1.00
GPHSLSYFSTAVSRPDRGDSRFIAVGYVDDTQFVRFDSDAPNPRMEPRAPWIQQEGQEYWDRNTRNVMGSAQINR
VNLKTLRGYYNQSEAGSHTLQWMYGCYLGPDGLLLRGYDQFAYDGADYLALNEDLRSWTAADMAAQISKRKWEAA
DAAEHWRSYLQGTCVESLRRYLQMGKDTLQRAEPPKTHVTRHPSSDLGVTLRCWALGFHPKEISLTWQREGQDQS
QDMELVETRPSGDGTFQKWAALVVPPGEEQSYTCHVQHEGLQEPLTLRWD---*

>P1;5nq0B
structure:5nq0B:    3: :   99: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-------------------------------ARPPKVQVSRHPAENGKPNLNCYVSGFHPPQIEIDLLKNGEKMN
AE--------QSDLSFSKWSFYLLPNAVDQ-YSCRVKHVTLDKPKIVKWDRDH*

>P1;6apnA
structure:6apnA:  113: :  384: :::-1.00:-1.00
GSHSMRYFFTSVSRPGRGEPRFIAVGYVDDTQFVRFDSDAASQRMEPRAPWIEQEGPEYWDGETRKVKAHSQTHR
VDLGTLRGAYNQSEAGSHTVQRMYGCDVGSDWRFLRGYHQYAYDGKDYIALKEDLRSWTAADMAAQTTKHKWEAA
HVAEQLRAYLEGTCVEWLRRYLENGKETLQRTDAPKTHMTHHAVSDHEATLRCWALSFYPAEITLTWQRDGEDQT
--TELVETRPAGDGTFQKWAAVVVPSGQEQRYTCHVQHEGLPKPLTLRW----*

>P1;3nwmA
structure:3nwmA:  114: :  383: :::-1.00:-1.00
GPHSLRYFVTAVSRPGLGEPRFIAVGYVDDTQFVRFDSDADNPRFEPRAPWMEQEGPEYWEEQTQRAKSDEQWFR
VSLRTAQRYYNQSKGGSHTFQRMFGCDVGSDWRLLRGYQQFAYDGRDYIALNEDLKTWTAADTAALITRRKWE--
--AEYYRAYLEGECVEWLRRYLELGNETLLRTDSPKAHVTYHPRSQVDVTLRCWALGFYPADITLTWQLNGEDLT
QDMELVETRPAGDGTFQKWAAVVVPLGKEQNYTCHVHHKGLPEPLTLRW----*

>P1;1q72L
structure:1q72L:   85: :  211: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
--AEDVGVY---YCMQHLEYPFTFGSGTIKRADAAPTVSIFPPSSEQGASVVCFLNNFYPQDITVSWKIDGAERS
SGVLNSWTQDSSDSTYSMSSTLTLTKDEYERYTCEATHKTSTSPIT-------*

>P1;1r5vB
structure:1r5vB:   29: :  185: :::-1.00:-1.00
---------------------------------------------------------------------------
------------------------------------------YNLEENLRFDSDVGEFRAVTELGRPDAENWNSP
EFLEQKRAEVDTVC----RHNYEIFDNFLRRVEPTVTYPTKTQPLEHHNLLVCSVSDFYPGNIEVRWFRNGKE--
EKTGIVSTGLVGDWTFQTLVMLETVPQSGEVYTCQVEHPSLTDPVTVEW----*

>P1;6pagA
structure:6pagA:    1: :  275: :::-1.00:-1.00
-SHSMRYFDTAVSRPGRGEPRFISVGYVDDTQFVRFDSDAASPRGEPRAPWVEQEGPEYWDRETQKYKRQAQADR
VSLRNLRGYYNQSEDGSHTLQRMSGCDLGPDGRLLRGYDQSAYDGKDYIALNEDLRSWTAADTAAQITQRKLEAA
RAAEQLRAYLEGTCVEWLRRYLENGKETLQRAEPPKTHVTHHPLSDHEATLRCWALGFYPAEITLTWQRDGEDQT
QDTELVETRPAGDGTFQKWAAVVVPSGQEQRYTCHMQHEGLQEPLTLSWEP--*

>P1;4mayB
structure:4mayB:   22: :  178: :::-1.00:-1.00
---------------------------------------------------------------------------
----------------------------------VRGVTRHIYNREEYVRFDSDVGVYRAVTPQGRPVAEYWNSQ
KVLEGARASVDRVC---RHNYEVAYRGILQRRVEPT--VTISPSN----LLICSVTDFYPSQIKVRWFRNDQEET
AGVVSTPLIRNGDWTFQILVMLEMTPQRGDVYTCHVEHPSLQSPITVEW----*

>P1;1iakA
structure:1iakA:  105: :  181: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-------------------------------------------------TLICFVDNIFPPVINITWLRNSKSVT
DGVYETSFFVNRDYSFHKLSYLTFIPSDDDIYDCKVEHWGLEEPVLKHWEP--*

>P1;1iakB
structure:1iakB:   28: :  183: :::-1.00:-1.00
---------------------------------------------------------------------------
------------------------------------------YNREEYVRFDSDVGEYRAVTELGRPDAEYWN-K
QYLERTRAELDTVC-----RHNYEKTETLRRLEQPSVSLSRTEALNHHNTLVCSVTDFYPAKIKVRWFRNGQEET
VGVSSTQLIRNGDWTFQVLVMLEMTPRRGEVYTCHVEHPSLTSPITVEW----*

>P1;2iadB
structure:2iadB:   42: :  199: :::-1.00:-1.00
---------------------------------------------------------------------------
------------------------------------------YNREEYVRYDSDVGEYRAVTELGRPDAEYWNSP
EILERTRAEVDTAC-----RHNYEGPETLRRLEQPNVAISRTEALNHHNTLVCSVTDFYPAKIKVRWFRNGQEET
VGVSSTQLIRNGDWTFQVLVMLEMTPHQGEVYTCHVEHPSLKSPITVEW----*

>P1;1iaoB
structure:1iaoB:   41: :  198: :::-1.00:-1.00
---------------------------------------------------------------------------
------------------------------------------YNREEYVRYDSDVGEYRAVTELGRPDAEYWNSP
EILDRTRAEVDTAC-----RHNYEGPETLRRLEQPNVAISRTEALNHHNTLVCSVTDFYPAKIKVRWFRNGQEET
VGVSSTQLIRNGDWTFQVLVMLEMTPHQGEVYTCHVEHPSLKSPITVEW----*

>P1;6vqoF
structure:6vqoF:    1: :  254: :::-1.00:-1.00
-SHSMRYFFTSVSRPGRGEPRFIAVGYVDDTQFVRFDSDAASQRMEPRAPWIEQEGPEYWDGETRKVKAHSQTHR
VDLGTLRGYYNQSEAGSHTVQRMYGCDVGSDWRFLRGYHQYAYDGKDYIALKEDLRSWTAADMAAQTTKHKWEAA
HVAEQLRAYLEGTCVEWLRRYLENGKETLQRTDAPKTH-------------RCWALSFYPAEITLTWQRDGEDQT
----LVETRPAGDGTFQKWAAVVVPSGQEQRYTCHVQHEGLPKPLTL------*

>P1;6mtlA
structure:6mtlA:    1: :  276: :::-1.00:-1.00
GSHSMRYFYTAMSRPGRGEPRFITVGYVDDTLFVRFDSDATSPRKEPRAPWIEQEGPEYWDRETQISKTNTQTYR
ENLRTALRYYNQSEAGSHIIQRMYGCDVGPDGRLLRGYDQYAYDGKDYIALNEDLSSWTAADTAAQITQRKWEAA
RVAEQDRAYLEGLCVESLRRYLENGKETLQRADPPKTHVTHHPISDHEVTLRCWALGFYPAEITLTWQRDGEDQT
QDTELVETRPAGDRTFQKWAAVVVPSGEEQRYTCHVQHEGLPKPLTLRWEP--*

>P1;6mt3A
structure:6mt3A:    1: :  276: :::-1.00:-1.00
GSHSMRYFHTSVSRPGRGEPRFISVGYVDGTQFVRFDSDAASPRTEPRAPWIEQEGPEYWDRNTQISKTNTQTYR
ESLRNLRGYYNQSEAGSHTLQRMYGCDVGPDGRLLRGHDQSAYDGKDYIALNEDLSSWTAADTAAQITQRKWEAA
RVAEQLRAYLEGTCVEWLRRHLENGKETLQRADPPKTHVTHHPISDHEATLRCWALGFYPAEITLTWQRDGEDQT
QDTELVETRPAGDRTFQKWAAVVVPSGEEQRYTCHVQHEGLPKPLTLRWEP--*

>P1;1nj9L
structure:1nj9L:   90: :  202: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-------------CALWYNHWVFGGGTKLTVLGQPKSSVTLFPPSSEEATLVCTITDFYPGVVTVDWKVDGTPVT
QGMETTQPSKQSNNKYMASSYLTLTAREWERYSCQVTHEG-------------*

>P1;5xmfA
structure:5xmfA:    1: :  275: :::-1.00:-1.00
GSHSLRYFYTAVSRPGLGEPRFIAVGYVDDTQFVRFDSDAPNPRMEPRAPWVEQEGPEYWDRETRKVKNTAQIFR
VDLNTLLRYYNQSESGSHNIQRMYGCDVEPDGRLLRGYNQDSYDGKDYIALNEDLRSWTAADTAAQITGRKWEEA
GEAERWRNYLQGTCVEWLAKYLDMGKETLLRAESPNTRVTRHPISDREVTLRCWALGFYPAEITLTWQRDGQDHT
QDAELVETRPAGDGTFQKWAAVVVSSGEEQRYTCHVQHEGLREPITLRWE---*

>P1;5xmfB
structure:5xmfB:    6: :   96: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
----------------------------------PKVQVSRHPAENGKPNLNCYVSGFHPPQIDITLMKNGKKEA
EQTDLSFNR---DWTFYLLVHTEFTPTVEDEYSCQVNHTTLSEPKVVKWD---*

>P1;4iiqC
structure:4iiqC:   98: :  350: :::-1.00:-1.00
-THSLRYFRLGISEPGYGIPEFISAGYVDSHPITMYNSVS---QLEPRALWMEENAPDHWERYTQLLRGWQQAFK
VELKQLQHHYNHS--GFHTYQRMIGCELLEDGS-ITGFLQYAYDGQDFLIFNKDTLSWMAMDNVADIIRRVWEAN
RHELQYKNWLEEECIAWLKRFLEYGKDALQRTEPPKVRV------NHKTTLYCRAYGFYPPEISINWMKNGEEIF
QDTDYGGILPSGDGTYQTWVSVELQNGD--IYSCHVEHGGV------------*

>P1;1kluB
structure:1kluB:   28: :  188: :::-1.00:-1.00
---------------------------------------------------------------------------
--------------------------------------ERCIYNQEESVRFDSDVGEYRAVTELGRPDAEYWNSQ
KLLEQRRAAVDTYC---RHNYGVGESFTVQRRVEPK--VTVYPSKQHHNLLVCSVSGFYPGSIEVRWFRNGQEEK
AGVVSTGLIQNGDWTFQTLVMLETVPRSGEVYTCQVEHPSVTSPLTVEW----*

>P1;3o6fF
structure:3o6fF:   57: :  209: :::-1.00:-1.00
---------------------------------------------------------------------------
--------------------------------------DRYFYHQEEYVRFDSDVGEYRAVTELGRPDAEYWNSQ
KLLEQKRAAVDTYC---RHNYGVGESFTVQRRVYPE--VTVYPAN----LLVCSVNGFYPGSIEVRWFRNGQEEK
TGVVSTGLIQNGDWTFQTLVMLETVPRSGEVYTCQVEHPSLTSPLTVEW----*

>P1;5ymwA
structure:5ymwA:    4: :  271: :::-1.00:-1.00
--HTLRYIQTAMTDPGPGQPWFVTVGYVDGELFVHYNSTAR--RYVPRTEWIAAKAQQYWDGQTQIGQGNEQIDR
ENLGILQRRYNQT-GGSHTVQWMYGCDI-LEGGPIRGYYQMAYDGRDFTAFDKGTMTFTAAVPEAVPTKRKWEEE
SEPERWKNYLEETCVEWLRRYVEYGKAELGRRERPEVRVWGKE-ADGILTLSCRAHGFYPRPIVVSWLKDGAVRG
QDAHSGGIVPNGDGTYHTWVTIDAQPGDGDKYQCRVEHASLPQPGLYSW----*

>P1;1ymmB
structure:1ymmB:   26: :  177: :::-1.00:-1.00
---------------------------------------------------------------------------
--------------------------------------DRYFYNQEESVRFDSDVGEFRAVTELGRPDAEYWNSQ
KILEQARAAVDTYC---RHNYGVVESFTVQRRVQPK--VTVYP-----SLLVCSVSGFYPGSIEVRWFLNGQEEK
ASTGLIQN---GDWTFQTLVMLETVPRSGEVYTCQVEHPSVTSPLTVEW----*

>P1;4i0pC
structure:4i0pC:  105: :  179: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
--------------------------------------------------LICIVDNIFPPVINITWLRNGQTVT
EGVAQTSFYSQPDHLFRKFHYLFVPSAEDV-YDCQVEHWGLDAPLLRHWE---*

>P1;4i0pD
structure:4i0pD:   32: :  185: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------EEYVRFDSDVGMFVALTKLGQPDAEQWNSL
DLLERSRQAVDGVC---RHNYRLGAPFTVGRKVQPEVTVERTPLLHQHNLLHCSVTGFYPGDIKIKWFLNGQEER
--AGVMSTGPIGDWTFQTVVMLEMTPELGHVYTCLVDHSSLLSPVSVEW----*

>P1;5ujtA
structure:5ujtA:   89: :  182: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------PEVTVFSKSPVTGQPNTLICLVDNIFPPVVNITWLSNGHSVT
EGVSETSFLSKSDHSFFKISYLTFLPSDDEIYDCKVEHWGLDEPLLKHWEP--*

>P1;5ujtB
structure:5ujtB:   30: :  185: :::-1.00:-1.00
---------------------------------------------------------------------------
------------------------------------------YNREEYARFDSDVGVYRAVTPLGPPAAEYWNSQ
KVLERTRAELDTVC---RHNYQLELRTTLQRVEPTVTISPSTEALNHHNLLVCSVTDFYPAQIKVRWFRNDQEET
TGVVSTPLIRNGDWTFQILVMLEMTPQRGDVYTCHVEHPSLQNPIIVEW----*

>P1;5ujtH
structure:5ujtH:   30: :  177: :::-1.00:-1.00
---------------------------------------------------------------------------
------------------------------------------YNREEYARFDSDVGVYRAVTPLGPPAAEYWNSQ
KVLERTRAELDTVC---RHNYQLELRTTLQRRVEPTVTISPN-------LLVCSVTDFYPAQIKVRWFRNDQEET
TGVVSTPLIRNGDWTFQILVMLEMTPQRGDVYTCHVEHPSLQNPIIVEW----*

>P1;3vwkA
structure:3vwkA:  106: :  249: :::-1.00:-1.00
---------------------------------------------------------------------------
-----------------------------------------AFQGKDILSFQG--TSWEPTQEAQVLNQDKW---
-TRETVQWLLNGTCPQFVSGLLESGKSELKKQVKPKAWLSRGP-SPGRLLLVCHVSGFYPKPVWVKW------MT
QPGDIL---PNADETWYLRATLDVLS-------CRVKHSSLEQDIVLYW----*

>P1;6blqA
structure:6blqA:  108: :  184: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-------------------------------------------------TLICFVDNIFPPVINITWLRNSKDGV
YETSFLVNR---DHSFHKLSYLTFIPSDDDIYDCKVEHWGLEEPVLKHWEP--*

>P1;6blqB
structure:6blqB:   50: :  198: :::-1.00:-1.00
---------------------------------------------------------------------------
------------------------------------------YNREEYLRFDSDVGEYRAVTELGRHSAEYYN-K
QYLERTRAELDTAC---RHNYEETEVPTLRRLEQPNV-----AISLSHNTLVCSVTDFYPAKIKVRWFRNGQEET
VGVSSTQLIRNGDWTFQVLVMLEMTPHQGEVYTCHVEHPSLKSPITVEW----*

>P1;3d2uA
structure:3d2uA:    1: :  269: :::-1.00:-1.00
--HVLRYGYTGIF-DDTSHMTLTVVGIFDGQHFFTYSSDKASSRANGTISWVSAAYPTYLDKGDLIFNQTEQNLL
E-LEIALGYRSQS-----VLTWTHECNTTENGSFVAGYEGFGWDGETLMELKDNLTLWTGPNLKQQKTYIDGKIK
NISEGQRNYLKGNCTQWSVIY--------SGFQPPVTHVVKGGVNDNRAEAFCTSYGFFPGEIQITFIHYGDKVP
EDSECNPLLPTLDGTFHQGCYVAIFS--NQNYTCRVTH---------------*

>P1;6irlA
structure:6irlA:    5: :  272: :::-1.00:-1.00
--HTLRYISTAMTDPGPGQPWYVDVGYVDGELFTHYNSTAR--RAVPRTEWIANTDQQYWDSETQTSQRTEQIDR
DGLGTLQRRYNQT-GGSHTVQLMYGCDILEDG-TIRGYSQDAYDGRDFIAFDKDTMTFTAAVPEAVPTKRKWEEG
DYAEGLKQYLEETCVEWLRRYVEYGKAELGRRERPEVRVWGKE-ADGILTLSCRAHGFYPRPIAVSWLKDGAVQG
QDAQSGGIVPNGDGTYHTWVTIDAQPGDGDKYQCRVEHASLPQPGLYSW----*

>P1;5iroI
structure:5iroI:    1: :  252: :::-1.00:-1.00
GSHSMRYFFTSVSRPGRGEPRFIAVGYVDDTQFVRFDSDAASQRMEPRAPWIEQEGPEYWDGETRKVKAHSQTHR
VDLG-TLRGY---EAGSHTVQRMYGCDVGSDWRFLRGYHQYAYDGKDYIALKEDLRSWTAADMAAQTTKHKWEAA
HVAEQLRAYLEGTCVEWLRRYLENGKETLQRTDAPKTHMTHHAVSDH---LRCWALSFYPAEITLTWQRDGE---
--TELVETRPAGDGTFQ-------PSGQEQRYTCHVQHEGLPKPLT-------*

>P1;5iroU
structure:5iroU:    1: :  246: :::-1.00:-1.00
----MRYFFTSVSRPGRGEPRFIAVGYVDDTQFVRFDSDAASQRMEPRAPWIEQEGPEYWDGETRKVKAHSQTHR
VDLGTLRGYYNQSEAGSHTVQRMYGCDVGSDWRFLRGYHQYAYDGKDYIALKEDLRSWTAADMAAQTTKHKWEAA
HVAEQLRAYLEGTCVEWLRRYLENGKETLQRTD-----MTHHAVS-----LRCWALSFYPAEI-----------T
QDTELVETRPAGDGTFQKWAAVVVPSGQEQRYTCHVQHEGLPKPLT-------*

>P1;5h5zA
structure:5h5zA:    1: :  259: :::-1.00:-1.00
GTHSLKYVYTGVSR-GIDFPEFTAVGMVDDGQFMYFDSN--SMKAVPKTEWIRQEGADYWDRQTQVLIGAHQVFK
DSIQIVMERFNQSK-GVHTWQNMYGCELNDDG-TTQGFYQYAYDGEDFVSLDKNTLTWTAANPQAVITKHKWEAL
AVAEQNKGYLENTCIEWLKKYVAYGKDTLERKVSPQVSLLQ---KDPSSPVTCHATGFYPSGVTITWQKNGQDHD
EDVDLGELLPNEDGSFQRMSTLNVGPDENNRFSCVVEHQ--------------*

>P1;6gl1G
structure:6gl1G:    1: :  249: :::-1.00:-1.00
GSHSLKYFHTSVSRPGRGEPRFISVGYVDDTQFVRFDNDAASPRMVPRAPWMEQEGSEYWDRETRSARDTAQIFR
VNLRTLRGYYNQSEAGSHTLQWMHGCELGPDGRFLRGYEQFAYDGKDYLTLNEDLRSWTAVDTAAQISEQKSNDA
SEAEHQRAYLEDTCVEWLHKYLEKGKETLLHLEPPKTHVTH-----HEATLRCWALGFYPAEITLT--------T
QDTELVETRPAGDGTFQKWAA------------CHVQHEGLPEPVTLRW----*

>P1;1c16A
structure:1c16A:    1: :  258: :::-1.00:-1.00
GSHSLRYFYTAVSRPGLGEPWFIIVGYVDDMQVLRFSSKEETPR---MAPWLEQEEADNWEQQTRIVTIQGQLSE
RNLMTLVHFYNKSMDDSHTLQWLQGCDVEPDRHLCLWYNQLAYDSEDLPTLNENPSSCTVGNST---------VP
HISQDLKSH----CSDLLQKYLEKGKERLLRSDPPKAHVTRHPRPEGDVTLRCWALGFYPADITLTWQLNGEELT
QDMELVETRPAGDGTFQKWAAVVVPLGKEQSYTCHVYHEGLPEPLILRW----*

>P1;3c5jB
structure:3c5jB:   29: :  180: :::-1.00:-1.00
---------------------------------------------------------------------------
------------------------------------------HNQEEFVRFDSDVGEYRAVTELGRPVAESWNSQ
KLLEQKRGQVDNYC---RHNYGVVESFTVQRRVHPQ--VTVYPAKHHN-LLVCSVSGFYPGSIEVRWFRNGQEEK
TGVVSTGLIHNGDWTFQTLVMLETVPRSGEVYTCQVEHPSVTSPLTVEW----*

>P1;2wy3A
structure:2wy3A:    4: :  173: :::-1.00:-1.00
--HSLRYNLMVLSQDESVQSGFLAEGHLDGQPFLRYDRQ--KRRAKPQGQWAEDVGAETWDTETEDLTENGQ---
-DLRRTLTHIKDQKGGLHSLQEIRVCEIHEDSS-TRGSRHFYYNGELFLSQNLETQESTVAQTLAMNVTNFWK-E
KTKTHYRA-MQADCLQKLQRYLKSG--------------------------------------------------
-----------------------------------------------------*

>P1;6a2bA
structure:6a2bA:    1: :  272: :::-1.00:-1.00
GSHSLRYYYTAVSDRAFGLPEFSIVGYVDDTQSFRYNSD--NQKAEPATQWMKQEGPEYWEQQTQIAKGSEPVHK
HDVKTAMDRFNQT-SGTHSLQVMYGCELREDNS-IRSYHQYGYDGREFIALDTERWVYVPSVREAQLTEQKWNSP
EVPERNKNYLQNLCIEGLKRYLSYGRAELERRVHPHVRISDHQ-SDDATELRCHAYGFYPREIDVKWVKNGRADV
HSEAAKEILPNPDGSYQLRVTAEITPSEGDSYACHVEHSSLKEKLIVVW----*

>P1;3rwiA
structure:3rwiA:    1: :  276: :::-1.00:-1.00
GSHSMKYFYTSVSRPGRGEPRFISVGYVDDTQFVRFDSDAESPREEPRAPWVEQEGPEYWEEATRRAKEAAQTHR
ENLRTALRYYNQSEAGSHTIQKMYGCDLGPDGRLLRGYHQSAYDGKDYIALNGDLRSWTAADMAAQNTQRKWEGN
RYAERFRAYLEGECLEWLRRYLENGKETLQRADPPKTHVTHHPVSDHEATLRCWALGFYPAEITLTWQRDGEEQT
QDTEFVETRPGGDGTFQKWGAVVVPSGEEQRYTCHVQHEGLPEPLTLRWEP--*

>P1;6v0yA
structure:6v0yA:   84: :  174: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------PEVTVLTNSPVELREPVLICFIDKFTPPVVNVTWLRNGKPVT
TGVSETVFLPREDHLFRKFH--YLPFLPEDVYDCRVEHWGLDEPLLKHWE---*

>P1;6jtoA
structure:6jtoA:    1: :  273: :::-1.00:-1.00
-SHSMRYFYTAVSRPGRGEPRFIAVGYVDDTQFVQFDSDAASPRGEPRAPWVEQEGPEYWDRETQKYKRQAQTDR
VNLRKLRGYYNQSEAGSHTLQRMYGCDLGPDGRLLRGYNQFAYDGKDYIALNEDLRSWTAADKAAQITQRKWEAA
REAEQRRAYLEGTCVEWLRRYLENGKKTLQRAEHPKTHVTHHPVSDHEATLRCWALGFYPAEITLTWQRDGEDQT
QDTELVETRPAGDGTFQKWAAVVVPSGEEQRYTCHVQHEGLPEPLTLRW----*

>P1;3jttA
structure:3jttA:    1: :  276: :::-1.00:-1.00
GSHSMRYFYTSMSRPGRWEPRFIAVGYVDDTQFVRFDSDAASQRMEPRAPWVEQEGPEYWDRETRNMKAETQNAP
VNLRNLRGYYNQSEAGSHTIQRMYGCDLGPDGRLLRGYHQSAYDGKDYIALNEDLRSWTAADMAAQNTQRKWEAA
GEAEQHRTYLEGECLEWLRRYLENGKETLQRADPPKTHVTHHPVSDQEATLRCWALGFYPAEITLTWQRDGEDQT
QDTELVETRPAGDGTFQKWAAVVVPSGKEQRYTCHVQHEGLREPLTLRWEP--*

>P1;6j2aA
structure:6j2aA:    1: :  274: :::-1.00:-1.00
GSHSMRYFSTSVSRPGSGEPRFIAVGYVDDTQFVRFDSDAASQRMEPRAPWIEQEGPEYWDQETRNVKAHSQTDR
ENLGTLRGYYNQSEAGSHTIQIMYGCDVGSDGRFLRGYEQHAYDGKDYIALNEDLRSWTAADMAAQITQRKWEAA
RRAEQLRAYLEGTCVEWLRRYLENGKETLQRTDPPKTHMTHHPISDHEATLRCWALGFYPAEITLTWQRDGEDQT
QDTELVETRPAGDGTFQKWAAVVVPSGEEQRYTCHVQHEGLPKPLTLRW----*

>P1;6j2fA
structure:6j2fA:    1: :  277: :::-1.00:-1.00
GFHSLRYFYTAWSRPGSGEPRFVAVGYVDDTQFVRFDSDNASPRAEPRAPWVEQQDPQYWDRNTRNARDAAQTYR
VGLDNVRGYYNQSEAGSHTIQRMYGCDVGPHGRLLRGYDQLAYDGADYIALNEDLRSWTAADLAAQNTRRKWEEA
GYAERDRAYLEGECVEWLLKHLENGRETLLRADPPKTHITHHPISDREVTLRCWALGFYPEEITLTWQHDGEDQT
QEMELVETRPDGNGAFQKWAALVVPSGEEQRYTCHVQHEGLPQPLTLRW----*

>P1;1lk2A
structure:1lk2A:    1: :  274: :::-1.00:-1.00
GPHSLRYFVTAVSRPGLGEPRYMEVGYVDDTEFVRFDSDAENPRYEPRARWMEQEGPEYWERETQKAKGNEQSFR
VDLRTLLGYYNQSKGGSHTIQVISGCEVGSDGRLLRGYQQYAYDGCDYIALNEDLKTWTAADMAALITKHKWEQA
GEAERLRAYLEGTCVEWLRRYLKNGNATLLRTDSPKAHVTHHSRPEDKVTLRCWALGFYPADITLTWQLNGEELI
QDMELVETRPAGDGTFQKWASVVVPLGKEQYYTCHVYHQGLPEPLTLRW----*

>P1;2p24B
structure:2p24B:   42: :  189: :::-1.00:-1.00
---------------------------------------------------------------------------
------------------------------------------YNREEYLRFDSDVGEYRAV-TELGRPDAEYYNK
QYLERTRAELDTVC-----RY--NYEETLRRLEQPNV------VISLSNTLVCSVTDFYPAKIKVRWFRNGQEET
VGVSSTQLIRNGDWTFQVLVMLEMTPRRGEVYTCHVEHPSLKSPITVEW----*

>P1;4p23D
structure:4p23D:   15: :  198: :::-1.00:-1.00
---------------------------------------------------------------------------
-----------------HFVYQFMGCYFTDGTQRIRYVTRYIYNREEYVRYDSDVGEHRAVTELGRPDAEYWNSP
EILERTRAELDTVC-----RHNYEGPETLRRLEQPNVSLSRTEALNHHNTLVCSVTDFYPAKIKVRWFRNGQEET
VGVSSTQLIRNGDWTFQVLVMLEMTPRRGEVYTCHVEHPSLKSPITVEW----*

>P1;1nezA
structure:1nezA:    1: :  274: :::-1.00:-1.00
GSHSLRYFYTALSRPAISEPWYIAVGYLDDTQFARFDSAGETGTYKLSAPWVEQEGPEYWARETEIVTSNAQFFR
ENLQTMLDYYNLSQNGSHTIQVMYGCEVEFFGSLFRAYEQHGYDGQDYIALNEDLKTWTAADMAAEITRSKWEQA
GYTELRRTYLEGPCKDSLLRYLENRKKTQECTDPPKTHVTHHARPEGDVTLRCWALGFYPAHITLTWQLNGEELI
QDTELVETRPAGDGTFQKWAAVVVPSGEEQKYTCHVYHEGLPEPLTLRW----*

>P1;6lb2A
structure:6lb2A:    2: :  277: :::-1.00:-1.00
GSHSMRYFSTTVSRPGRGEPRFIVVGYVDDTQFVRFDSDAASPKMEPRAPWMEQEGPEYWEEQTRRVKDAAQTFR
VSLGNLRGYYNQSEAGSHTLQTMSGCDLGPDGRLLRGYYQQAYDGRDYIALNEDLRSWTAADEAAQNTQRKWEAA
GVAEQWRAYLEGECLESLRRYLENGKETLQRAEPPKTHVTHHPVSDHEATLRCWALGFYPAEITLTWQRDGEDQT
QDTELVETRPGGDGTFQKWGAVVVPSGEEQRYTCHVQHEGLPEPLTLRWEP--*

>P1;4ah2B
structure:4ah2B:   43: :  197: :::-1.00:-1.00
---------------------------------------------------------------------------
--------------------------------------ERCIYNQEESVRFDSDVGEYRAVTELGRPDAEYWNSQ
KLLEQRRAAVDTYC---RHNYGVGESFTVQRRVEPK--VTVYP--SHHNLLVCSVSGFYPGSIEVRWFRNGQEEK
AGVVSTGLIQNGDWTFQTLVMLETVPRSGEVYTCQVEHPSVTSPLTVEW----*

>P1;5gsbA
structure:5gsbA:    1: :  274: :::-1.00:-1.00
GPHSLRYFVTAVSRPGLGEPRFIAVGYVDDTQFVRFDSDADNPRFEPRAPWMEQEGPEYWEEQTQRAKSDEQWFR
VSLRTAQRYYNQSKGGSHTFQRMFGCDVGSDWRLLRGYHQFAYDGRDYIALNEDLKTWTAADTAALITRRKWEQA
GDAEYYRAYLEGECVEWLRRYLELGNETLLRTDSPKAHVTYHPRSQVDVTLRCWALGFYPADITLTWQLNGEDLT
QDMELVETRPAGDGTFQKWAAVVVPLGKEQNYTCHVHHKGLPEPLTLRW----*

>P1;4s0uC
structure:4s0uC:    3: :  170: :::-1.00:-1.00
--HSLSYDITVIPRPG---PRWCAVGQVDEKTFLHYDCGNKTV-TPVSPLGKKLNVTMAWKAQNPVLREVVDILT
EQLDIQLENYTPKEPLT--LQARMSCEQKAEGH-SSGSWQFSIDGQTFLLFDSEKRMWTTVHPGARKMKEKWEND
KVAMSFHYISMGDCIGWLEDFL-----------------------------------------------------
-----------------------------------------------------*

>P1;2bc4B
structure:2bc4B:   91: :  189: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
------------------------------RTRPPSVQVAKTPFNTREVMLACYVWGFYPAEVTITWRKNGKLVM
PHSSAHKTQPNGDWTYQTLSHLALTPSYGDTYTCVVEHIGAPEPILRDWTP--*
