
>P1;1RERC
sequence:1RERC:    0: :    0: :::-1.00:-1.00
YEHSTVMPNVVGFPYKAHIERPGYSPLTLQMQVVETSLEPTLNLEYITCEYKTVVPSPYVKCCGASECSTKEKPD
YQCKVYTGVYPFMWGGAYCFCDSENTQLSEAYVDRSDVCRHDHASAYKAHTASLKAKVRVMYGNVNQTVDVYVNG
DHAVTIGGTQFIFGPLSSAWTPFDNKIVVYKDEVFNQDFPPYGSGQPGRFGDIQSRTVESNDLYANTALKLARPS
PGMVHVPYTQTPSGFKYWLKEKGTALNTKAPFGCQIKTNPVRAMNCAVGNIPVSMNLPDSAFTRIVEAPTIIDLT
CTVATCTHSSDFGGVLTLTYKTNKNGDCSVHSHSNVATLQEATAKVKTAGKVTLHFSTASASPSFVVSLCSARAT
CSASCEPPKDHIVPYA*

>P1;1LD4M
sequence:1LD4M:    1: :  354: :::-1.00:-1.00
-EHATTVPNVPQIPYKALVERAGYAPLNLEITVMSSEVLPSTNQEYITCKFTTVVPSPKIKCCGSLECQPAAHAD
YTCKVFGGVYPFMWGGAQCFCDSENSQMSEAYVELSADCASDHAQAIKVHTAAMKVGLRIVYGNTTSFLDVYVNG
VTPGTSKDLKVIAGPISASFTPFDHKVVIHRGLVYNYDFPEYGAMKPGAFGDIQATSLTSKDLIASTDIRLLKPS
AKNVHVPYTQASSGFEMWKNNSGRPLQETAPFGCKIAVNPLRAVDCSYGNIPISIDIPNAAFIRTSDAPLVSTVK
CEVSECTYS-----MATLQYVSDREGQCPVHSHSSTATLQESTV------HVTVHFSTASPQANFI---------
----------------*

>P1;1LD4N
sequence:1LD4N:    1: :  354: :::-1.00:-1.00
-EHATTVPNVPQIPYKALVERAGYAPLNLEITVMSSEVLPSTNQEYITCKFTTVVPSPKIKCCGSLECQPAAHAD
YTCKVFGGVYPFMWGGAQCFCDSENSQMSEAYVELSADCASDHAQAIKVHTAAMKVGLRIVYGNTTSFLDVYVNG
VTPGTSKDLKVIAGPISASFTPFDHKVVIHRGLVYNYDFPEYGAMKPGAFGDIQATSLTSKDLIASTDIRLLKPS
AKNVHVPYTQASSGFEMWKNNSGRPLQETAPFGCKIAVNPLRAVDCSYGNIPISIDIPNAAFIRTSDAPLVSTVK
CEVSECTYS-----MATLQYVSDREGQCPVHSHSSTATLQESTV------HVTVHFSTASPQANFI---------
----------------*

>P1;1LD4O
sequence:1LD4O:    1: :  354: :::-1.00:-1.00
-EHATTVPNVPQIPYKALVERAGYAPLNLEITVMSSEVLPSTNQEYITCKFTTVVPSPKIKCCGSLECQPAAHAD
YTCKVFGGVYPFMWGGAQCFCDSENSQMSEAYVELSADCASDHAQAIKVHTAAMKVGLRIVYGNTTSFLDVYVNG
VTPGTSKDLKVIAGPISASFTPFDHKVVIHRGLVYNYDFPEYGAMKPGAFGDIQATSLTSKDLIASTDIRLLKPS
AKNVHVPYTQASSGFEMWKNNSGRPLQETAPFGCKIAVNPLRAVDCSYGNIPISIDIPNAAFIRTSDAPLVSTVK
CEVSECTYS-----MATLQYVSDREGQCPVHSHSSTATLQESTV------HVTVHFSTASPQANFI---------
----------------*

>P1;1LD4P
sequence:1LD4P:    1: :  354: :::-1.00:-1.00
-EHATTVPNVPQIPYKALVERAGYAPLNLEITVMSSEVLPSTNQEYITCKFTTVVPSPKIKCCGSLECQPAAHAD
YTCKVFGGVYPFMWGGAQCFCDSENSQMSEAYVELSADCASDHAQAIKVHTAAMKVGLRIVYGNTTSFLDVYVNG
VTPGTSKDLKVIAGPISASFTPFDHKVVIHRGLVYNYDFPEYGAMKPGAFGDIQATSLTSKDLIASTDIRLLKPS
AKNVHVPYTQASSGFEMWKNNSGRPLQETAPFGCKIAVNPLRAVDCSYGNIPISIDIPNAAFIRTSDAPLVSTVK
CEVSECTYS-----MATLQYVSDREGQCPVHSHSSTATLQESTV------HVTVHFSTASPQANFI---------
----------------*

>P1;1RERA
sequence:1RERA:    1: :  391: :::-1.00:-1.00
YEHSTVMPNVVGFPYKAHIERPGYSPLTLQMQVVETSLEPTLNLEYITCEYKTVVPSPYVKCCGASECSTKEKPD
YQCKVYTGVYPFMWGGAYCFCDSENTQLSEAYVDRSDVCRHDHASAYKAHTASLKAKVRVMYGNVNQTVDVYVNG
DHAVTIGGTQFIFGPLSSAWTPFDNKIVVYKDEVFNQDFPPYGSGQPGRFGDIQSRTVESNDLYANTALKLARPS
PGMVHVPYTQTPSGFKYWLKEKGTALNTKAPFGCQIKTNPVRAMNCAVGNIPVSMNLPDSAFTRIVEAPTIIDLT
CTVATCTHSSDFGGVLTLTYKTNKNGDCSVHSHSNVATLQEATAKVKTAGKVTLHFSTASASPSFVVSLCSARAT
CSASCEPPKDHIVPYA*

>P1;1RERB
sequence:1RERB:    1: :  391: :::-1.00:-1.00
YEHSTVMPNVVGFPYKAHIERPGYSPLTLQMQVVETSLEPTLNLEYITCEYKTVVPSPYVKCCGASECSTKEKPD
YQCKVYTGVYPFMWGGAYCFCDSENTQLSEAYVDRSDVCRHDHASAYKAHTASLKAKVRVMYGNVNQTVDVYVNG
DHAVTIGGTQFIFGPLSSAWTPFDNKIVVYKDEVFNQDFPPYGSGQPGRFGDIQSRTVESNDLYANTALKLARPS
PGMVHVPYTQTPSGFKYWLKEKGTALNTKAPFGCQIKTNPVRAMNCAVGNIPVSMNLPDSAFTRIVEAPTIIDLT
CTVATCTHSSDFGGVLTLTYKTNKNGDCSVHSHSNVATLQEATAKVKTAGKVTLHFSTASASPSFVVSLCSARAT
CSASCEPPKDHIVPYA*

>P1;1RERC
sequence:1RERC:    1: :  391: :::-1.00:-1.00
YEHSTVMPNVVGFPYKAHIERPGYSPLTLQMQVVETSLEPTLNLEYITCEYKTVVPSPYVKCCGASECSTKEKPD
YQCKVYTGVYPFMWGGAYCFCDSENTQLSEAYVDRSDVCRHDHASAYKAHTASLKAKVRVMYGNVNQTVDVYVNG
DHAVTIGGTQFIFGPLSSAWTPFDNKIVVYKDEVFNQDFPPYGSGQPGRFGDIQSRTVESNDLYANTALKLARPS
PGMVHVPYTQTPSGFKYWLKEKGTALNTKAPFGCQIKTNPVRAMNCAVGNIPVSMNLPDSAFTRIVEAPTIIDLT
CTVATCTHSSDFGGVLTLTYKTNKNGDCSVHSHSNVATLQEATAKVKTAGKVTLHFSTASASPSFVVSLCSARAT
CSASCEPPKDHIVPYA*

>P1;1Z8YA
sequence:1Z8YA:    1: :  288: :::-1.00:-1.00
-EHATTVPNVPQIPYKALVERAGYAPLNLEITVMSSEVLPSTNQEYITCKFTTVVPSPKIKCCGSLECQPAAHAD
YTCKVFGGVYPFMWGGAQCFCDSENSQMSEAYVELSADCASDHAQAIKVHTAAMKVGLRIVYGNTTSFLDVYVNG
VTPGTSKDLKVIAGPISASFTPFDHKVVIHRGLVYNYDFPEYGAMKPGAFGDIQATSLTSKDLIASTDIRLLKPS
AKNVHVPYTQASSGFEMWKNNSGRPLQETAPFGCKIAVNPLRAVDCSYGNIPISIDIPNAAFIR-----------
---------------------------------------------------------------------------
----------------*

>P1;1Z8YB
sequence:1Z8YB:    7: :   89: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------------------------------------------------
CEVSECTYSADFGGMATLQYVSDREGQCPVHSHSSTATLQESTVHVLEKGAVTVHFSTASPQANFIVSLCGKKTT
CNAECKPP--------*

>P1;1Z8YC
sequence:1Z8YC:    1: :  289: :::-1.00:-1.00
YEHATTVPNVPQIPYKALVERAGYAPLNLEITVMSSEVLPSTNQEYITCKFTTVVPSPKIKCCGSLECQPAAHAD
YTCKVFGGVYPFMWGGAQCFCDSENSQMSEAYVELSADCASDHAQAIKVHTAAMKVGLRIVYGNTTSFLDVYVNG
VTPGTSKDLKVIAGPISASFTPFDHKVVIHRGLVYNYDFPEYGAMKPGAFGDIQATSLTSKDLIASTDIRLLKPS
AKNVHVPYTQASSGFEMWKNNSGRPLQETAPFGCKIAVNPLRAVDCSYGNIPISIDIPNAAFIR-----------
---------------------------------------------------------------------------
----------------*

>P1;1Z8YD
sequence:1Z8YD:    7: :   89: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------------------------------------------------
CEVSECTYSADFGGMATLQYVSDREGQCPVHSHSSTATLQESTVHVLEKGAVTVHFSTASPQANFIVSLCGKKTT
CNAECKPP--------*

>P1;1Z8YE
sequence:1Z8YE:    1: :  289: :::-1.00:-1.00
YEHATTVPNVPQIPYKALVERAGYAPLNLEITVMSSEVLPSTNQEYITCKFTTVVPSPKIKCCGSLECQPAAHAD
YTCKVFGGVYPFMWGGAQCFCDSENSQMSEAYVELSADCASDHAQAIKVHTAAMKVGLRIVYGNTTSFLDVYVNG
VTPGTSKDLKVIAGPISASFTPFDHKVVIHRGLVYNYDFPEYGAMKPGAFGDIQATSLTSKDLIASTDIRLLKPS
AKNVHVPYTQASSGFEMWKNNSGRPLQETAPFGCKIAVNPLRAVDCSYGNIPISIDIPNAAFIR-----------
---------------------------------------------------------------------------
----------------*

>P1;1Z8YF
sequence:1Z8YF:    7: :   89: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------------------------------------------------
CEVSECTYSADFGGMATLQYVSDREGQCPVHSHSSTATLQESTVHVLEKGAVTVHFSTASPQANFIVSLCGKKTT
CNAECKPP--------*

>P1;1Z8YG
sequence:1Z8YG:    1: :  289: :::-1.00:-1.00
YEHATTVPNVPQIPYKALVERAGYAPLNLEITVMSSEVLPSTNQEYITCKFTTVVPSPKIKCCGSLECQPAAHAD
YTCKVFGGVYPFMWGGAQCFCDSENSQMSEAYVELSADCASDHAQAIKVHTAAMKVGLRIVYGNTTSFLDVYVNG
VTPGTSKDLKVIAGPISASFTPFDHKVVIHRGLVYNYDFPEYGAMKPGAFGDIQATSLTSKDLIASTDIRLLKPS
AKNVHVPYTQASSGFEMWKNNSGRPLQETAPFGCKIAVNPLRAVDCSYGNIPISIDIPNAAFIR-----------
---------------------------------------------------------------------------
----------------*

>P1;1Z8YH
sequence:1Z8YH:    7: :   89: :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------------------------------------------------
CEVSECTYSADFGGMATLQYVSDREGQCPVHSHSSTATLQESTVHVLEKGAVTVHFSTASPQANFIVSLCGKKTT
CNAECKPP--------*

>P1;2XFBA
sequence:2XFBA:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKNLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVTAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNMPISIDIPEAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHPPKDHIVNY-*

>P1;2XFBD
sequence:2XFBD:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKNLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVTAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNMPISIDIPEAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHPPKDHIVNY-*

>P1;2XFBF
sequence:2XFBF:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKNLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVTAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNMPISIDIPEAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHPPKDHIVNY-*

>P1;2XFBH
sequence:2XFBH:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKNLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVTAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNMPISIDIPEAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHPPKDHIVNY-*

>P1;2XFCA
sequence:2XFCA:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKNLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVTAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNMPISIDIPEAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHPPKDHIVNY-*

>P1;2XFCD
sequence:2XFCD:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKNLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVTAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNMPISIDIPEAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHPPKDHIVNY-*

>P1;2XFCF
sequence:2XFCF:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKNLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVTAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNMPISIDIPEAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHPPKDHIVNY-*

>P1;2XFCH
sequence:2XFCH:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKNLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVTAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNMPISIDIPEAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHPPKDHIVNY-*

>P1;2YEWB
sequence:2YEWB:    1: :  380: :::-1.00:-1.00
YE-STTMPNQVGIPFKALIERPGYAGLPLSLVVIKSELVPSLVQDYITCNYKTVVPSPYIKCCGGAECS-KNEAD
YKCSVFTGVYPFMWGGAYCFCDTENSQMSEVYVTRGESCEAD-AIAYQV-TASLKAQVMISIGELNQTVDVFVNG
DSPARIQQSKFILGPISSAWSPFD-KVIVYRDEVYNEDYAPYGSGQAGRFGDIQSRTVNSTDVYANTNLKLKRPA
SGNV-VPYTQTPSGFSYWKKEKGVPLNRNAPFGCIIKVNPVRAENCVYGNIPISMDIAD-AFTRIDESPSVSLKA
CEVQSCTYSSDFGGVASISYTSNKVGKCAISSNS--ATMKDSVQDVQESGALSLFFATSSVEPNFVVQVCNARIT
C-GKCEPPKD-IVPYA*

>P1;2YEWE
sequence:2YEWE:    1: :  380: :::-1.00:-1.00
YE-STTMPNQVGIPFKALIERPGYAGLPLSLVVIKSELVPSLVQDYITCNYKTVVPSPYIKCCGGAECS-KNEAD
YKCSVFTGVYPFMWGGAYCFCDTENSQMSEVYVTRGESCEAD-AIAYQV-TASLKAQVMISIGELNQTVDVFVNG
DSPARIQQSKFILGPISSAWSPFD-KVIVYRDEVYNEDYAPYGSGQAGRFGDIQSRTVNSTDVYANTNLKLKRPA
SGNV-VPYTQTPSGFSYWKKEKGVPLNRNAPFGCIIKVNPVRAENCVYGNIPISMDIAD-AFTRIDESPSVSLKA
CEVQSCTYSSDFGGVASISYTSNKVGKCAISSNS--ATMKDSVQDVQESGALSLFFATSSVEPNFVVQVCNARIT
C-GKCEPPKD-IVPYA*

>P1;2YEWH
sequence:2YEWH:    1: :  380: :::-1.00:-1.00
YE-STTMPNQVGIPFKALIERPGYAGLPLSLVVIKSELVPSLVQDYITCNYKTVVPSPYIKCCGGAECS-KNEAD
YKCSVFTGVYPFMWGGAYCFCDTENSQMSEVYVTRGESCEAD-AIAYQV-TASLKAQVMISIGELNQTVDVFVNG
DSPARIQQSKFILGPISSAWSPFD-KVIVYRDEVYNEDYAPYGSGQAGRFGDIQSRTVNSTDVYANTNLKLKRPA
SGNV-VPYTQTPSGFSYWKKEKGVPLNRNAPFGCIIKVNPVRAENCVYGNIPISMDIAD-AFTRIDESPSVSLKA
CEVQSCTYSSDFGGVASISYTSNKVGKCAISSNS--ATMKDSVQDVQESGALSLFFATSSVEPNFVVQVCNARIT
C-GKCEPPKD-IVPYA*

>P1;2YEWK
sequence:2YEWK:    1: :  380: :::-1.00:-1.00
YE-STTMPNQVGIPFKALIERPGYAGLPLSLVVIKSELVPSLVQDYITCNYKTVVPSPYIKCCGGAECS-KNEAD
YKCSVFTGVYPFMWGGAYCFCDTENSQMSEVYVTRGESCEAD-AIAYQV-TASLKAQVMISIGELNQTVDVFVNG
DSPARIQQSKFILGPISSAWSPFD-KVIVYRDEVYNEDYAPYGSGQAGRFGDIQSRTVNSTDVYANTNLKLKRPA
SGNV-VPYTQTPSGFSYWKKEKGVPLNRNAPFGCIIKVNPVRAENCVYGNIPISMDIAD-AFTRIDESPSVSLKA
CEVQSCTYSSDFGGVASISYTSNKVGKCAISSNS--ATMKDSVQDVQESGALSLFFATSSVEPNFVVQVCNARIT
C-GKCEPPKD-IVPYA*

>P1;3J0CA
sequence:3J0CA:    1: :  390: :::-1.00:-1.00
YEHATTMPSQAGISYNTIVNRAGYAPLPISITPTKIKLIPTVNLEYVTCHYKTGMDSPAIKCCGSQECTPTYRPD
EQCKVFTGVYPFMWGGAYCFCDTENTQVSKAYVMKSDDCLADHAEAYKAHTASVQAFLNITVGEHSIVTTVYVNG
ETPVNFNGVKITAGPLSTAWTPFDRKIVQYAGEIYNYDFPEYGAGQPGAFGDIQSRTVSSSDLYANTNLVLQRPK
AGAIHVPYTQAPSGFEQWKKDKAPSLKFTAPFGCEIYTNPIRAENCAVGSIPLAFDIPDALFTRVSETPTLSAAE
CTLNECVYSSDFGGIATVKYSASKSGKCAVHVPSGTATLKEAAVELTEQGSATIHFSTANIHPEFRLQICTSYVT
CKGDCHPPKDHIVTH-*

>P1;3J0CD
sequence:3J0CD:    1: :  390: :::-1.00:-1.00
YEHATTMPSQAGISYNTIVNRAGYAPLPISITPTKIKLIPTVNLEYVTCHYKTGMDSPAIKCCGSQECTPTYRPD
EQCKVFTGVYPFMWGGAYCFCDTENTQVSKAYVMKSDDCLADHAEAYKAHTASVQAFLNITVGEHSIVTTVYVNG
ETPVNFNGVKITAGPLSTAWTPFDRKIVQYAGEIYNYDFPEYGAGQPGAFGDIQSRTVSSSDLYANTNLVLQRPK
AGAIHVPYTQAPSGFEQWKKDKAPSLKFTAPFGCEIYTNPIRAENCAVGSIPLAFDIPDALFTRVSETPTLSAAE
CTLNECVYSSDFGGIATVKYSASKSGKCAVHVPSGTATLKEAAVELTEQGSATIHFSTANIHPEFRLQICTSYVT
CKGDCHPPKDHIVTH-*

>P1;3J0CG
sequence:3J0CG:    1: :  390: :::-1.00:-1.00
YEHATTMPSQAGISYNTIVNRAGYAPLPISITPTKIKLIPTVNLEYVTCHYKTGMDSPAIKCCGSQECTPTYRPD
EQCKVFTGVYPFMWGGAYCFCDTENTQVSKAYVMKSDDCLADHAEAYKAHTASVQAFLNITVGEHSIVTTVYVNG
ETPVNFNGVKITAGPLSTAWTPFDRKIVQYAGEIYNYDFPEYGAGQPGAFGDIQSRTVSSSDLYANTNLVLQRPK
AGAIHVPYTQAPSGFEQWKKDKAPSLKFTAPFGCEIYTNPIRAENCAVGSIPLAFDIPDALFTRVSETPTLSAAE
CTLNECVYSSDFGGIATVKYSASKSGKCAVHVPSGTATLKEAAVELTEQGSATIHFSTANIHPEFRLQICTSYVT
CKGDCHPPKDHIVTH-*

>P1;3J0CJ
sequence:3J0CJ:    1: :  390: :::-1.00:-1.00
YEHATTMPSQAGISYNTIVNRAGYAPLPISITPTKIKLIPTVNLEYVTCHYKTGMDSPAIKCCGSQECTPTYRPD
EQCKVFTGVYPFMWGGAYCFCDTENTQVSKAYVMKSDDCLADHAEAYKAHTASVQAFLNITVGEHSIVTTVYVNG
ETPVNFNGVKITAGPLSTAWTPFDRKIVQYAGEIYNYDFPEYGAGQPGAFGDIQSRTVSSSDLYANTNLVLQRPK
AGAIHVPYTQAPSGFEQWKKDKAPSLKFTAPFGCEIYTNPIRAENCAVGSIPLAFDIPDALFTRVSETPTLSAAE
CTLNECVYSSDFGGIATVKYSASKSGKCAVHVPSGTATLKEAAVELTEQGSATIHFSTANIHPEFRLQICTSYVT
CKGDCHPPKDHIVTH-*

>P1;3J2WA
sequence:3J2WA:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKNLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVTAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNMPISIDIPEAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHPPKDHIVNY-*

>P1;3J2WB
sequence:3J2WB:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKNLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVTAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNMPISIDIPEAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHPPKDHIVNY-*

>P1;3J2WC
sequence:3J2WC:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKNLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVTAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNMPISIDIPEAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHPPKDHIVNY-*

>P1;3J2WD
sequence:3J2WD:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKNLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVTAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNMPISIDIPEAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHPPKDHIVNY-*

>P1;3MUUA
sequence:3MUUA:  241: :  613: :::-1.00:-1.00
YEHATTVPNVPQIPYKALVERAGYAPLNLEI-TVSSEVLPSTNQEYITCKFTTVVPSPKIKCCGSLECQPAAHAG
YTCKVFGGVYPF-WGGAQCFCDSENSQ-SEAYVELSADCASDHAQAIKVHTAA-KVGLRIVYGNTTSFLDVYVNG
VTPGTSKDLKVIAGPISASFTPFDHKVVIHRGLVYNYDFPEYGA-KPGAFGDIQATSLTSKDLIASTDIRLLKPS
AKNVHVPYTQASSGFE-WKNNSGRPLQETAPFGCKIAVNPLRAVDCSYGNIPISIDIPNAAFIRTSDAPLVSTVK
CEVSECTYSADFGGA-TLQYVSDREGQCPVHSHSSTATLQESTVHVLEKGAVTVHFSTASPQANFIVSLCGKKTT
CNAEC-----------*

>P1;3MUUB
sequence:3MUUB:  240: :  612: :::-1.00:-1.00
YEHATTVPNVPQIPYKALVERAGYAPLNLEI-TVSSEVLPSTNQEYITCKFTTVVPSPKIKCCGSLECQPAAHAG
YTCKVFGGVYPF-WGGAQCFCDSENSQ-SEAYVELSADCASDHAQAIKVHTAA-KVGLRIVYGNTTSFLDVYVNG
VTPGTSKDLKVIAGPISASFTPFDHKVVIHRGLVYNYDFPEYGA-KPGAFGDIQATSLTSKDLIASTDIRLLKPS
AKNVHVPYTQASSGFE-WKNNSGRPLQETAPFGCKIAVNPLRAVDCSYGNIPISIDIPNAAFIRTSDAPLVSTVK
CEVSECTYSADFGGA-TLQYVSDREGQCPVHSHSSTATLQESTVHVLEKGAVTVHFSTASPQANFIVSLCGKKTT
CNAEC-----------*

>P1;3MUUC
sequence:3MUUC:  240: :  612: :::-1.00:-1.00
YEHATTVPNVPQIPYKALVERAGYAPLNLEI-TVSSEVLPSTNQEYITCKFTTVVPSPKIKCCGSLECQPAAHAG
YTCKVFGGVYPF-WGGAQCFCDSENSQ-SEAYVELSADCASDHAQAIKVHTAA-KVGLRIVYGNTTSFLDVYVNG
VTPGTSKDLKVIAGPISASFTPFDHKVVIHRGLVYNYDFPEYGA-KPGAFGDIQATSLTSKDLIASTDIRLLKPS
AKNVHVPYTQASSGFE-WKNNSGRPLQETAPFGCKIAVNPLRAVDCSYGNIPISIDIPNAAFIRTSDAPLVSTVK
CEVSECTYSADFGGA-TLQYVSDREGQCPVHSHSSTATLQESTVHVLEKGAVTVHFSTASPQANFIVSLCGKKTT
CNAEC-----------*

>P1;3N40F
sequence:3N40F:    3: :  392: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKNLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVTAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNMPISIDIPEAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHPPKDHIVNY-*

>P1;3N41F
sequence:3N41F:    2: :  381: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKNLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVTAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNMPISIDIPEAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAEC-----------*

>P1;3N42F
sequence:3N42F:    3: :  392: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKNLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVTAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNMPISIDIPEAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHPPKDHIVNY-*

>P1;3N43F
sequence:3N43F:    3: :  392: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKNLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVTAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNMPISIDIPEAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHPPKDHIVNY-*

>P1;3N44F
sequence:3N44F:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKNLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVTAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNMPISIDIPEAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHPPKDHIVNY-*

>P1;5ANYA
sequence:5ANYA:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKNLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVTAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNMPISIDIPEAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHPPKDHIVNY-*

>P1;5ANYC
sequence:5ANYC:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKNLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVTAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNMPISIDIPEAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHPPKDHIVNY-*

>P1;5ANYE
sequence:5ANYE:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKNLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVTAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNMPISIDIPEAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHPPKDHIVNY-*

>P1;5ANYG
sequence:5ANYG:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKNLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVTAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNMPISIDIPEAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHPPKDHIVNY-*

>P1;5VU2M
sequence:5VU2M:    1: :  382: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKNLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVTAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNMPISIDIPEAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHP---------*

>P1;5VU2N
sequence:5VU2N:    1: :  382: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKNLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVTAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNMPISIDIPEAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHP---------*

>P1;5VU2O
sequence:5VU2O:    1: :  382: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKNLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVTAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNMPISIDIPEAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHP---------*

>P1;5VU2P
sequence:5VU2P:    1: :  382: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKNLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVTAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNMPISIDIPEAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHP---------*

>P1;6IMMN
sequence:6IMMN:    1: :  376: :::-1.00:-1.00
FEHATTVPNVPRIPYKALVERAGYAPLNLEITVMSSELIPSTNLEYVTCKYTTVVPSPKVKCCGTLECSSARHAD
YNCKVFGGVYP------------ENSQMSEAYVEFSADCAADHAQAVKVHTAALKAGLRIVYGNTTSMLDVYVNG
VTPGTSKDLKVIAGPISAAYTPFDHKVIIHKGKVYNYDFPEYGAMKPGAFGDIQATSLTSNDLIANTDIRLLKPS
AKNVHVPYTQAASGFEMWKNNSGRPLQETAPFGCQIAVNPLRAVDCAYGNIPISLDIPNAAFVRVSDAPLVTALK
CEVGECVYSADFGGIATLQYSSDREGQCSVHSHSSTATLQESTVHVLQKGGATIHFSTASPQANFIVSLCGKKTT
CNAECKPPADHIV---*

>P1;6IMMT
sequence:6IMMT:    1: :  376: :::-1.00:-1.00
FEHATTVPNVPRIPYKALVERAGYAPLNLEITVMSSELIPSTNLEYVTCKYTTVVPSPKVKCCGTLECSSARHAD
YNCKVFGGVYP------------ENSQMSEAYVEFSADCAADHAQAVKVHTAALKAGLRIVYGNTTSMLDVYVNG
VTPGTSKDLKVIAGPISAAYTPFDHKVIIHKGKVYNYDFPEYGAMKPGAFGDIQATSLTSNDLIANTDIRLLKPS
AKNVHVPYTQAASGFEMWKNNSGRPLQETAPFGCQIAVNPLRAVDCAYGNIPISLDIPNAAFVRVSDAPLVTALK
CEVGECVYSADFGGIATLQYSSDREGQCSVHSHSSTATLQESTVHVLQKGGATIHFSTASPQANFIVSLCGKKTT
CNAECKPPADHIV---*

>P1;6IMMZ
sequence:6IMMZ:    1: :  376: :::-1.00:-1.00
FEHATTVPNVPRIPYKALVERAGYAPLNLEITVMSSELIPSTNLEYVTCKYTTVVPSPKVKCCGTLECSSARHAD
YNCKVFGGVYP------------ENSQMSEAYVEFSADCAADHAQAVKVHTAALKAGLRIVYGNTTSMLDVYVNG
VTPGTSKDLKVIAGPISAAYTPFDHKVIIHKGKVYNYDFPEYGAMKPGAFGDIQATSLTSNDLIANTDIRLLKPS
AKNVHVPYTQAASGFEMWKNNSGRPLQETAPFGCQIAVNPLRAVDCAYGNIPISLDIPNAAFVRVSDAPLVTALK
CEVGECVYSADFGGIATLQYSSDREGQCSVHSHSSTATLQESTVHVLQKGGATIHFSTASPQANFIVSLCGKKTT
CNAECKPPADHIV---*

>P1;6IMMa
sequence:6IMMa:    1: :  376: :::-1.00:-1.00
FEHATTVPNVPRIPYKALVERAGYAPLNLEITVMSSELIPSTNLEYVTCKYTTVVPSPKVKCCGTLECSSARHAD
YNCKVFGGVYP------------ENSQMSEAYVEFSADCAADHAQAVKVHTAALKAGLRIVYGNTTSMLDVYVNG
VTPGTSKDLKVIAGPISAAYTPFDHKVIIHKGKVYNYDFPEYGAMKPGAFGDIQATSLTSNDLIANTDIRLLKPS
AKNVHVPYTQAASGFEMWKNNSGRPLQETAPFGCQIAVNPLRAVDCAYGNIPISLDIPNAAFVRVSDAPLVTALK
CEVGECVYSADFGGIATLQYSSDREGQCSVHSHSSTATLQESTVHVLQKGGATIHFSTASPQANFIVSLCGKKTT
CNAECKPPADHIV---*

>P1;6JO8B
sequence:6JO8B:    3: :  392: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKNLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVTAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNMPISIDIPEAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHPPKDHIVNY-*

>P1;6MUIA
sequence:6MUIA:    1: :  391: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFTGVYPFMWGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQAPSGFERWKRDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYASDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKDHIVDY-*

>P1;6MUIE
sequence:6MUIE:    1: :  391: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFTGVYPFMWGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQAPSGFERWKRDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYASDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKDHIVDY-*

>P1;6MUII
sequence:6MUII:    1: :  391: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFTGVYPFMWGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQAPSGFERWKRDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYASDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKDHIVDY-*

>P1;6MUIM
sequence:6MUIM:    1: :  391: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFTGVYPFMWGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQAPSGFERWKRDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYASDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKDHIVDY-*

>P1;6MW9A
sequence:6MW9A:    1: :  391: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFTGVYPFMWGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQAPSGFERWKRDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYASDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKDHIVDY-*

>P1;6MW9E
sequence:6MW9E:    1: :  391: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFTGVYPFMWGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQAPSGFERWKRDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYASDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKDHIVDY-*

>P1;6MW9I
sequence:6MW9I:    1: :  391: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFTGVYPFMWGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQAPSGFERWKRDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYASDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKDHIVDY-*

>P1;6MW9M
sequence:6MW9M:    1: :  391: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFTGVYPFMWGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQAPSGFERWKRDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYASDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKDHIVDY-*

>P1;6MWCA
sequence:6MWCA:    1: :  391: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFTGVYPFMWGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQAPSGFERWKRDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYASDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKDHIVDY-*

>P1;6MWCE
sequence:6MWCE:    1: :  391: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFTGVYPFMWGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQAPSGFERWKRDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYASDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKDHIVDY-*

>P1;6MWCI
sequence:6MWCI:    1: :  391: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFTGVYPFMWGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQAPSGFERWKRDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYASDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKDHIVDY-*

>P1;6MWCM
sequence:6MWCM:    1: :  391: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFTGVYPFMWGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQAPSGFERWKRDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYASDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKDHIVDY-*

>P1;6MWVA
sequence:6MWVA:    1: :  391: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFTGVYPFMWGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQAPSGFERWKRDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYASDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKDHIVDY-*

>P1;6MWVE
sequence:6MWVE:    1: :  391: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFTGVYPFMWGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQAPSGFERWKRDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYASDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKDHIVDY-*

>P1;6MWVI
sequence:6MWVI:    1: :  391: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFTGVYPFMWGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQAPSGFERWKRDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYASDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKDHIVDY-*

>P1;6MWVM
sequence:6MWVM:    1: :  391: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFTGVYPFMWGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQAPSGFERWKRDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYASDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKDHIVDY-*

>P1;6MWXA
sequence:6MWXA:    1: :  391: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFTGVYPFMWGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQAPSGFERWKRDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYASDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKDHIVDY-*

>P1;6MWXE
sequence:6MWXE:    1: :  391: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFTGVYPFMWGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQAPSGFERWKRDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYASDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKDHIVDY-*

>P1;6MWXI
sequence:6MWXI:    1: :  391: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFTGVYPFMWGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQAPSGFERWKRDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYASDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKDHIVDY-*

>P1;6MWXM
sequence:6MWXM:    1: :  391: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFTGVYPFMWGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQAPSGFERWKRDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYASDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKDHIVDY-*

>P1;6MX4A
sequence:6MX4A:    1: :  391: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFTGVYPFMWGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQAPSGFERWKRDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYASDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKDHIVDY-*

>P1;6MX4D
sequence:6MX4D:    1: :  391: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFTGVYPFMWGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQAPSGFERWKRDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYASDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKDHIVDY-*

>P1;6MX4G
sequence:6MX4G:    1: :  391: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFTGVYPFMWGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQAPSGFERWKRDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYASDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKDHIVDY-*

>P1;6MX4J
sequence:6MX4J:    1: :  391: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFTGVYPFMWGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQAPSGFERWKRDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYASDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKDHIVDY-*

>P1;6NK5A
sequence:6NK5A:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELQSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKSLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVAAYANG
DHAVTVKDAKFVVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNIPISIDIPDAAFTRVVDAPSVTDMS
CEVPACTHSSDFGGVAIIKYTASKKGKCAVHSMTNAVTIREADVEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAACHPPKDHIVNY-*

>P1;6NK5B
sequence:6NK5B:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELQSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKSLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVAAYANG
DHAVTVKDAKFVVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNIPISIDIPDAAFTRVVDAPSVTDMS
CEVPACTHSSDFGGVAIIKYTASKKGKCAVHSMTNAVTIREADVEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAACHPPKDHIVNY-*

>P1;6NK5C
sequence:6NK5C:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELQSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKSLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVAAYANG
DHAVTVKDAKFVVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNIPISIDIPDAAFTRVVDAPSVTDMS
CEVPACTHSSDFGGVAIIKYTASKKGKCAVHSMTNAVTIREADVEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAACHPPKDHIVNY-*

>P1;6NK5D
sequence:6NK5D:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELQSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKSLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVAAYANG
DHAVTVKDAKFVVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNIPISIDIPDAAFTRVVDAPSVTDMS
CEVPACTHSSDFGGVAIIKYTASKKGKCAVHSMTNAVTIREADVEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAACHPPKDHIVNY-*

>P1;6NK6A
sequence:6NK6A:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELQSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKSLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVAAYANG
DHAVTVKDAKFVVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNIPISIDIPDAAFTRVVDAPSVTDMS
CEVPACTHSSDFGGVAIIKYTASKKGKCAVHSMTNAVTIREADVEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAACHPPKDHIVNY-*

>P1;6NK6B
sequence:6NK6B:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELQSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKSLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVAAYANG
DHAVTVKDAKFVVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNIPISIDIPDAAFTRVVDAPSVTDMS
CEVPACTHSSDFGGVAIIKYTASKKGKCAVHSMTNAVTIREADVEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAACHPPKDHIVNY-*

>P1;6NK6C
sequence:6NK6C:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELQSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKSLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVAAYANG
DHAVTVKDAKFVVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNIPISIDIPDAAFTRVVDAPSVTDMS
CEVPACTHSSDFGGVAIIKYTASKKGKCAVHSMTNAVTIREADVEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAACHPPKDHIVNY-*

>P1;6NK6D
sequence:6NK6D:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELQSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKSLPD
YSCKVFTGVYPFMWGGAYCFCDAENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNITVAAYANG
DHAVTVKDAKFVVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESKDVYANTQLVLQRPA
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAVNCAVGNIPISIDIPDAAFTRVVDAPSVTDMS
CEVPACTHSSDFGGVAIIKYTASKKGKCAVHSMTNAVTIREADVEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAACHPPKDHIVNY-*

>P1;6NK7A
sequence:6NK7A:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKSLPD
YSCKVFTGVYPFMWGGAYCFCDTENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNVTVSAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESEDVYANTQLVLQRPS
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAMNCAVGNMPISIDIPDAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHPPKDHIVNY-*

>P1;6NK7B
sequence:6NK7B:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKSLPD
YSCKVFTGVYPFMWGGAYCFCDTENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNVTVSAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESEDVYANTQLVLQRPS
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAMNCAVGNMPISIDIPDAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHPPKDHIVNY-*

>P1;6NK7C
sequence:6NK7C:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKSLPD
YSCKVFTGVYPFMWGGAYCFCDTENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNVTVSAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESEDVYANTQLVLQRPS
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAMNCAVGNMPISIDIPDAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHPPKDHIVNY-*

>P1;6NK7D
sequence:6NK7D:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKSLPD
YSCKVFTGVYPFMWGGAYCFCDTENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNVTVSAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESEDVYANTQLVLQRPS
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAMNCAVGNMPISIDIPDAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHPPKDHIVNY-*

>P1;6ODFA
sequence:6ODFA:    1: :  391: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFTGVYPFMWGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQAPSGFERWKRDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYASDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKDHIVDY-*

>P1;6ODFC
sequence:6ODFC:    1: :  391: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFTGVYPFMWGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQAPSGFERWKRDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYASDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKDHIVDY-*

>P1;6ODFE
sequence:6ODFE:    1: :  391: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFTGVYPFMWGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQAPSGFERWKRDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYASDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKDHIVDY-*

>P1;6ODFG
sequence:6ODFG:    1: :  391: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFTGVYPFMWGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQAPSGFERWKRDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYASDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKDHIVDY-*

>P1;6VYVA
sequence:6VYVA:    1: :  390: :::-1.00:-1.00
YEHTATIPNVVGFPYKAHIERNGFSPMTLQLEVVETSWEPTLNLEYITCEYKTVVPSPFIKCCGTSECSSKEQPD
YQCKVYTGVYPFMWGGAYCFCDSENTQLSEAYVDRSDVCKHDHASAYKAHTASLKATIRISYGTINQTTEAFVNG
EHAVNVGGSKFIFGPISTAWSPFDNKIVVYKDDVYNQDFPPYGSGQPGRFGDIQSRTVESKDLYANTALKLSRPS
PGVVHVPYTPTPSGFKYWLKEKGSSLNTKAPFGCKIKTNPVRAMDCAVGSIPVSMDIPDSAFTRVVDAPAVTDLS
CQVVVCTHSSDFGGVATLSYKTDKPGKCAVHSHSNVATLQEATVDVKEDGKVTVHFSTASASPAFKVSVCDAKTT
CTAACEPPKDHIVPY-*

>P1;6VYVB
sequence:6VYVB:    1: :  390: :::-1.00:-1.00
YEHTATIPNVVGFPYKAHIERNGFSPMTLQLEVVETSWEPTLNLEYITCEYKTVVPSPFIKCCGTSECSSKEQPD
YQCKVYTGVYPFMWGGAYCFCDSENTQLSEAYVDRSDVCKHDHASAYKAHTASLKATIRISYGTINQTTEAFVNG
EHAVNVGGSKFIFGPISTAWSPFDNKIVVYKDDVYNQDFPPYGSGQPGRFGDIQSRTVESKDLYANTALKLSRPS
PGVVHVPYTPTPSGFKYWLKEKGSSLNTKAPFGCKIKTNPVRAMDCAVGSIPVSMDIPDSAFTRVVDAPAVTDLS
CQVVVCTHSSDFGGVATLSYKTDKPGKCAVHSHSNVATLQEATVDVKEDGKVTVHFSTASASPAFKVSVCDAKTT
CTAACEPPKDHIVPY-*

>P1;6VYVC
sequence:6VYVC:    1: :  390: :::-1.00:-1.00
YEHTATIPNVVGFPYKAHIERNGFSPMTLQLEVVETSWEPTLNLEYITCEYKTVVPSPFIKCCGTSECSSKEQPD
YQCKVYTGVYPFMWGGAYCFCDSENTQLSEAYVDRSDVCKHDHASAYKAHTASLKATIRISYGTINQTTEAFVNG
EHAVNVGGSKFIFGPISTAWSPFDNKIVVYKDDVYNQDFPPYGSGQPGRFGDIQSRTVESKDLYANTALKLSRPS
PGVVHVPYTPTPSGFKYWLKEKGSSLNTKAPFGCKIKTNPVRAMDCAVGSIPVSMDIPDSAFTRVVDAPAVTDLS
CQVVVCTHSSDFGGVATLSYKTDKPGKCAVHSHSNVATLQEATVDVKEDGKVTVHFSTASASPAFKVSVCDAKTT
CTAACEPPKDHIVPY-*

>P1;6VYVD
sequence:6VYVD:    1: :  390: :::-1.00:-1.00
YEHTATIPNVVGFPYKAHIERNGFSPMTLQLEVVETSWEPTLNLEYITCEYKTVVPSPFIKCCGTSECSSKEQPD
YQCKVYTGVYPFMWGGAYCFCDSENTQLSEAYVDRSDVCKHDHASAYKAHTASLKATIRISYGTINQTTEAFVNG
EHAVNVGGSKFIFGPISTAWSPFDNKIVVYKDDVYNQDFPPYGSGQPGRFGDIQSRTVESKDLYANTALKLSRPS
PGVVHVPYTPTPSGFKYWLKEKGSSLNTKAPFGCKIKTNPVRAMDCAVGSIPVSMDIPDSAFTRVVDAPAVTDLS
CQVVVCTHSSDFGGVATLSYKTDKPGKCAVHSHSNVATLQEATVDVKEDGKVTVHFSTASASPAFKVSVCDAKTT
CTAACEPPKDHIVPY-*

>P1;6W09A
sequence:6W09A:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKSLPD
YSCKVFTGVYPFMWGGAYCFCDTENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNVTVSAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESEDVYANTQLVLQRPS
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAMNCAVGNMPISIDIPDAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHPPKDHIVNY-*

>P1;6W09B
sequence:6W09B:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKSLPD
YSCKVFTGVYPFMWGGAYCFCDTENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNVTVSAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESEDVYANTQLVLQRPS
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAMNCAVGNMPISIDIPDAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHPPKDHIVNY-*

>P1;6W09C
sequence:6W09C:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKSLPD
YSCKVFTGVYPFMWGGAYCFCDTENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNVTVSAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESEDVYANTQLVLQRPS
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAMNCAVGNMPISIDIPDAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHPPKDHIVNY-*

>P1;6W09D
sequence:6W09D:    1: :  390: :::-1.00:-1.00
YEHVTVIPNTVGVPYKTLVNRPGYSPMVLEMELLSVTLEPTLSLDYITCEYKTVIPSPYVKCCGTAECKDKSLPD
YSCKVFTGVYPFMWGGAYCFCDTENTQLSEAHVEKSESCKTEFASAYRAHTASASAKLRVLYQGNNVTVSAYANG
DHAVTVKDAKFIVGPMSSAWTPFDNKIVVYKGDVYNMDYPPFGAGRPGQFGDIQSRTPESEDVYANTQLVLQRPS
AGTVHVPYSQAPSGFKYWLKERGASLQHTAPFGCQIATNPVRAMNCAVGNMPISIDIPDAAFTRVVDAPSLTDMS
CEVPACTHSSDFGGVAIIKYAASKKGKCAVHSMTNAVTIREAEIEVEGNSQLQISFSTALASAEFRVQVCSTQVH
CAAECHPPKDHIVNY-*

>P1;6W1CA
sequence:6W1CA:    1: :  380: :::-1.00:-1.00
YEHTAIIPNQVGFPYKAHVAREGYSPLTLQMQVIETSLEPTLNLEYITCDYKTKVPSPYVKCCGTAECRTQDKPE
YKCAVFTGVYPFMWGGAYCFCDSENTQMSEAYVERADVCKHDHAAAYRAHTASLRAKIKVTYGTVNQTVEAYVNG
DHAVTIAGTKFIFGPVSTPWTPFDTKILVYKGELYNQDFPRYGAGQPGRFGDIQSRTLDSRDLYANTGLKLARPA
AGNIHVPYTQTPSGFKTWQKDRDSPLNAKAPFGCIIQTNPVRAMNCAVGNIPVSMDIADSAFTRLTDAPVISELT
CTVSTCTHSSDFGGIAVLSYKVEKSGRCDIHSHSNVAVLQEVS--IETEGRSVIHFSTASASPSFVVSVCSSRAT
CTAKCEP---------*

>P1;6W1CB
sequence:6W1CB:    1: :  380: :::-1.00:-1.00
YEHTAIIPNQVGFPYKAHVAREGYSPLTLQMQVIETSLEPTLNLEYITCDYKTKVPSPYVKCCGTAECRTQDKPE
YKCAVFTGVYPFMWGGAYCFCDSENTQMSEAYVERADVCKHDHAAAYRAHTASLRAKIKVTYGTVNQTVEAYVNG
DHAVTIAGTKFIFGPVSTPWTPFDTKILVYKGELYNQDFPRYGAGQPGRFGDIQSRTLDSRDLYANTGLKLARPA
AGNIHVPYTQTPSGFKTWQKDRDSPLNAKAPFGCIIQTNPVRAMNCAVGNIPVSMDIADSAFTRLTDAPVISELT
CTVSTCTHSSDFGGIAVLSYKVEKSGRCDIHSHSNVAVLQEVS--IETEGRSVIHFSTASASPSFVVSVCSSRAT
CTAKCEP---------*

>P1;6W1CC
sequence:6W1CC:    1: :  380: :::-1.00:-1.00
YEHTAIIPNQVGFPYKAHVAREGYSPLTLQMQVIETSLEPTLNLEYITCDYKTKVPSPYVKCCGTAECRTQDKPE
YKCAVFTGVYPFMWGGAYCFCDSENTQMSEAYVERADVCKHDHAAAYRAHTASLRAKIKVTYGTVNQTVEAYVNG
DHAVTIAGTKFIFGPVSTPWTPFDTKILVYKGELYNQDFPRYGAGQPGRFGDIQSRTLDSRDLYANTGLKLARPA
AGNIHVPYTQTPSGFKTWQKDRDSPLNAKAPFGCIIQTNPVRAMNCAVGNIPVSMDIADSAFTRLTDAPVISELT
CTVSTCTHSSDFGGIAVLSYKVEKSGRCDIHSHSNVAVLQEVS--IETEGRSVIHFSTASASPSFVVSVCSSRAT
CTAKCEP---------*

>P1;6W1CD
sequence:6W1CD:    1: :  380: :::-1.00:-1.00
YEHTAIIPNQVGFPYKAHVAREGYSPLTLQMQVIETSLEPTLNLEYITCDYKTKVPSPYVKCCGTAECRTQDKPE
YKCAVFTGVYPFMWGGAYCFCDSENTQMSEAYVERADVCKHDHAAAYRAHTASLRAKIKVTYGTVNQTVEAYVNG
DHAVTIAGTKFIFGPVSTPWTPFDTKILVYKGELYNQDFPRYGAGQPGRFGDIQSRTLDSRDLYANTGLKLARPA
AGNIHVPYTQTPSGFKTWQKDRDSPLNAKAPFGCIIQTNPVRAMNCAVGNIPVSMDIADSAFTRLTDAPVISELT
CTVSTCTHSSDFGGIAVLSYKVEKSGRCDIHSHSNVAVLQEVS--IETEGRSVIHFSTASASPSFVVSVCSSRAT
CTAKCEP---------*

>P1;6W2UA
sequence:6W2UA:    1: :  380: :::-1.00:-1.00
YEHTAIIPNQVGFPYKAHVAREGYSPLTLQMQVIETSLEPTLNLEYITCDYKTKVPSPYVKCCGTAECRTQDKPE
YKCAVFTGVYPFMWGGAYCFCDSENTQMSEAYVERADVCKHDHAAAYRAHTASLRAKIKVTYGTVNQTVEAYVNG
DHAVTIAGTKFIFGPVSTPWTPFDTKILVYKGELYNQDFPRYGAGQPGRFGDIQSRTLDSRDLYANTGLKLARPA
AGNIHVPYTQTPSGFKTWQKDRDSPLNAKAPFGCIIQTNPVRAMNCAVGNIPVSMDIADSAFTRLTDAPVISELT
CTVSTCTHSSDFGGIAVLSYKVEKSGRCDIHSHSNVAVLQEVS--IETEGRSVIHFSTASASPSFVVSVCSSRAT
CTAKCEP---------*

>P1;6W2UB
sequence:6W2UB:    1: :  380: :::-1.00:-1.00
YEHTAIIPNQVGFPYKAHVAREGYSPLTLQMQVIETSLEPTLNLEYITCDYKTKVPSPYVKCCGTAECRTQDKPE
YKCAVFTGVYPFMWGGAYCFCDSENTQMSEAYVERADVCKHDHAAAYRAHTASLRAKIKVTYGTVNQTVEAYVNG
DHAVTIAGTKFIFGPVSTPWTPFDTKILVYKGELYNQDFPRYGAGQPGRFGDIQSRTLDSRDLYANTGLKLARPA
AGNIHVPYTQTPSGFKTWQKDRDSPLNAKAPFGCIIQTNPVRAMNCAVGNIPVSMDIADSAFTRLTDAPVISELT
CTVSTCTHSSDFGGIAVLSYKVEKSGRCDIHSHSNVAVLQEVS--IETEGRSVIHFSTASASPSFVVSVCSSRAT
CTAKCEP---------*

>P1;6W2UC
sequence:6W2UC:    1: :  380: :::-1.00:-1.00
YEHTAIIPNQVGFPYKAHVAREGYSPLTLQMQVIETSLEPTLNLEYITCDYKTKVPSPYVKCCGTAECRTQDKPE
YKCAVFTGVYPFMWGGAYCFCDSENTQMSEAYVERADVCKHDHAAAYRAHTASLRAKIKVTYGTVNQTVEAYVNG
DHAVTIAGTKFIFGPVSTPWTPFDTKILVYKGELYNQDFPRYGAGQPGRFGDIQSRTLDSRDLYANTGLKLARPA
AGNIHVPYTQTPSGFKTWQKDRDSPLNAKAPFGCIIQTNPVRAMNCAVGNIPVSMDIADSAFTRLTDAPVISELT
CTVSTCTHSSDFGGIAVLSYKVEKSGRCDIHSHSNVAVLQEVS--IETEGRSVIHFSTASASPSFVVSVCSSRAT
CTAKCEP---------*

>P1;6W2UD
sequence:6W2UD:    1: :  380: :::-1.00:-1.00
YEHTAIIPNQVGFPYKAHVAREGYSPLTLQMQVIETSLEPTLNLEYITCDYKTKVPSPYVKCCGTAECRTQDKPE
YKCAVFTGVYPFMWGGAYCFCDSENTQMSEAYVERADVCKHDHAAAYRAHTASLRAKIKVTYGTVNQTVEAYVNG
DHAVTIAGTKFIFGPVSTPWTPFDTKILVYKGELYNQDFPRYGAGQPGRFGDIQSRTLDSRDLYANTGLKLARPA
AGNIHVPYTQTPSGFKTWQKDRDSPLNAKAPFGCIIQTNPVRAMNCAVGNIPVSMDIADSAFTRLTDAPVISELT
CTVSTCTHSSDFGGIAVLSYKVEKSGRCDIHSHSNVAVLQEVS--IETEGRSVIHFSTASASPSFVVSVCSSRAT
CTAKCEP---------*

>P1;6XO4A
sequence:6XO4A:    1: :  387: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFSGVYPFMYGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQVPSGFERWKKDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYAFDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKQH-----*

>P1;6XO4D
sequence:6XO4D:    1: :  387: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFSGVYPFMYGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQVPSGFERWKKDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYAFDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKQH-----*

>P1;6XO4G
sequence:6XO4G:    1: :  387: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFSGVYPFMYGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQVPSGFERWKKDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYAFDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKQH-----*

>P1;6XO4J
sequence:6XO4J:    1: :  387: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFSGVYPFMYGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQVPSGFERWKKDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYAFDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKQH-----*

>P1;6XOBA
sequence:6XOBA:    1: :  387: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFSGVYPFMYGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQVPSGFERWKKDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYAFDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKQH-----*

>P1;6XOBD
sequence:6XOBD:    1: :  387: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFSGVYPFMYGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQVPSGFERWKKDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYAFDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKQH-----*

>P1;6XOBG
sequence:6XOBG:    1: :  387: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFSGVYPFMYGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQVPSGFERWKKDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYAFDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKQH-----*

>P1;6XOBJ
sequence:6XOBJ:    1: :  387: :::-1.00:-1.00
YEHTAVMPNKVGIPYKALVERPGYAPVHLQIQLVNTRIIPSTNLEYITCKYKTKVPSPVVKCCGATQCTSKPHPD
YQCQVFSGVYPFMYGGAYCFCDTENTQMSEAYVERSEECSIDHAKAYKVHTGTVQAMVNITYGSVSRSADVYVNG
ETPAKIGDAKLIIGPLSSAWSPFDNKVVVYGHEVYNYDFPEYGTGKAGSFGDLQSRTSTSNDLYANTNLKLQRPQ
AGIVHTPFTQVPSGFERWKKDKGAPLNDVAPFGCSIALEPLRAENCAVGSIPISIDIPDAAFTRISETPTVSDLE
CKITECTYAFDFGGIATVAYKSSKAGNCPIHSPSGVAVIKENDVTLAESGSFTFHFSTANIHPAFKLQVCTSAVT
CKGDCKPPKQH-----*

>P1;7FFEB
sequence:7FFEB:    1: :  390: :::-1.00:-1.00
YEHATTMPSQAGISYNTIVNRAGYAPLPISITPTKIKLIPTVNLEYVTCHYKTGMDSPAIKCCGSQECTPTYRPD
EQCKVFTGVYPFMWGGAYCFCDTENTQVSKAYVMKSDDCLADHAEAYKAHTASVQAFLNITVGEHSIVTTVYVNG
ETPVNFNGVKITAGPLSTAWTPFDRKIVQYAGEIYNYDFPEYGAGQPGAFGDIQSRTVSSSDLYANTNLVLQRPK
AGAIHVPYTQAPSGFEQWKKDKAPSLKFTAPFGCEIYTNPIRAENCAVGSIPLAFDIPDALFTRVSETPTLSAAE
CTLNECVYSSDFGGIATVKYSASKSGKCAVHVPSGTATLKEAAVELTEQGSATIHFSTANIHPEFRLQICTSYVT
CKGDCHPPKDHIVTH-*

>P1;7FFEC
sequence:7FFEC:    1: :  390: :::-1.00:-1.00
YEHATTMPSQAGISYNTIVNRAGYAPLPISITPTKIKLIPTVNLEYVTCHYKTGMDSPAIKCCGSQECTPTYRPD
EQCKVFTGVYPFMWGGAYCFCDTENTQVSKAYVMKSDDCLADHAEAYKAHTASVQAFLNITVGEHSIVTTVYVNG
ETPVNFNGVKITAGPLSTAWTPFDRKIVQYAGEIYNYDFPEYGAGQPGAFGDIQSRTVSSSDLYANTNLVLQRPK
AGAIHVPYTQAPSGFEQWKKDKAPSLKFTAPFGCEIYTNPIRAENCAVGSIPLAFDIPDALFTRVSETPTLSAAE
CTLNECVYSSDFGGIATVKYSASKSGKCAVHVPSGTATLKEAAVELTEQGSATIHFSTANIHPEFRLQICTSYVT
CKGDCHPPKDHIVTH-*

>P1;7FFEE
sequence:7FFEE:    1: :  390: :::-1.00:-1.00
YEHATTMPSQAGISYNTIVNRAGYAPLPISITPTKIKLIPTVNLEYVTCHYKTGMDSPAIKCCGSQECTPTYRPD
EQCKVFTGVYPFMWGGAYCFCDTENTQVSKAYVMKSDDCLADHAEAYKAHTASVQAFLNITVGEHSIVTTVYVNG
ETPVNFNGVKITAGPLSTAWTPFDRKIVQYAGEIYNYDFPEYGAGQPGAFGDIQSRTVSSSDLYANTNLVLQRPK
AGAIHVPYTQAPSGFEQWKKDKAPSLKFTAPFGCEIYTNPIRAENCAVGSIPLAFDIPDALFTRVSETPTLSAAE
CTLNECVYSSDFGGIATVKYSASKSGKCAVHVPSGTATLKEAAVELTEQGSATIHFSTANIHPEFRLQICTSYVT
CKGDCHPPKDHIVTH-*

>P1;7FFEK
sequence:7FFEK:    1: :  390: :::-1.00:-1.00
YEHATTMPSQAGISYNTIVNRAGYAPLPISITPTKIKLIPTVNLEYVTCHYKTGMDSPAIKCCGSQECTPTYRPD
EQCKVFTGVYPFMWGGAYCFCDTENTQVSKAYVMKSDDCLADHAEAYKAHTASVQAFLNITVGEHSIVTTVYVNG
ETPVNFNGVKITAGPLSTAWTPFDRKIVQYAGEIYNYDFPEYGAGQPGAFGDIQSRTVSSSDLYANTNLVLQRPK
AGAIHVPYTQAPSGFEQWKKDKAPSLKFTAPFGCEIYTNPIRAENCAVGSIPLAFDIPDALFTRVSETPTLSAAE
CTLNECVYSSDFGGIATVKYSASKSGKCAVHVPSGTATLKEAAVELTEQGSATIHFSTANIHPEFRLQICTSYVT
CKGDCHPPKDHIVTH-*

>P1;7FFFC
sequence:7FFFC:    1: :  390: :::-1.00:-1.00
YEHATTMPSQAGISYNTIVNRAGYAPLPISITPTKIKLIPTVNLEYVTCHYKTGMDSPAIKCCGSQECTPTYRPD
EQCKVFTGVYPFMWGGAYCFCDTENTQVSKAYVMKSDDCLADHAEAYKAHTASVQAFLNITVGEHSIVTTVYVNG
ETPVNFNGVKITAGPLSTAWTPFDRKIVQYAGEIYNYDFPEYGAGQPGAFGDIQSRTVSSSDLYANTNLVLQRPK
AGAIHVPYTQAPSGFEQWKKDKAPSLKFTAPFGCEIYTNPIRAENCAVGSIPLAFDIPDALFTRVSETPTLSAAE
CTLNECVYSSDFGGIATVKYSASKSGKCAVHVPSGTATLKEAAVELTEQGSATIHFSTANIHPEFRLQICTSYVT
CKGDCHPPKDHIVTH-*

>P1;7FFFG
sequence:7FFFG:    1: :  390: :::-1.00:-1.00
YEHATTMPSQAGISYNTIVNRAGYAPLPISITPTKIKLIPTVNLEYVTCHYKTGMDSPAIKCCGSQECTPTYRPD
EQCKVFTGVYPFMWGGAYCFCDTENTQVSKAYVMKSDDCLADHAEAYKAHTASVQAFLNITVGEHSIVTTVYVNG
ETPVNFNGVKITAGPLSTAWTPFDRKIVQYAGEIYNYDFPEYGAGQPGAFGDIQSRTVSSSDLYANTNLVLQRPK
AGAIHVPYTQAPSGFEQWKKDKAPSLKFTAPFGCEIYTNPIRAENCAVGSIPLAFDIPDALFTRVSETPTLSAAE
CTLNECVYSSDFGGIATVKYSASKSGKCAVHVPSGTATLKEAAVELTEQGSATIHFSTANIHPEFRLQICTSYVT
CKGDCHPPKDHIVTH-*

>P1;7FFFM
sequence:7FFFM:    1: :  390: :::-1.00:-1.00
YEHATTMPSQAGISYNTIVNRAGYAPLPISITPTKIKLIPTVNLEYVTCHYKTGMDSPAIKCCGSQECTPTYRPD
EQCKVFTGVYPFMWGGAYCFCDTENTQVSKAYVMKSDDCLADHAEAYKAHTASVQAFLNITVGEHSIVTTVYVNG
ETPVNFNGVKITAGPLSTAWTPFDRKIVQYAGEIYNYDFPEYGAGQPGAFGDIQSRTVSSSDLYANTNLVLQRPK
AGAIHVPYTQAPSGFEQWKKDKAPSLKFTAPFGCEIYTNPIRAENCAVGSIPLAFDIPDALFTRVSETPTLSAAE
CTLNECVYSSDFGGIATVKYSASKSGKCAVHVPSGTATLKEAAVELTEQGSATIHFSTANIHPEFRLQICTSYVT
CKGDCHPPKDHIVTH-*

>P1;7FFFT
sequence:7FFFT:    1: :  390: :::-1.00:-1.00
YEHATTMPSQAGISYNTIVNRAGYAPLPISITPTKIKLIPTVNLEYVTCHYKTGMDSPAIKCCGSQECTPTYRPD
EQCKVFTGVYPFMWGGAYCFCDTENTQVSKAYVMKSDDCLADHAEAYKAHTASVQAFLNITVGEHSIVTTVYVNG
ETPVNFNGVKITAGPLSTAWTPFDRKIVQYAGEIYNYDFPEYGAGQPGAFGDIQSRTVSSSDLYANTNLVLQRPK
AGAIHVPYTQAPSGFEQWKKDKAPSLKFTAPFGCEIYTNPIRAENCAVGSIPLAFDIPDALFTRVSETPTLSAAE
CTLNECVYSSDFGGIATVKYSASKSGKCAVHVPSGTATLKEAAVELTEQGSATIHFSTANIHPEFRLQICTSYVT
CKGDCHPPKDHIVTH-*

>P1;7FFLB
sequence:7FFLB:    1: :  390: :::-1.00:-1.00
YEHATTMPSQAGISYNTIVNRAGYAPLPISITPTKIKLIPTVNLEYVTCHYKTGMDSPAIKCCGSQECTPTYRPD
EQCKVFTGVYPFMWGGAYCFCDTENTQVSKAYVMKSDDCLADHAEAYKAHTASVQAFLNITVGEHSIVTTVYVNG
ETPVNFNGVKITAGPLSTAWTPFDRKIVQYAGEIYNYDFPEYGAGQPGAFGDIQSRTVSSSDLYANTNLVLQRPK
AGAIHVPYTQAPSGFEQWKKDKAPSLKFTAPFGCEIYTNPIRAENCAVGSIPLAFDIPDALFTRVSETPTLSAAE
CTLNECVYSSDFGGIATVKYSASKSGKCAVHVPSGTATLKEAAVELTEQGSATIHFSTANIHPEFRLQICTSYVT
CKGDCHPPKDHIVTH-*

>P1;7FFLC
sequence:7FFLC:    1: :  390: :::-1.00:-1.00
YEHATTMPSQAGISYNTIVNRAGYAPLPISITPTKIKLIPTVNLEYVTCHYKTGMDSPAIKCCGSQECTPTYRPD
EQCKVFTGVYPFMWGGAYCFCDTENTQVSKAYVMKSDDCLADHAEAYKAHTASVQAFLNITVGEHSIVTTVYVNG
ETPVNFNGVKITAGPLSTAWTPFDRKIVQYAGEIYNYDFPEYGAGQPGAFGDIQSRTVSSSDLYANTNLVLQRPK
AGAIHVPYTQAPSGFEQWKKDKAPSLKFTAPFGCEIYTNPIRAENCAVGSIPLAFDIPDALFTRVSETPTLSAAE
CTLNECVYSSDFGGIATVKYSASKSGKCAVHVPSGTATLKEAAVELTEQGSATIHFSTANIHPEFRLQICTSYVT
CKGDCHPPKDHIVTH-*

>P1;7FFLG
sequence:7FFLG:    1: :  390: :::-1.00:-1.00
YEHATTMPSQAGISYNTIVNRAGYAPLPISITPTKIKLIPTVNLEYVTCHYKTGMDSPAIKCCGSQECTPTYRPD
EQCKVFTGVYPFMWGGAYCFCDTENTQVSKAYVMKSDDCLADHAEAYKAHTASVQAFLNITVGEHSIVTTVYVNG
ETPVNFNGVKITAGPLSTAWTPFDRKIVQYAGEIYNYDFPEYGAGQPGAFGDIQSRTVSSSDLYANTNLVLQRPK
AGAIHVPYTQAPSGFEQWKKDKAPSLKFTAPFGCEIYTNPIRAENCAVGSIPLAFDIPDALFTRVSETPTLSAAE
CTLNECVYSSDFGGIATVKYSASKSGKCAVHVPSGTATLKEAAVELTEQGSATIHFSTANIHPEFRLQICTSYVT
CKGDCHPPKDHIVTH-*

>P1;7FFQB
sequence:7FFQB:    1: :  390: :::-1.00:-1.00
YEHATTMPSQAGISYNTIVNRAGYAPLPISITPTKIKLIPTVNLEYVTCHYKTGMDSPAIKCCGSQECTPTYRPD
EQCKVFTGVYPFMWGGAYCFCDTENTQVSKAYVMKSDDCLADHAEAYKAHTASVQAFLNITVGEHSIVTTVYVNG
ETPVNFNGVKITAGPLSTAWTPFDRKIVQYAGEIYNYDFPEYGAGQPGAFGDIQSRTVSSSDLYANTNLVLQRPK
AGAIHVPYTQAPSGFEQWKKDKAPSLKFTAPFGCEIYTNPIRAENCAVGSIPLAFDIPDALFTRVSETPTLSAAE
CTLNECVYSSDFGGIATVKYSASKSGKCAVHVPSGTATLKEAAVELTEQGSATIHFSTANIHPEFRLQICTSYVT
CKGDCHPPKDHIVTH-*

>P1;7FFQC
sequence:7FFQC:    1: :  390: :::-1.00:-1.00
YEHATTMPSQAGISYNTIVNRAGYAPLPISITPTKIKLIPTVNLEYVTCHYKTGMDSPAIKCCGSQECTPTYRPD
EQCKVFTGVYPFMWGGAYCFCDTENTQVSKAYVMKSDDCLADHAEAYKAHTASVQAFLNITVGEHSIVTTVYVNG
ETPVNFNGVKITAGPLSTAWTPFDRKIVQYAGEIYNYDFPEYGAGQPGAFGDIQSRTVSSSDLYANTNLVLQRPK
AGAIHVPYTQAPSGFEQWKKDKAPSLKFTAPFGCEIYTNPIRAENCAVGSIPLAFDIPDALFTRVSETPTLSAAE
CTLNECVYSSDFGGIATVKYSASKSGKCAVHVPSGTATLKEAAVELTEQGSATIHFSTANIHPEFRLQICTSYVT
CKGDCHPPKDHIVTH-*

>P1;7FFQE
sequence:7FFQE:    1: :  390: :::-1.00:-1.00
YEHATTMPSQAGISYNTIVNRAGYAPLPISITPTKIKLIPTVNLEYVTCHYKTGMDSPAIKCCGSQECTPTYRPD
EQCKVFTGVYPFMWGGAYCFCDTENTQVSKAYVMKSDDCLADHAEAYKAHTASVQAFLNITVGEHSIVTTVYVNG
ETPVNFNGVKITAGPLSTAWTPFDRKIVQYAGEIYNYDFPEYGAGQPGAFGDIQSRTVSSSDLYANTNLVLQRPK
AGAIHVPYTQAPSGFEQWKKDKAPSLKFTAPFGCEIYTNPIRAENCAVGSIPLAFDIPDALFTRVSETPTLSAAE
CTLNECVYSSDFGGIATVKYSASKSGKCAVHVPSGTATLKEAAVELTEQGSATIHFSTANIHPEFRLQICTSYVT
CKGDCHPPKDHIVTH-*

>P1;7KO8B
sequence:7KO8B:    1: :  388: :::-1.00:-1.00
YEHTAVIPNQVGFPYKAHVAREGYSPLTLQMQVVETSLEPTLNLEYITCDYKTKVPSPYVKCCGTAECRTQDKPE
YKCAVFTGVYPFMWGGAYCFCDSENTQMSEAYVERADVCKHDYAAAYRAHTASLRAKIKVTYGTVNQTVEAYVNG
DHAVTIAGTKFIFGPVSTAWTPFDTKIVVYKGEVYNQDFPPYGAGQPGRFGDIQSRTLDSKDLYANTGLKLARPA
AGNIHVPYTQTPSGFKTWQKDRDSPLNAKAPFGCTIQTNPVRAMNCAVGNIPVSMDIADSAFTRLTDAPIISELL
CTVSTCTHSSDFGGVAVLSYKVEKAGRCDVHSHSNVAVLQEVS--IEAEGRSVIHFSTASAAPSFIVSVCSSRAT
CTAKCEPPKDHVVTY-*

>P1;7KO8E
sequence:7KO8E:    1: :  388: :::-1.00:-1.00
YEHTAVIPNQVGFPYKAHVAREGYSPLTLQMQVVETSLEPTLNLEYITCDYKTKVPSPYVKCCGTAECRTQDKPE
YKCAVFTGVYPFMWGGAYCFCDSENTQMSEAYVERADVCKHDYAAAYRAHTASLRAKIKVTYGTVNQTVEAYVNG
DHAVTIAGTKFIFGPVSTAWTPFDTKIVVYKGEVYNQDFPPYGAGQPGRFGDIQSRTLDSKDLYANTGLKLARPA
AGNIHVPYTQTPSGFKTWQKDRDSPLNAKAPFGCTIQTNPVRAMNCAVGNIPVSMDIADSAFTRLTDAPIISELL
CTVSTCTHSSDFGGVAVLSYKVEKAGRCDVHSHSNVAVLQEVS--IEAEGRSVIHFSTASAAPSFIVSVCSSRAT
CTAKCEPPKDHVVTY-*

>P1;7KO8H
sequence:7KO8H:    1: :  388: :::-1.00:-1.00
YEHTAVIPNQVGFPYKAHVAREGYSPLTLQMQVVETSLEPTLNLEYITCDYKTKVPSPYVKCCGTAECRTQDKPE
YKCAVFTGVYPFMWGGAYCFCDSENTQMSEAYVERADVCKHDYAAAYRAHTASLRAKIKVTYGTVNQTVEAYVNG
DHAVTIAGTKFIFGPVSTAWTPFDTKIVVYKGEVYNQDFPPYGAGQPGRFGDIQSRTLDSKDLYANTGLKLARPA
AGNIHVPYTQTPSGFKTWQKDRDSPLNAKAPFGCTIQTNPVRAMNCAVGNIPVSMDIADSAFTRLTDAPIISELL
CTVSTCTHSSDFGGVAVLSYKVEKAGRCDVHSHSNVAVLQEVS--IEAEGRSVIHFSTASAAPSFIVSVCSSRAT
CTAKCEPPKDHVVTY-*

>P1;7KO8L
sequence:7KO8L:    1: :  388: :::-1.00:-1.00
YEHTAVIPNQVGFPYKAHVAREGYSPLTLQMQVVETSLEPTLNLEYITCDYKTKVPSPYVKCCGTAECRTQDKPE
YKCAVFTGVYPFMWGGAYCFCDSENTQMSEAYVERADVCKHDYAAAYRAHTASLRAKIKVTYGTVNQTVEAYVNG
DHAVTIAGTKFIFGPVSTAWTPFDTKIVVYKGEVYNQDFPPYGAGQPGRFGDIQSRTLDSKDLYANTGLKLARPA
AGNIHVPYTQTPSGFKTWQKDRDSPLNAKAPFGCTIQTNPVRAMNCAVGNIPVSMDIADSAFTRLTDAPIISELL
CTVSTCTHSSDFGGVAVLSYKVEKAGRCDVHSHSNVAVLQEVS--IEAEGRSVIHFSTASAAPSFIVSVCSSRAT
CTAKCEPPKDHVVTY-*

>P1;7N1HE
sequence:7N1HE:    1: :  390: :::-1.00:-1.00
YEHATTMPSQAGISYNTIVNRAGYAPLPISITPTKIKLIPTVNLEYVTCHYKTGMDSPAIKCCGSQECTPTYRPD
EQCKVFTGVYPFMWGGAYCFCDTENTQVSKAYVMKSDDCLADHAEAYKAHTASVQAFLNITVGEHSIVTTVYVNG
ETPVNFNGVKITAGPLSTAWTPFDRKIVQYAGEIYNYDFPEYGAGQPGAFGDIQSRTVSSSDLYANTNLVLQRPK
AGAIHVPYTQAPSGFEQWKKDKAPSLKFTAPFGCEIYTNPIRAENCAVGSIPLAFDIPDALFTRVSETPTLSAAE
CTLNECVYSSDFGGIATVKYSASKSGKCAVHVPSGTATLKEAAVELTEQGSATIHFSTANIHPEFRLQICTSYVT
CKGDCHPPKDHIVTH-*

>P1;7N1HH
sequence:7N1HH:    1: :  390: :::-1.00:-1.00
YEHATTMPSQAGISYNTIVNRAGYAPLPISITPTKIKLIPTVNLEYVTCHYKTGMDSPAIKCCGSQECTPTYRPD
EQCKVFTGVYPFMWGGAYCFCDTENTQVSKAYVMKSDDCLADHAEAYKAHTASVQAFLNITVGEHSIVTTVYVNG
ETPVNFNGVKITAGPLSTAWTPFDRKIVQYAGEIYNYDFPEYGAGQPGAFGDIQSRTVSSSDLYANTNLVLQRPK
AGAIHVPYTQAPSGFEQWKKDKAPSLKFTAPFGCEIYTNPIRAENCAVGSIPLAFDIPDALFTRVSETPTLSAAE
CTLNECVYSSDFGGIATVKYSASKSGKCAVHVPSGTATLKEAAVELTEQGSATIHFSTANIHPEFRLQICTSYVT
CKGDCHPPKDHIVTH-*

>P1;7N1HK
sequence:7N1HK:    1: :  390: :::-1.00:-1.00
YEHATTMPSQAGISYNTIVNRAGYAPLPISITPTKIKLIPTVNLEYVTCHYKTGMDSPAIKCCGSQECTPTYRPD
EQCKVFTGVYPFMWGGAYCFCDTENTQVSKAYVMKSDDCLADHAEAYKAHTASVQAFLNITVGEHSIVTTVYVNG
ETPVNFNGVKITAGPLSTAWTPFDRKIVQYAGEIYNYDFPEYGAGQPGAFGDIQSRTVSSSDLYANTNLVLQRPK
AGAIHVPYTQAPSGFEQWKKDKAPSLKFTAPFGCEIYTNPIRAENCAVGSIPLAFDIPDALFTRVSETPTLSAAE
CTLNECVYSSDFGGIATVKYSASKSGKCAVHVPSGTATLKEAAVELTEQGSATIHFSTANIHPEFRLQICTSYVT
CKGDCHPPKDHIVTH-*

>P1;7N1HN
sequence:7N1HN:    1: :  390: :::-1.00:-1.00
YEHATTMPSQAGISYNTIVNRAGYAPLPISITPTKIKLIPTVNLEYVTCHYKTGMDSPAIKCCGSQECTPTYRPD
EQCKVFTGVYPFMWGGAYCFCDTENTQVSKAYVMKSDDCLADHAEAYKAHTASVQAFLNITVGEHSIVTTVYVNG
ETPVNFNGVKITAGPLSTAWTPFDRKIVQYAGEIYNYDFPEYGAGQPGAFGDIQSRTVSSSDLYANTNLVLQRPK
AGAIHVPYTQAPSGFEQWKKDKAPSLKFTAPFGCEIYTNPIRAENCAVGSIPLAFDIPDALFTRVSETPTLSAAE
CTLNECVYSSDFGGIATVKYSASKSGKCAVHVPSGTATLKEAAVELTEQGSATIHFSTANIHPEFRLQICTSYVT
CKGDCHPPKDHIVTH-*

>P1;7N1IA
sequence:7N1IA:    1: :  390: :::-1.00:-1.00
YEHATTMPSQAGISYNTIVNRAGYAPLPISITPTKIKLIPTVNLEYVTCHYKTGMDSPAIKCCGSQECTPTYRPD
EQCKVFTGVYPFMWGGAYCFCDTENTQVSKAYVMKSDDCLADHAEAYKAHTASVQAFLNITVGEHSIVTTVYVNG
ETPVNFNGVKITAGPLSTAWTPFDRKIVQYAGEIYNYDFPEYGAGQPGAFGDIQSRTVSSSDLYANTNLVLQRPK
AGAIHVPYTQAPSGFEQWKKDKAPSLKFTAPFGCEIYTNPIRAENCAVGSIPLAFDIPDALFTRVSETPTLSAAE
CTLNECVYSSDFGGIATVKYSASKSGKCAVHVPSGTATLKEAAVELTEQGSATIHFSTANIHPEFRLQICTSYVT
CKGDCHPPKDHIVTH-*

>P1;7N1ID
sequence:7N1ID:    1: :  390: :::-1.00:-1.00
YEHATTMPSQAGISYNTIVNRAGYAPLPISITPTKIKLIPTVNLEYVTCHYKTGMDSPAIKCCGSQECTPTYRPD
EQCKVFTGVYPFMWGGAYCFCDTENTQVSKAYVMKSDDCLADHAEAYKAHTASVQAFLNITVGEHSIVTTVYVNG
ETPVNFNGVKITAGPLSTAWTPFDRKIVQYAGEIYNYDFPEYGAGQPGAFGDIQSRTVSSSDLYANTNLVLQRPK
AGAIHVPYTQAPSGFEQWKKDKAPSLKFTAPFGCEIYTNPIRAENCAVGSIPLAFDIPDALFTRVSETPTLSAAE
CTLNECVYSSDFGGIATVKYSASKSGKCAVHVPSGTATLKEAAVELTEQGSATIHFSTANIHPEFRLQICTSYVT
CKGDCHPPKDHIVTH-*

>P1;7N1IG
sequence:7N1IG:    1: :  390: :::-1.00:-1.00
YEHATTMPSQAGISYNTIVNRAGYAPLPISITPTKIKLIPTVNLEYVTCHYKTGMDSPAIKCCGSQECTPTYRPD
EQCKVFTGVYPFMWGGAYCFCDTENTQVSKAYVMKSDDCLADHAEAYKAHTASVQAFLNITVGEHSIVTTVYVNG
ETPVNFNGVKITAGPLSTAWTPFDRKIVQYAGEIYNYDFPEYGAGQPGAFGDIQSRTVSSSDLYANTNLVLQRPK
AGAIHVPYTQAPSGFEQWKKDKAPSLKFTAPFGCEIYTNPIRAENCAVGSIPLAFDIPDALFTRVSETPTLSAAE
CTLNECVYSSDFGGIATVKYSASKSGKCAVHVPSGTATLKEAAVELTEQGSATIHFSTANIHPEFRLQICTSYVT
CKGDCHPPKDHIVTH-*

>P1;7N1IJ
sequence:7N1IJ:    1: :  390: :::-1.00:-1.00
YEHATTMPSQAGISYNTIVNRAGYAPLPISITPTKIKLIPTVNLEYVTCHYKTGMDSPAIKCCGSQECTPTYRPD
EQCKVFTGVYPFMWGGAYCFCDTENTQVSKAYVMKSDDCLADHAEAYKAHTASVQAFLNITVGEHSIVTTVYVNG
ETPVNFNGVKITAGPLSTAWTPFDRKIVQYAGEIYNYDFPEYGAGQPGAFGDIQSRTVSSSDLYANTNLVLQRPK
AGAIHVPYTQAPSGFEQWKKDKAPSLKFTAPFGCEIYTNPIRAENCAVGSIPLAFDIPDALFTRVSETPTLSAAE
CTLNECVYSSDFGGIATVKYSASKSGKCAVHVPSGTATLKEAAVELTEQGSATIHFSTANIHPEFRLQICTSYVT
CKGDCHPPKDHIVTH-*
