>P1;3BXN
structureN:3BXN::A:276:B:1:::
GSHSMRYFYTA-VSRPGRGEPRFI-SVGYVDDTQFVRFDSDAASPR-EEPRAP-WIEQEG
PEYWDRNTQI-CKTNTQT-DRE-SLR--NLRGYYNQSEAGSH--TLQ-WMYGCD-VGPDG
RLLRG--YNQ-FAYDGKDYIALNEDLSSWTAADTAAQITQRKWEAAR-EAEQLRAYLEG-
TCVEWLRR-HLENGKETLQRADPPKTHVTHHP-ISDHEATLRCWALGFYPAEITLTWQRD
GEDQTQDTELVETRPAGDRTFQKWAAVVVPSGEEQRYTCHVQHEGLPKPLTLRWEP--/I
QRTPKIQVYSRHPAENGKSNFLNCYVSGFHPSDIEVDLLKNGERIEKVEHSDLSFSKDWS
FYLLYYTEFTPTEKDEYACRVNHVTLSQPKIVKWDRDM*

>P1;1A1MA_1A1MB
sequence:1A1MA_1A1MB: :A:376:B:1: : : 
GSHSMRYFYTAM-SRPGRGEPRFIA-VGYVDDTQFVRFDSDAASPRT-EPR-PPWIEQEG
PEYWDRNTQIF-KTNTQTY-REN-LRIA-LR-YYNQSEAGSHII--QR-MYGCDL-GPDG
RLLRGHD--QS-AYDGKDYIALNEDLSSWTAADTAAQITQRKWEAARV-AEQLRAYLEGL
-CVEWLRRY-LENGKETLQRADPPKTHVTHHPV-SDHEATLRCWALGFYPAEITLTWQRD
GEDQTQDTELVETRPAGDRTFQKWAAVVVPSGEEQRYTCHVQHEGLPKPLTLRWEPHH/I
QRTPKIQVYSRHPAENGKSNFLNCYVSGFHPSDIEVDLLKNGERIEKVEHSDLSFSKDWS
FYLLYYTEFTPTEKDEYACRVNHVTLSQPKIVKWDRDM*
