
>P1;5GNIA
sequence:5GNIA:    0: :    0: :::-1.00:-1.00
SFTINSVDMKSLPDWTVQNGKQLTLQCFADVSTTSKPQHQMLFYKDDVLFYQISSMKSTESYFIPEVRIYDSGTY
KCTVIVNNKEKTTAEYQLLVEGVPSPRVTLDKKEAIQGGIVRVQCSVPEEKAPIHFTIEKLELNEKMVKLKREKN
SRDQNFVILEFPVEEQDRVLSFRCQARIISGIHMQTSESTKSELVT*

>P1;5gniA
structure:5gniA:    1: :  196: :::-1.00:-1.00
SFTINSVDMKSLPDWTVQNGKQLTLQCFADVSTTSKPQHQMLFYKDDVLFYQISSMKSTESYFIPEVRIYDSGTY
KCTVIVNNKEKTTAEYQLLVEGVPSPRVTLDKKEAIQGGIVRVQCSVPEEKAPIHFTIEKLELNEKMVKLKREKN
SRDQNFVILEFPVEEQDRVLSFRCQARIISGIHMQTSESTKSELVT*

>P1;5gniB
structure:5gniB:    1: :  197: :::-1.00:-1.00
SFTINSVDMKSLPDWTVQNGKQLTLQCFADVSTTSKPQHQMLFYKDDVLFYQISSMKSTESYFIPEVRIYDSGTY
KCTVIVNNKEKTTAEYQLLVEGVPSPRVTLDKKEAIQGGIVRVQCSVPEEKAPIHFTIEKLELNEKMVKLKREKN
SRDQNFVILEFPVEEQDRVLSFRCQARIISGIHMQTSESTKSELVT*

>P1;5c14A
structure:5c14A:    1: :  198: :::-1.00:-1.00
SFTINSVDMKSLPDWTVQNGKNLTLQCFADVSTTSKPQHQMLFYKDDVLFYNISSMKSTESYFIPEVRIYDSGTY
KCTVIVNNKEKTTAEYQLLVEGVPSPRVTLDKKEAIQGGIVRVNCSVPEEKAPIHFTIEKLELNEKMVKLKREKN
SRDQNFVILEFPVEEQDRVLSFRCQARIISGIHMQTSESTKSELVT*

>P1;5c14B
structure:5c14B:    1: :  198: :::-1.00:-1.00
SFTINSVDMKSLPDWTVQNGKNLTLQCFADVSTTSKPQHQMLFYKDDVLFYNISSMKSTESYFIPEVRIYDSGTY
KCTVIVNNKEKTTAEYQLLVEGVPSPRVTLDKKEAIQGGIVRVNCSVPEEKAPIHFTIEKLELNEKMVKLKREKN
SRDQNFVILEFPVEEQDRVLSFRCQARIISGIHMQTSESTKSELVT*
